### ISSUE TITLE
Determine correct buildtools-wide xunit version

### ISSUE THREAD

**Issue by dagood** [dotnet/buildtools#1004]
Currently there are multiple versions, and it would be good to add one repo-wide version to dependency validation.

Created this task to avoid figuring this out while working on https://github.com/dotnet/buildtools/issues/954 (Upgrade buildtools to RTM shared framework).

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
