### ISSUE TITLE
Improve core dump handling

### ISSUE THREAD

**Issue by adityamandaleeka** [dotnet/buildtools#1021]
When we first enabled dump collection in buildtools, it was on par with CoreCLR's dump collection and was carefully designed to avoid issues like flooding machines with dumps or having dump-related settings persist between tests when they shouldn't.

However, since then, the CoreCLR dump story has moved forward substantially (with automatic uploading and improved OS X dump management being just two of the areas where the experience has been greatly improved). Similar changes were not made in buildtools, partly because the service being used for uploads was still being brought up (we didn't want to add more load than necessary) and partly because there were concerns about adding more dump-related logic into the runner scripts where it lives today.

If someone familiar with buildtools and the various places where it's used can propose where the core dump logic should live going forward, we can move it there and bring the experience up to par with what we have in CoreCLR.

**Comment by weshaggard** [comment]
We have already created the dumping.targets to tackle this.
