### ISSUE TITLE
ExternalPackages cleanup in AddDependenciesToProjectJson

### ISSUE THREAD

**Issue by chcosta** [dotnet/buildtools#1023]
ExternalPackage versions are no longer used, we now use exclusively the package drop or a versions file.   ExternalPackage code should be cleaned up from BuildTools in these locations:

https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks/AddDependenciesToProjectJson.cs#L57
https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks/AddDependenciesToProjectJson.cs#L288
https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks/AddDependenciesToProjectJson.cs#L288

**Comment by weshaggard** [comment]
Triage: This is no longer applicable but we should probably re-purpose this to completely remove AddDependneciesToProjectJson task itself.

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
