### ISSUE TITLE
Add property to version-stable location of dotnet.exe

### ISSUE THREAD

**Issue by jhendrixMSFT** [dotnet/buildtools#1045]
In https://github.com/dotnet/buildtools/pull/1038 a change was made to make the path to the shared framework copy of dotnet.exe resilient to versioning, e.g. $RepoRoot\Tools\dotnetcli\shared\Microsoft.NETCore.App\version\dotnet.exe; this way when the CLI is updated and a new version of FX is brought it we don't need to update a bunch of runtime config JSON files.  Only run.ps1 is consuming this at present, we need to expose this in our msbuild targets so that tools like GenAPI.exe etc can take advantage of it.  The change would likely go in toolruntime.targets that ships as a part of build tools.

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
