### ISSUE TITLE
Refactor properties out of repo's and into BuildTools where appropriate

### ISSUE THREAD

**Issue by chcosta** [dotnet/buildtools#1049]
Related to build cleanup - https://github.com/chcosta/corefx/blob/f2673c97a30e8ad79b0dc4c4bb7b29cc2454def8/Documentation/building/build-guidelines.md

**Comment by chcosta** [comment]
As an initial pass, I'm going to look at all of the places in CoreFx where we are defining properties which are compound properties (built up from other properties).  Not all of these will be ideal to move into BuildTools, but this seems like a good list to start with and examine closer.

[Compound Properties List (CoreFx)](https://github.com/dotnet/buildtools/files/480718/compoundproperties.txt)

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
