### ISSUE TITLE
Refactor targets out of repo's and into BuildTools where appropriate

### ISSUE THREAD

**Issue by chcosta** [dotnet/buildtools#1050]
Related to https://github.com/chcosta/corefx/blob/f2673c97a30e8ad79b0dc4c4bb7b29cc2454def8/Documentation/building/build-guidelines.md

Also see https://github.com/dotnet/buildtools/issues/1049

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
