### ISSUE TITLE
After a retry, SendToHelix task doesn't actually log success

### ISSUE THREAD

**Issue by MattGal** [dotnet/buildtools#1058]
Reading the source code, one can INFER when success happens, but it's unclear after a bunch of retries what really happens from the logs:

https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.CloudTestTasks/SendToHelix.cs#L92

Example:
  D:\A_work\18\s\Tools\CloudTest.targets(425,5): warning : Helix Api Response: StatusCode Unauthorized You do not have permission to view this directory or page. [D:\A_work\18\s\src\post.builds]
  D:\A_work\18\s\Tools\CloudTest.targets(425,5): warning : Failed to publish to 'https://helix.int-dot.net/api/2016-06-28/jobs', 11 retries remaining [D:\A_work\18\s\src\post.builds]
  D:\A_work\18\s\Tools\CloudTest.targets(425,5): warning : Helix Api Response: StatusCode Unauthorized You do not have permission to view this directory or page. [D:\A_work\18\s\src\post.builds]
  D:\A_work\18\s\Tools\CloudTest.targets(425,5): warning : Failed to publish to 'https://helix.int-dot.net/api/2016-06-28/jobs', 10 retries remaining [D:\A_work\18\s\src\post.builds]
    10 Warning(s)
    0 Error(s)

(this is "successful")

**Comment by dleeapho** [comment]
Nice to have since you can infer success.
