### ISSUE TITLE
test-archiving is failing in our release branch. 

### ISSUE THREAD

**Issue by weshaggard** [dotnet/buildtools#1064]
We need to port change #1052 to a release branch of build tools so we can consume it in our corefx release/1.1.0 branch.

We will need to fork at whatever version 
1.0.26-prerelease-00802-01 (https://github.com/dotnet/corefx/blob/release/1.1.0/BuildToolsVersion.txt), points to.

**Comment by gkhanna79** [comment]
This is blocking 1.1.0.

CC @leecow

**Comment by ericstj** [comment]
I think we'll need a later codebase.  I've brought us up to 1.0.26-prerelease-00819-01 in a PR I am preparing to fix https://github.com/dotnet/corefx/issues/12028.
