### ISSUE TITLE
Improve BinClashLogger alert

### ISSUE THREAD

**Issue by danmoseley** [dotnet/buildtools#1067]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/windows_nt_release_prtest/693/
failed with

MSBuild Error

error MSB4015: The build stopped unexpectedly because the "ReusableLogger" logger failed unexpectedly during shutdown.
Indication 1 

if you look at the log though, it's the BinClashLogger telling us about a problem. Probably there is no way to do this cleaner than throwing an exception but we should add an Indication to jenkins for 

Error : Multiple projects built twice with the same target path D:\j\workspace\windows_nt_re---37265eab\bin\Windows_NT.AnyCPU.Release\System.Net.Requests\System.Net.Requests.dll.

MSBUILD : error MSB4015: The build stopped unexpectedly because the "ReusableLogger" logger failed unexpectedly during shutdown.
11:16:46 System.Exception: 1 bin clashes were detected during the build.
11:16:46    at Microsoft.DotNet.Build.Tasks.BinClashLogger.Shutdown()
11:16:46    at Microsoft.Build.Evaluation.ProjectCollection.ReusableLogger.Shutdown()
11:16:46    at Microsoft.Build.BackEnd.Logging.LoggingService.ShutdownLogger(ILogger logger)
11:16:46 Error : Multiple projects built twice with the same target path D:\j\workspace\windows_nt_re---37265eab\bin\Windows_NT.AnyCPU.Release\System.Net.Requests\System.Net.Requests.dll.
11:16:46 D:\j\workspace\windows_nt_re---37265eab\build.proj -->
11:16:46   Global Properties:
11:16:46     OSGroup = Windows_NT
11:16:46     TargetOS = Windows_NT
11:16:46     ConfigurationGroup = Release
11:16:46     WithoutCategories = IgnoreForCI
11:16:46 D:\j\workspace\windows_nt_re---37265eab\src\dirs.proj -->
11:16:46   Global Properties:
11:16:46     TargetOS = Windows_NT
11:16:46     ConfigurationGroup = Release
11:16:46     WithoutCategories = IgnoreForCI
11:16:46     DefaultBuildAllTarget = Build
11:16:46     BuildAllProjects = true
11:16:46     InputOSGroup = Windows_NT
11:16:46     FilterToOSGroup = Windows_NT
11:16:46 D:\j\workspace\windows_nt_re---37265eab\src\src.builds -->
11:16:46   Global Properties:
11:16:46     TargetOS = Windows_NT
11:16:46     ConfigurationGroup = Release
11:16:46     WithoutCategories = IgnoreForCI
11:16:46     DefaultBuildAllTarget = Build
11:16:46     BuildAllProjects = true
11:16:46     InputOSGroup = Windows_NT
11:16:46     FilterToOSGroup = Windows_NT
11:16:46 D:\j\workspace\windows_nt_re---37265eab\src\System.Private.Xml\src\System.Private.Xml.builds -->
11:16:46   Global Properties:
11:16:46     TargetOS = Windows_NT
11:16:46     ConfigurationGroup = Release
11:16:46     WithoutCategories = IgnoreForCI
11:16:46     DefaultBuildAllTarget = Build
11:16:46     BuildAllProjects = true
11:16:46     InputOSGroup = Windows_NT
11:16:46     FilterToOSGroup = Windows_NT
11:16:46 D:\j\workspace\windows_nt_re---37265eab\src\System.Private.Xml\src\System.Private.Xml.csproj -->
11:16:46   Global Properties:
11:16:46     TargetOS = Windows_NT
11:16:46     ConfigurationGroup = Release
11:16:46     WithoutCategories = IgnoreForCI
11:16:46     BuildAllProjects = true
11:16:46     InputOSGroup = Windows_NT
11:16:46 D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Requests\src\System.Net.Requests.csproj
11:16:46   Global Properties:
11:16:46     TargetOS = Windows_NT
11:16:46     ConfigurationGroup = Release
11:16:46     WithoutCategories = IgnoreForCI
11:16:46     BuildAllProjects = true
11:16:46     InputOSGroup = Windows_NT
11:16:46 
11:16:46 D:\j\workspace\windows_nt_re---37265eab\build.proj -->
11:16:46   Global Properties:
11:16:46     OSGroup = Windows_NT
11:16:46     TargetOS = Windows_NT
11:16:46     ConfigurationGroup = Release
11:16:46     WithoutCategories = IgnoreForCI
11:16:46 D:\j\workspace\windows_nt_re---37265eab\src\dirs.proj -->
11:16:46   Global Properties:
11:16:46     TargetOS = Windows_NT
11:16:46     ConfigurationGroup = Release
11:16:46     WithoutCategories = IgnoreForCI
11:16:46     DefaultBuildAllTarget = Build
11:16:46     BuildAllProjects = true
11:16:46     InputOSGroup = Windows_NT
11:16:46     FilterToOSGroup = Windows_NT
11:16:46 D:\j\workspace\windows_nt_re---37265eab\src\src.builds -->
11:16:46   Global Properties:
11:16:46     TargetOS = Windows_NT
11:16:46     ConfigurationGroup = Release
11:16:46     WithoutCategories = IgnoreForCI
11:16:46     DefaultBuildAllTarget = Build
11:16:46     BuildAllProjects = true
11:16:46     InputOSGroup = Windows_NT
11:16:46     FilterToOSGroup = Windows_NT
11:16:46 D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Requests\src\System.Net.Requests.builds -->
11:16:46   Global Properties:
11:16:46     TargetOS = Windows_NT
11:16:46     ConfigurationGroup = Release
11:16:46     WithoutCategories = IgnoreForCI
11:16:46     DefaultBuildAllTarget = Build
11:16:46     BuildAllProjects = true
11:16:46     InputOSGroup = Windows_NT
11:16:46     FilterToOSGroup = Windows_NT
11:16:46 D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Requests\src\System.Net.Requests.csproj
11:16:46   Global Properties:
11:16:46     TargetOS = Windows_NT
11:16:46     ConfigurationGroup = Release
11:16:46     WithoutCategories = IgnoreForCI
11:16:46     BuildAllProjects = true
11:16:46     InputOSGroup = Windows_NT
11:16:46     OSGroup = Windows_NT
11:16:46 
11:16:46 
11:16:46

**Comment by dleeapho** [comment]
We should add a Jenkins indicator for this condition.

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
