### ISSUE TITLE
Fix GetPerfTestAssemblies to throw warning instead of error when no perf assemblies where found

### ISSUE THREAD

**Issue by joperezr** [dotnet/buildtools#1074]
Currently in corefx, we are running all of our perftests with netcoreapp1.0 and the FilterToTestTFM is set to netcoreapp1.1, so when we run this task on our official builds, it can't find any assemblies as it tries to find them under a netcoreapp1.0 folder. For this reason, we should instead throw a warning instead of failing the builds due to this.

FYI: @weshaggard 
cc: @MattGal

**Comment by MattGal** [comment]
@joperezr  agreed, but we do need some kind of indication if a test build produced no output at all.  If it's just a warning, it's fairly likely to be ignored.  Do you have any suggestions?

**Comment by joperezr** [comment]
I agree that a warning might be dismissed, but I also think that given that the logic itself for finding test archives is flaky then we definitely shouldn't break the build for this, which is why my suggestion is still to move it to a warning. Check issue #1076 that I logged this morning which contains a bit more explanation of how the logic for archiving and finding test zip files is error-prone

**Comment by MattGal** [comment]
@joperezr with the AnyOS bug fix from earlier fixed, we should be able to turn perf tests back on.

**Comment by MattGal** [comment]
Closing as the requested change was made...
