### ISSUE TITLE
The archiving of the test build shouldn't use project-specific configuration for the location of the zip

### ISSUE THREAD

**Issue by joperezr** [dotnet/buildtools#1076]
Today, official builds have a step after running tests for a particular project that zips them and puts them in a directory. The selection of this directory, [is using that project's specific configuration](https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks/PackageFiles/publishtest.targets#L254-L255) to build the `<TestArchiveDir>`.

Once all test builds and runs are done, we use a _centralized_ project to call a target on it, which will push to helix all of these zip files. This project obviously is not aware of the individual project's configuration, so [it tries to make wild guesses](https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.targets#L311-L330) to try to find where these zip files live. We were getting lucky before and it was being able to find them, but that is not the case anymore since we recently added a bit more logic on where the perf zip tests are located for netcoreapp1.1 runs (they use to live in ...\archives\netcoreapp1.1*.zip folder, and now they live in ...\archives\netstandard1.7\netcoreapp1.1*.zip) so the zip files can't be found any longer. This problem is currently blocking our official builds.

The proposed solution would be to instead use a static test archive dir where all zip files are located, and only add any project specific configuration to the name of the zip file if needed.

cc: @weshaggard @markwilkie @chcosta @MattGal

**Comment by weshaggard** [comment]
On top of that we should not see things like OSPlatformConfig at all in any of the non-project-specific targets like https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.targets#L41.

**Comment by bartonjs** [comment]
@weshaggard If that's saying "we don't have any OSGroup-specific test builds", that's not true (though, I suppose, with enough work it could be).  If it's saying that OSGroup-specific things are handled at a different layer, that's fine.

**Comment by weshaggard** [comment]
>@weshaggard If that's saying "we don't have any OSGroup-specific test builds", that's not true (though, I suppose, with enough work it could be). If it's saying that OSGroup-specific things are handled at a different layer, that's fine.

They should be handled at a different layer. For example:

```
<ArchivesRoot>$(TestWorkingDir)$(OSPlatformConfig)/archive/</ArchivesRoot>
```
That should be:
```
<ArchivesRoot>$(TestWorkingDir)/archive/</ArchivesRoot>
```
And then we can work on everything under the archive folder and individual projects can still put assets under an OSPlatformConfig sub-folder there. The individual projects actually have the right context to do that whereas the overarching post-build step doesn't have the right context and so it shouldn't assume that everything for a given build went into an OSPlatformConfig based directory.

**Comment by bartonjs** [comment]
Okay, cool with me.  I just wanted to make sure that none of the platform-specific-build tests got broken by that.

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
