### ISSUE TITLE
Run.exe's usage output is always max verbosity

### ISSUE THREAD

**Issue by MattGal** [dotnet/buildtools#1078]
Currently, when using -? to get help with the standard developer work flow, the output ends up as several pages of information, much of which is not necessary to actually use the program.

Ideally the basics of each command could be shown using 1-2 lines apiece and fitting on a single page;  Users could see the large paragraph explaining what run.exe is, every option, and the resultant msbuild command produced with an argument like "-?  -v " or similar.

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
