### ISSUE TITLE
Consider not requiring '-' character before action verbs for Run.exe

### ISSUE THREAD

**Issue by MattGal** [dotnet/buildtools#1079]
Consider how a tool like dotnet.exe works:
To restore nuget packages (a command), one calls: **dotnet restore**, to publish **dotnet publish** etc.

For the commands supported by Run.exe, they are not stored in config.json this way but they expect and print usage with a '-' character preceding them, e.g. "**build.cmd -binaries**"

This behavior is confusing to the user since a flag like -binaries looks to the untrained eye more like a flag or a parameter versus an action.

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
