### ISSUE TITLE
Inherit some Run.exe config from buildtools

### ISSUE THREAD

**Issue by dagood** [dotnet/buildtools#1085]
Some commands are shared between all buildtools-using repos because they only use functionality defined in buildtools. Instead of repeating these commands in each repo's `config.json`, they should be inherited from a repo-agnostic `config.json` defined in buildtools.

Most recently I brought this up in https://github.com/dotnet/buildtools/issues/1046#issuecomment-250205226, and I realized that there isn't an issue for this (that I could see).

@maririos @markwilkie Is there a plan already for someone to work on this?

**Comment by markwilkie** [comment]
@MattGal - this should probably be a part of the dev workflow work you're looking into.

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
