### ISSUE TITLE
Remove use of AllowFallbackOnTargetSelection

### ISSUE THREAD

**Issue by ericstj** [dotnet/buildtools#1086]
This is causing mismatched NuGetTargetMoniker and project.json to result in a warning, which folks never pay attention to, until they pile up.  EG: https://github.com/dotnet/corefx/issues/12233

When this change is made we'll need to make sure corefx is in good shape and we weren't relying on the fallback behavior anywhere.

/cc @alexperovich

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
