### ISSUE TITLE
Run.exe can capture input state, resulting in strange console behavior

### ISSUE THREAD

**Issue by MattGal** [dotnet/buildtools#1089]
I routinely run into this issue when using Ctrl-C / Break to cancel a build started by Run.exe.  The symptoms include:
- Tab no longer causes file name completion, but rather inserts a tab (indentation)
- Pressing Enter/Return causes a carriage return the first time, works as expected the second time.

There's no obvious reason for this;  there's some theories around it being related to Win32 APIs that the System.Console libraries PInvoke to, but no proof yet.

**Comment by dleeapho** [comment]
@MattGal believes this is a CLI issue. It could also be related to the way we start the process. Could also be we were using an old CLI. In any case this is a major annoyance.

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
