### ISSUE TITLE
Change project type for Run.exe to a dotnet core app

### ISSUE THREAD

**Issue by MattGal** [dotnet/buildtools#1090]
Currently Run.exe builds as a "Portable .NET Console app" project type despite being runnable from dotnet.exe.  As such, F5 debugging of the project doesn't work.

For engineers working to debug and add features to this library, having a F5-debug-able project makes good sense and should be fairly cheap.

**Comment by dleeapho** [comment]
Would be great to fix with other run.exe work.

**Comment by ViktorHofer** [comment]
Closing as the buildtools repository has been archived and replaced by https://github.com/dotnet/arcade.
