### ISSUE TITLE
Xunit UWP runner crashes on certain invalid char enums

### ISSUE THREAD

**Issue by hughbe** [dotnet/buildtools#1091]
Yes, char enums do exist! When moved into MemberData, the tests found here: https://github.com/dotnet/corefx/blob/master/src/System.Runtime/tests/System/EnumTests.cs#L1453-L1461 crash with the following mesage:
![error](https://cloud.githubusercontent.com/assets/1275900/19095982/05241d1a-8a91-11e6-8ce9-fd9e6f53d02e.png)

Note: I have tested and made sure that invalid chars work, so that part of the crashing bug is fixed.

/cc @jamesqo

**Comment by dleeapho** [comment]
Fix when we work on UWP runner for NS 2.0
