### ISSUE TITLE
Handle assembly binding when running tests against full framework

### ISSUE THREAD

**Issue by tarekgh** [dotnet/buildtools#1092]
When running the tests against full framework (TestTFM is net46x), we run into assembly binding issues by the loader because the loader can load the older version of the assembly which cause runtime error like: 

```
System.IO.IsolatedStorage.Tests.HelperTests.GetNormalizedStrongNameHash [FAIL]
        System.IO.FileLoadException : Could not load file or assembly 'System.Security.Cryptography.Primitives, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) 
```

I believe the way to fix this is to add the following to tests.targets:

``` XML
  <PropertyGroup>
   <!-- Add the following properties -->
    <_IsNet4XTFM Condition="$(TestTFM.StartsWith('net4'))">true</_IsNet4XTFM>
    <AutoGenerateBindingRedirects Condition="'$(_IsNet4XTFM)' =='true'">true</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType Condition="'$(_IsNet4XTFM)' =='true'">true</GenerateBindingRedirectsOutputType>
  </PropertyGroup>


  <Target Name="DiscoverTestInputs" DependsOnTargets="ResolveProjectReferences;ResolveAssemblyReferences;GetCopyToOutputDirectoryItems">
    <ItemGroup>
     ….

      <!-- Add the following properties -->
      <RunTestsForProjectInputs Include="$(TargetPath).config" /> 
    </ItemGroup>
  </Target>

  <PropertyGroup>
    <XunitResultsFileName>testResults.xml</XunitResultsFileName>

    <!-- Add $(TargetFileName).config to xunit runner parameters -->
    <XunitOptions Condition="'$(_IsNet4XTFM)' == 'true'">$(XunitOptions) $(TargetFileName).config -noshadow </XunitOptions>
…
  </PropertyGroup>
```

**Comment by tarekgh** [comment]
CC @ericstj @JeremyKuhne

**Comment by ericstj** [comment]
/cc @weshaggard 
For this to work ResolveAssemblyReferences (RAR) will need to see the desktop assemblies.  Not sure if that will necessarily happen in the cases where we compile against netstandard but run against net4*.

**Comment by jiangzeng** [comment]
Reopen this ticket as Corefx Desktop runs still have lots of tests failed with "System.IO.FileLoadException : Could not load file or assembly XXX" or "System.IO.FileNotFoundException : Could not load file or assembly XXX".
Examples in build 20161219.02:
Common.Tests (Desktop) --- [https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fdesktop~2Fcli~2F/build/20161219.02/workItem/Common.Tests](url)
System.Collections.NonGeneric.Tests (Desktop) --- https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fdesktop~2Fcli~2F/build/20161219.02/workItem/System.Collections.NonGeneric.Tests

**Comment by karajas** [comment]
From https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fdesktop~2Fcli~2F/build/20170109.02 , it looks like this has been resolved from an infrastructure standpoint.

**Comment by jiangzeng** [comment]
From build 20170109.02, most failures of this issue are not happening, but there are still some assembles throw this kind of issue, see example:
https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fdesktop~2Fcli~2F/build/20170109.02/workItem/System.Data.SqlClient.ManualTesting.Tests/details/fe84088c-3b91-46db-8c76-44f3151ae058

Log:
```
2017-01-09 15:35:05,464: INFO: proc(55): run_and_log_output: Output: Command(s):
2017-01-09 15:35:05,464: INFO: proc(55): run_and_log_output: Output: call xunit.console.exe System.Data.SqlClient.ManualTesting.Tests.dll  -noshadow  -xml testResults.xml -notrait Benchmark=true -notrait category=nonnet46tests -notrait category=requireselevation -notrait category=failing -notrait category=nonwindowstests
2017-01-09 15:35:05,871: INFO: proc(55): run_and_log_output: Output: xUnit.net Console Runner (64-bit .NET 4.0.30319.42000)
2017-01-09 15:35:06,668: INFO: proc(55): run_and_log_output: Output: System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
2017-01-09 15:35:06,684: INFO: proc(55): run_and_log_output: Output: Finished running tests.  End time=15:35:06.68, Exit code = 1
2017-01-09 15:35:06,684: INFO: proc(58): run_and_log_output: Exit Code: 1
```

**Comment by karajas** [comment]
As a part of https://github.com/dotnet/corefx/commit/c3f912f2ca14562826c37e9cb7a2d2153eac5a07#diff-20e6ae99f7084d10fb8f6fb1540aec65R8 , I noticed that some tests weren’t passing in the right NugetTargetMoniker. For net46 to run, a tests would need a version of NugetTargetMoniker of .NETStandard1.3 or lower, following the table listed here https://github.com/dotnet/corefx/blob/9130bb9fe75d7ed693a5ef3d53f4145cf8f62f44/Documentation/architecture/net-platform-standard.md#mapping-the-net-platform-standard-to-platforms. I saw that for Diagnostics.Debug it targets .NETStandard1.7 which may cause some issues. Currently the test build targets only net46; we may want to consider updating this to higher versions to test.

**Comment by tarekgh** [comment]
talked offline with @karajas and he is going to investigate more to understand why this is failing even when compiling against netstandard 1.7.

**Comment by tofutim** [comment]
Hi, I recently ran into

System.IO.FileLoadException : Could not load file or assembly 'System.Security.Cryptography.Primitives

when running NUnit 3 tests in TeamCity. Strangely, I see no such error in NCrunch running the same tests.

**Comment by dleeapho** [comment]
Binding redirects have changed, this should not be a problem now.
