### ISSUE TITLE
Index packages with only runtime-specific impls

### ISSUE THREAD

**Issue by ericstj** [dotnet/buildtools#1093]
https://github.com/dotnet/buildtools/commit/e6f32a54deeaee94063eb6d4164221ad1d66e363 fixed indexing so that it could handle packages without refs, but I missed the case where a package only had runtime-specific Impls.

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
