### ISSUE TITLE
SendToHelix task should print out raw response text if response is not JSON-Deserializable

### ISSUE THREAD

**Issue by MattGal** [dotnet/buildtools#1097]
In the case of receiving a response from POST'ing to the Helix API, the response may be HTML and not JSON.  IN this case, we should catch the exception and print the raw content of the stream we're attempting to deserialize.

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
