### ISSUE TITLE
Do we have to use “--configuration Linux” if want to build for Linux?

### ISSUE THREAD

**Issue by jianyunt** [dotnet/buildtools#1101]
We use dotnet build for our [OneGet](https://oneget.org) project for both coreclr and fullclr. Our code is C# based. 
Our goal is to use the donet coreclr build so that our binaries can be run on windows, Linux, Mac, etc.

However we observed that :

If we want to build for Linux, we have to pass in  --configuration Linux . The binaries generated then work well on Linux . For example,

dotnet -v build –framework netstandard1.6--configuration Linux

If we build without passing in Linux,

dotnet -v build –framework netstandard1.6

We have trouble to calling into some methods such as using powershel.Invoke(). 

Question:

1. Assuming we do not have build options for pre-compile process, is it true any app purely built on top up  of CoreCRL should be able to run other Platform like Linux, Mac ?

2. What sort of special things dotnet build do when a user passes in --configuration Linux?

**Comment by weshaggard** [comment]
This is the wrong repo for this request. I think http://github.com/dotnet/cli is the more appropriate repo.
