### ISSUE TITLE
Enable /m for our xplat builds.

### ISSUE THREAD

**Issue by weshaggard** [dotnet/buildtools#1103]
msbuild has enabled /m for x-plat so we should update our version of msbuild to start using it.
https://github.com/Microsoft/msbuild/issues/303

@markwilkie who would be a good person to give this work-item to?

**Comment by joperezr** [comment]
I'm not sure if I understood this correctly, but aren't we already doing this here: https://github.com/dotnet/corefx/blob/master/config.json#L527

**Comment by weshaggard** [comment]
Your right I miss remembered something here. Do you know if we are still using daniel's private packages for msbuild? If so we should at least move to the official msbuild package to get this update.

**Comment by weshaggard** [comment]
We are passing `/m` for our cross plat builds.
