### ISSUE TITLE
When bootstrapping buildtools, resume from last successful step

### ISSUE THREAD

**Issue by dagood** [dotnet/buildtools#1106]
Bootstrapping might be cancelled intentionally (ctrl-c) or fail during certain steps. When possible, we should be able to resume the bootstrapping process from where it stopped.

One clear cutoff, for example, is that bootstrapping should be able to avoid redownloading the CLI if the buildtools package init fails.

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
