### ISSUE TITLE
Consider supporting custom Azure ContainerName for helix runs

### ISSUE THREAD

**Issue by MattGal** [dotnet/buildtools#1108]
Previously, we allowed the user to specify their own value for ContainerName.  THis can still be achieved via override from external build command line, but it cannot be generated and provided as a property from Msbuild.

Line in question: 
https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.targets#L28

**Comment by dleeapho** [comment]
We are using GUIDs instead now.
