### ISSUE TITLE
Remove UseECMAKey hack for unix builds

### ISSUE THREAD

**Issue by weshaggard** [dotnet/buildtools#1110]
Remove hack for blocking ECMA key https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks/PackageFiles/Roslyn.Common.props#L28

After our last compiler update we got the public key signing support from https://github.com/dotnet/roslyn/issues/2444 so this hack is no longer needed.

**Comment by dleeapho** [comment]
No longer applicable.

**Comment by weshaggard** [comment]
As in we already cleaned this up in the corefx fork of the targets that we will merge into BuildTools.
