### ISSUE TITLE
Recent CLI doesn't work with init_tools.sh

### ISSUE THREAD

**Issue by janvorli** [dotnet/buildtools#1111]
While trying to help someone from the community to build coreclr on Linux with kernel version >= 4.6, which requires using recent CLI, I have discovered that init_tools.sh don't work when I modify the DotnetCLIVersion.txt to point to a recent version, e.g. 1.0.0-preview3-003786. There are two issues here. First one is a folder casing issue:
`/home/janvorli/git/coreclr/init-tools.sh: line 137: /home/janvorli/git/coreclr/packages/Microsoft.DotNet.BuildTools/1.0.26-prerelease-00809-01/lib/init-tools.sh: No such file or directory`
But `ls /home/janvorli/git/coreclr/packages` shows that the Microsoft.DotNet.BuildTools is named microsoft.dotnet.buildtools now.
So I've modified init_tools.sh by modifying this path to lowercase. But after that, the second issue occurs:

```
/home/janvorli/git/coreclr/Tools/Microsoft.Common.CurrentVersion.targets(1097,5): warning MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.0" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/home/janvorli/git/coreclr/src/mscorlib/System.Private.CoreLib.csproj]
/home/janvorli/git/coreclr/Tools/Microsoft.Common.CurrentVersion.targets(1097,5): warning MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.0" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/home/janvorli/git/coreclr/src/mscorlib/ref/mscorlib.csproj]
/home/janvorli/git/coreclr/Tools/FrameworkTargeting.targets(67,3): error MSB4019: The imported project "/home/janvorli/git/coreclr/Tools/Extensions/Microsoft/Portable/v4.5/Microsoft.Portable.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk. [/home/janvorli/git/coreclr/src/ToolBox/SOS/NETCore/SOS.NETCore.csproj]
/home/janvorli/git/coreclr/Tools/FrameworkTargeting.targets(67,3): error MSB4019: The imported project "/home/janvorli/git/coreclr/Tools/Extensions/Microsoft/Portable/v4.5/Microsoft.Portable.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk. [/home/janvorli/git/coreclr/src/mscorlib/facade/mscorlib.csproj]

Command execution failed with exit code 1.
ERROR: An error occured in /home/janvorli/git/coreclr/Tools/dotnetcli/dotnet /home/janvorli/git/coreclr/Tools/run 11. Check 11 logs under /home/janvorli/git/coreclr.
Failed to build managed components.
```

So there is no way to build CoreCLR on Linux with kernel >= 4.6. The CLI tarball of a version that works with the init_tools.sh contains coreclr with a bug causing the runtime to crash as soon as GC occurs, which usually does during the dotnet restore.
The issue is related to https://github.com/NuGet/Home/issues/2522.

**Comment by dagood** [comment]
The casing change in coreclr `init-tools.sh` is something that needs to change in coreclr, but the second problem looks like it can be solved with something like https://github.com/dagood/buildtools/commit/1798b24 to allow any package id casing.

**Comment by dagood** [comment]
CoreCLR official build `beta-24906-05` has succeeded using a CLI that has the Linux kernel 4.6.x fix--resolved.
