### ISSUE TITLE
Make a build-info file available that maintains previous builds' packages

### ISSUE THREAD

**Issue by dagood** [dotnet/buildtools#1117]
Right now `VersionsRepoUpdater` overwrites `Latest_Packages.txt` with the list of packages created during the current build. Instead, the `Latest_Packages.txt` should contain the latest versions of all packages ever published from that build, unless packages are manually removed. For example, a servicing release would only update the serviced packages in `Latest_Packages.txt` to their new versions.

There should also be a `Last_Build_Packages.txt` that's simply overwritten with the build's package list.

This matches the name "`Latest`" better, and would improve scenarios like https://github.com/dotnet/buildtools/pull/1112#discussion_r82700580 and https://github.com/dotnet/buildtools/pull/858.

We should consider using the [github tree API](https://developer.github.com/v3/git/trees/#create-a-tree) so these files can be updated in the same commit rather than two (or three, when `Latest.txt` is updated).

@chcosta @weshaggard

**Comment by weshaggard** [comment]
Sounds good. I do like the idea of having the separate "LastBuild" list as well.

**Comment by dagood** [comment]
This is done, and happens in corefx master.

**Comment by chcosta** [comment]
How can we get this working for CoreFx release/1.0.0 and release/1.1.0?

**Comment by dagood** [comment]
Getting this in 1.0.0 is what I mentioned here: https://github.com/dotnet/buildtools/pull/1118#issuecomment-253318066, but I don't think the needed changes are considered above the bar at the moment. /cc @markwilkie 

For 1.1.0, we'd need https://github.com/dotnet/buildtools/pull/1118 in the buildtools version that corefx/1.1.0 uses, but 1.1.0 uses VersionTools so in the CoreFX repo I believe it would just be a buildtools update.

**Comment by chcosta** [comment]
Based on conversations with a few people, I think that the bar has shifted slightly. Given that there is no urgency around releases at the moment, and that we could opportunistically get these types of changes in.
