### ISSUE TITLE
Debugging tests broken in VS

### ISSUE THREAD

**Issue by ellismg** [dotnet/buildtools#112]
a385cfb seems to have broken the ability to run Unit Tests inside VS.  The transformation for {XunitTraitOptions} doesn't seem to happen when loading the project inside VS, so the command line we pass when the test project is set as the startup project is incorrect and causes the test runner to exit with an error.

Do we need to do something specific here when running under VS?

**Comment by weshaggard** [comment]
I wonder if this was broken with change https://github.com/dotnet/corefx/commit/85bd8348750dc65e55d625a2e20552d64fb076bc#diff-aad6833a46296c5e45aba8de08674fa0. However at any case you are correct the replacement piece is broken in VS. It becomes somewhat tricky to do the computation of the traits outside of the targets but we could make the VS arguments ignore the traits all together.

**Comment by ellismg** [comment]
Very possible that it was broken before your refactoring, I haven't tried it in a few weeks.
