### ISSUE TITLE
Looking for documentation about the build tools

### ISSUE THREAD

**Issue by ghost** [dotnet/buildtools#1137]
It is not immediately accessible to me the entry points to our build tooling nor how to use them properly (without resulting in many cycles of guess and check to 'figure it out').

Is there some way we can get an enumeration of the test tooling, along with the intended 'use scenarios'?

**Comment by bryanar** [comment]
Proposed approach: an index at the front of the repository that has an enumeration of all of the tooling, and then for each additional 'tool' a mark down file that follows the 'layout' of the original man-pages (https://en.wikipedia.org/wiki/Man_page)

From that:

> All man pages follow a common layout that is optimized for presentation on a simple ASCII text display, possibly without any form of highlighting or font control. Sections present may include:

> **NAME**
> The name of the command or function, followed by a one-line description of what it does.
> **SYNOPSIS**
> In the case of a command, a formal description of how to run it and what command line options it takes. For program functions, a list of the parameters the function takes and which header file contains its definition.
> **DESCRIPTION**
> A textual description of the functioning of the command or function.
> **EXAMPLES**
> Some examples of common usage.
> **SEE ALSO**
> A list of related commands or functions.
> Other sections may be present, but these are not well standardized across man pages. Common examples include: OPTIONS, EXIT STATUS, ENVIRONMENT, BUGS, FILES, AUTHOR, REPORTING BUGS, HISTORY and COPYRIGHT.

@markwilkie @Chrisboh @MattGal

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
