### ISSUE TITLE
RestoreBuildTools has some race conditions

### ISSUE THREAD

**Issue by weshaggard** [dotnet/buildtools#114]
We should look for another solution that doesn't requiring an explicit Touch of nuget.exe and the buildtools library at the end of RestoreBuildTools target in dir.targets.

The reason it was added was to deal with the case where people didn't actually delete their packages directory but they got an updated dir.props file and in that case they could get into a loop where RestoreBuildTools always runs every time for every project and slows down the build.

**Comment by MichaelSimons** [comment]
Triage: not applicable currently.
