### ISSUE TITLE
Auto-PR generation might not wait for pushed commits to be available through API

### ISSUE THREAD

**Issue by dagood** [dotnet/buildtools#1140]
https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=477589 got this error:

> {"message":"Validation Failed","errors":[{"resource":"PullRequest","code":"custom","message":"No commits between dotnet:master and dotnet-bot:master-UpdateDependencies"}],"documentation_url":"https://developer.github.com/v3/pulls/#create-a-pull-request"}

Earlier I thought this was a race condition between auto-PR runs and merges, but the the linked build's case I think it's just because the PR creation call happens immediately after the push with no delay, but maybe GitHub needs some time for the pushed commits to be available.

To diagnose this, we should use the GitHub API to get the current commit on the branch between the push and PR creation. This might mask the issue by introducing a long enough delay to make the PR work, but we can start to see if the pushed commits are immediately available or if there really is a delay before the API can see them.

To fix this, we can retry the PR creation call a few times with a delay.

**Comment by dleeapho** [comment]
We haven't seen this in a while.
