### ISSUE TITLE
dot-net bot repo update PR's should include commit SHA's

### ISSUE THREAD

**Issue by danmoseley** [dotnet/buildtools#1141]
eg https://github.com/dotnet/corefx/pull/12721/files tells me   <CoreClrCurrentRef>28bce260e5ca4c279913dd523ae70b3f4adb1e19</CoreClrCurrentRef> but this is the SHA for dotnet/versions. 

What I want to know is what changes this will bring me, ie., what the SHA is in coreclr. Right now I have to go to myget and get the package with the stated version, crack it and look at the commit ID inside it. 

It would be simpler if the bot would just include this SHA in a comment in the XML file or similar.

@joperezr

**Comment by joperezr** [comment]
I'm not sure if this is possible though, as we would probably need to check this sha into dotnet/versions probably to get this working. @dagood  thoughts?

**Comment by dagood** [comment]
Correct, the auto-PR process currently has no better way to get this info because it relies on what's in dotnet/versions. Adding the build commit SHA to the versions repo is tracked in https://github.com/dotnet/buildtools/issues/986.

I'm on the fence about baking the SHA into source, though. Would it be enough for it to be listed in the PR description, or do you think you'll want quick access offline in a checked out repo?

**Comment by danmosemsft** [comment]
The PR description would be fine.

**Comment by dagood** [comment]
The commit hash is actually used during builds, so now I'm all for putting it in `dependencies.props`. Core-Setup "forwards" the CoreCLR and CoreFX commit hashes, and recently @BruceForstall asked me about the hashes wrt. some new CoreCLR automation. Once commit hash is available (https://github.com/dotnet/buildtools/issues/1853), it won't be hard to add an updater that can put it in `dependencies.props`.

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
