### ISSUE TITLE
TestCopyLocal item group does not get a tested assembly's PDB if Test and product assembly are in different OS Group

### ISSUE THREAD

**Issue by MattGal** [dotnet/buildtools#1144]
Repro: 
Build and compare the Runtests.cmd / sh files for
System.Security.SecureString (repros problem)
Microsoft.Csharp (Does not repro).

The difference here is that the runner script generated for the latter ends up with the PDB to test in the copy local list, so it gets copied when propping test files.  (This happens in publishtest.targets).

I spent some time investigating this but need to look at other things so am creating an issue.

@weshaggard @stephentoub

**Comment by stephentoub** [comment]
Note that this is preventing getting code coverage data on many of our libraries.

**Comment by stephentoub** [comment]
> Microsoft.Csharp (Does not repro)

This now does repro the problem.
