### ISSUE TITLE
Project setting handled inconsistently by Run tool

### ISSUE THREAD

**Issue by clayton-taylor** [dotnet/buildtools#1152]
**Observed Behavior**

It appears that the Project setting is intended to be utilized by the Run tool to dynamically construct the path to the tools which do not have a path specified in the config.json file or to be passed as a positional argument to tools which do. I've found that one will get different behavior depending on whether or not a value is defined for the alias/command in the config. Consider the following `config.json` file:

``` JSON
{
  "settings": {
    "Project": {
      "description": "Project where the commands are going to be applied.",
      "valueType": "passThrough",
      "values": [],
      "defaultValue": ""
    }
  },
  "commands": {
    "test-with-default": {
      "alias": {
        "alias-with-project": {
          "description": "An alias that defines the 'Project' setting",
          "settings": {
            "Project": "path/to/project1"
          }
        },
        "alias-without-project": {
          "description": "An alias that does not define the 'Project' setting",
          "settings": {}
        }
      },
      "defaultValues": {
        "toolName": "extension-tool",
        "Project": "path/to/project2",
        "settings": {}
      }
    },
    "test-without-default": {
      "alias": {
        "alias-with-project": {
          "description": "An alias that defines the 'Project' setting",
          "settings": {
            "Project": "path/to/project3"
          }
        },
        "alias-without-project": {
          "description": "An alias that does not define the 'Project' setting",
          "settings": {}
        }
      },
      "defaultValues": {
        "toolName": "extension-tool",
        "settings": {}
      }
    }
  },
  "tools": {
    "extension-tool": {
      "osSpecific": {
        "windows": {
          "filesExtension": "cmd"
        },
        "unix":{
          "filesExtension": "sh"
        }
      },
      "valueTypes": {}
    }
  }
}
```

Running all of the different permutations of commands/aliases with the setting being defined on the command-line or not, I see the following:

![selection_002](https://cloud.githubusercontent.com/assets/22800738/19614361/64d63908-97a9-11e6-8cd6-56e1a32470f3.png)

One will also see some inconsistencies when using tool definitions that use the path property in that the Project value will sometimes be passed as a positional argument and sometimes won't.

**Expected Behavior**
I would expect that defining a value for Project would yield the same behavior regardless of whether it was done at the command level or at the alias level. It would seem to me that the root of the problem is that in the config Project is not included in the settings dictionary for a command while it is included for an alias. I would personally find one of the following solutions to yield more intuitive behavior:
1. Push Project down into the settings dictionary for commands and ensure that lookup rules for its value consider a definition made on the command-line.
2. Pull Project up out of the settings dictionary for aliases and perhaps rename it if possible to indicate that it is not being treated the same as the setting of the same name.

In either case the rule that the value of Project cannot be redefined on the command-line if already defined in the config file should either be enforced for both or neither.

**Comment by dleeapho** [comment]
Unfortunately, there are many inconsistencies in run.exe and the config, many of which are much worse than this issue.
