### ISSUE TITLE
Make NuGet dependency auto-update case-insensitive

### ISSUE THREAD

**Issue by dagood** [dotnet/buildtools#1153]
Currently package ids from dotnet/versions have to match the ones in a project.json exactly. NuGet itself is case-insensitive, so Package update should be too.

Issue was spotted in auto-PR: https://github.com/dotnet/corefx/pull/12958#issuecomment-255822892

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
