### ISSUE TITLE
In package's init-tools.sh, ensure portable targets and MicroBuild package copy correctly

### ISSUE THREAD

**Issue by dagood** [dotnet/buildtools#1162]
When init-tools copies `Microsoft.Portable.Targets` and `MicroBuild.Core` files to the tools directory, https://github.com/dotnet/buildtools/pull/1114 adds case insensitivity to the package directory layout using `find`. Using `find` rather than `cp` removes the implicit check to make sure the files that need to be copied exist. With `find`, if it doesn't find them init-tools will silently continue, and if there are multiple packages with the same insensitive name and version, `find` will attempt to copy them all.

Typically if `dotnet restore` succeeds, the expected files will be there, but it is good to have a specific check to catch any errors rather than finding out about them downstream.

**Comment by dleeapho** [comment]
No longer using find.
