### ISSUE TITLE
boostrap script does not have an architecture option

### ISSUE THREAD

**Issue by livarcocc** [dotnet/buildtools#1165]
The bootstrap script is always installing x64 CLI, which causes the CLI's x86 builds itself to be x64, because we check the Inptr side to determine if we should build for x86 or x64.

Since we are always downloading x64 CLI, we are always building for x64.

Please add a parameter to allow specifying the architecture.

Meanwhile, I have reverted this change in the CLI as it broke our windows x86 build: https://github.com/dotnet/cli/commit/007cfc1f9bdd290b0bc2f614c27cdddae90e438a.

**Comment by livarcocc** [comment]
cc @piotrpMSFT

**Comment by crummel** [comment]
I'm looking at this now.

**Comment by livarcocc** [comment]
Let me know when this gets merged. I want to go ahead and fix the CLI immediately.
