### ISSUE TITLE
Need to wrap or remove Console Color calls in Xunit.Console.NetCore

### ISSUE THREAD

**Issue by MattGal** [dotnet/buildtools#1172]
Lines like this used to not throw, even if they were no-ops internally:
https://github.com/dotnet/buildtools/blob/master/src/xunit.console.netcore/Program.cs#L23

I'm not sure when this changed but at some point recently this started failing for Xunit.Console.Netcore when targeting NetCore50 ILC scenarios.

We need to put try/catch wrappers around these calls and/or just not set the console color in XUnit.COnsole.NetCore.

@weshaggard

**Comment by danmosemsft** [comment]
@MattGal if setting or getting the color on Unix throws that is a bug please open one in corefx. It is supposed to be ignored IIRC

**Comment by weshaggard** [comment]
@danmosemsft this isn't an issue on unix it is an issue on UWP/netcore50. I believe it was introduced by @SedarG PR https://github.com/dotnet/corefx/pull/12984. 

@SedarG when you removed the netcore50 build you throw away @ianhays changes https://github.com/dotnet/corefx/commit/6b0b2c26d16fcdd8347cbc411b859e108247b8d7 which added fuller support for System.Console.

**Comment by dleeapho** [comment]
No longer applicable.
