### ISSUE TITLE
BuildTools should use props file for signing plugin

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/buildtools#1186]
From @ericstj 

```
We only import targets and not props files, whereas had we installed the microbuild package directly we’d get both.

Make a fix to buildtools to pick up props as well, update that in all release branches.
```

When release branches (both LTS and 1.1.0) are updated, please undo the change that forces the signing version to be 1.0.268.

**Comment by markwilkie** [comment]
From Eric St John,
===============
We have two options to fix this:
1.	Just change the build definitions to lock in the signing plugin on a version that works with the buildtools in release.
2.	Make a fix to buildtools to pick up props as well, update that in all release branches.

I think #1 is the right thing to do in the release branches.

================

I think I found the problem.
 
There was a breaking change in the plugin. 
WCF is using MicroBuild.Plugins.Signing.1.0.279
CoreFx is using MicroBuild.Plugins.Signing.1.0.268
 
The difference between these two?  The 279 version adds a property MicroBuild_SigningEnabled to MicroBuild.Plugins.Signing.props.
 
As far as I can tell the only thing we import is 
  
 
This means we’ll never import that props file which sets the property to enable the signing task.
 
I think the simple fix here is to change the plugin version your’re using.  
 
I think someone from infrastructure side needs to see what needs to update in buidltools to pick up the new microbuild plugins.  I believe that’d be having buidltools import the MicroBuild.core.props in https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks/PackageFiles/Build.Common.props like we do for the targets here:
https://github.com/dotnet/buildtools/blob/b382611268cec867010948b71dbedc466f36ddf7/src/Microsoft.DotNet.Build.Tasks/PackageFiles/Build.Common.targets#L246
 
Eric

**Comment by ericstj** [comment]
Also undo the change in DotNetCore-BuildTools-Trusted, I had to force 1.0.268 here as well.
