### ISSUE TITLE
Changing .cliversion in consuming repo does not cause bootstrapper to re-run

### ISSUE THREAD

**Issue by crummel** [dotnet/buildtools#1192]
Updating .cliversion in a consuming repo using bootstrapper should re-run bootstrapper, download the new CLI, and re-symlink the current CLI version.  Currently this does not happen because the bootstrap.complete file still exists and CLI is not one of the checked version numbers.

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
