### ISSUE TITLE
Stop using the raw.githubusercontent.com endpoint, use GitHub API instead

### ISSUE THREAD

**Issue by dagood** [dotnet/buildtools#1196]
This will prevent us from hitting errors when trying to access empty build-info files using their raw urls. We currently work around by not using empty files: https://github.com/dotnet/buildtools/pull/1174.

GitHub doesn't intend for us to use the raw endpoint in this way, recommending that we don't use the raw API, instead using the documented GitHub API.

**Comment by dagood** [comment]
I looked into the GitHub API and discovered the recommended solution simply directs to the exact same url at raw.githubusercontent.com, so it the same problem repros. I'm following up some more with GitHub support.

**Comment by dagood** [comment]
I didn't get a response from support that it was fixed, but I tried reproing the issue and it doesn't seem to happen. It might still be a good idea to stop assembling raw api URLs manually and use the GH api to retrieve them, just for flexibility. (Unfortunately with my current understanding that would double the number of API calls we need to make for this part of the build.)

@MichaelSimons Have you been seeing 503 errors in the docker nightly auto-PR builds, or is the issue recently only that the files are blank?

**Comment by MichaelSimons** [comment]
I am seeing [blank version files](https://github.com/dotnet/versions/blob/master/build-info/dotnet/cli/rel/1.0.0/Latest_Packages.txt) and the files are not getting updated with the latest builds.  I haven't gone searching through the build logs to see if the builds are seeing the 503 errors.  Tracing this down is a real pain :)

**Comment by dagood** [comment]
Ok, thanks. Briefly looking at the general executor for docker nightly, I don't see build failures, and I'm pretty sure the 503s caused hard build fails. This issue would only fix those, so at the moment it seems the fix for the blank file you linked is just CLI work, nothing in BuildTools.

**Comment by MichaelSimons** [comment]
@naamunds logged this [bug](https://github.com/dotnet/cli/issues/4399#issuecomment-264997737) for the CLI issue.

**Comment by MichaelSimons** [comment]
GitHub issue but we can avoid hitting this by avoiding blank version files.  CLI was the main place that was producing these and the issue was resolved.  Closing.
