### ISSUE TITLE
Not having PDBs should be a hard/loud error on coverage builds

### ISSUE THREAD

**Issue by crummel** [dotnet/buildtools#1207]
See https://github.com/dotnet/buildtools/issues/1144 and https://github.com/dotnet/corefx/issues/12927, which were eventually resolved by https://github.com/dotnet/buildtools/issues/1205.  This might have been easier to track down if we fail on not having PDBs instead of just getting reduced coverage, which might not be as obvious.

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
