### ISSUE TITLE
BuildTools bootstrapping script is failing to install dotnet CLI

### ISSUE THREAD

**Issue by MattGal** [dotnet/buildtools#1208]
Investigating now.

D:\GIT\buildtools>build.cmd
D:\GIT\buildtools\Tools\dotnet-install.ps1 -Version 1.0.0-preview3-003223 -InstallDir D:\GIT\buildtools\Tools\dotnetcli -Architecture "<auto>"
dotnet-install: Downloading https://dotnetcli.azureedge.net/dotnet/Sdk/1.0.0-preview3-003223/dotnet-dev-win-x64.1.0.0-preview3-003223.zip
Failed to download https://dotnetcli.azureedge.net/dotnet/Sdk/1.0.0-preview3-003223/dotnet-dev-win-x64.1.0.0-preview3-003223.zip.
At D:\GIT\buildtools\Tools\dotnet-install.ps1:157 char:13
+             throw $ErrorMsg
+             ~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Failed to downl...ew3-003223.zip.:String) [], RuntimeException
    + FullyQualifiedErrorId : Failed to download https://dotnetcli.azureedge.net/dotnet/Sdk/1.0.0-preview3-003223/dotnet-dev-win-x64.1.0.0-preview3-003223.zip.

**Comment by weshaggard** [comment]
I was hitting this as well. I'm not sure if it was a timeout or what it was.

**Comment by MattGal** [comment]
I think I have a fix: https://github.com/dotnet/cli/pull/4659.

They always use the default timeout which assumes they can get everything in < 100s.  Today, only about 1/20 downloads of that zip is that fast on my local PC.

**Comment by weshaggard** [comment]
Awesome thanks @MattGal.

**Comment by MichaelSimons** [comment]
CLI script issue was addressed.
