### ISSUE TITLE
Remove OpenSourceSign from Microsoft.DotNet.Build.Tasks

### ISSUE THREAD

**Issue by mellinoe** [dotnet/buildtools#1221]
Ported from https://github.com/dotnet/corefx/issues/6759 (cc @tmat)

> Csc now supports OSS signing via /publicsign switch. The build task is not needed anymore and can be removed and CoreFX build simplified.

https://github.com/dotnet/buildtools/blob/e7768f0b40786251c787daaac43533f06fee8b26/src/Microsoft.DotNet.Build.Tasks/PackageFiles/sign.targets#L9

https://github.com/dotnet/buildtools/blob/78260239e4db68ad5c2df774a27d5f9a54fd92e5/src/Microsoft.DotNet.Build.Tasks/OpenSourceSign.cs

**Comment by weshaggard** [comment]
Yes please

**Comment by weshaggard** [comment]
I was going to switch to doing this but there is one issue with switching to let the compiler do this work for us. Namely some projects have assembly rewriting that they do after compile (i.e. GenFacades, ILLinker, etc) and for those projects they will not be correctly signed after rewriting if we do it during the compile phase. I didn't fully verify that we don't already have this issue but I wanted to call it out for anyone that looks at doing this.

**Comment by weshaggard** [comment]
Another thought here if we cannot easily remove the rewriting tools (which I suspect we cannot) then we can just augment them to round-trip the open/public signing bit in the binary (assuming it isn't already, I've not verified).

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
