### ISSUE TITLE
traversals targets don't correctly capture errors when serialized

### ISSUE THREAD

**Issue by weshaggard** [dotnet/buildtools#1224]
https://github.com/dotnet/corefx/blob/master/dir.traversal.targets

When SerializeProjects=true we batch over the projects at https://github.com/dotnet/corefx/blob/master/dir.traversal.targets#L122 which in turns drops any errors and only takes the task error code of the last project built. 

Instead of doing this batching we should consider other options like BuildInParallel=false to see if that gets us the serialized behavior we want as well as correctly captures the failures while allowing all projects to build.

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
