### ISSUE TITLE
Bootstrap process downloads and executes scripts from GitHub

### ISSUE THREAD

**Issue by mellinoe** [dotnet/buildtools#1225]
There's a few problems that I see here:

https://github.com/dotnet/buildtools/blob/master/run.ps1#L14
https://github.com/dotnet/buildtools/blob/master/bootstrap/bootstrap.ps1#L42

1. We are not pinned to specific versions of these files. This means that breaking changes at any point in the future can cause breaks in our historic commits. Realistically this means that we can never safely change these scripts in the future without testing every single commit that uses them.
2. We're implicitly trusting the contents of the files delivered by GitHub here. I think there are some security implications around downloading and executing raw scripts like this.
3. (more subjective) We don't really need this dependency on GitHub here. It would be nice if the repo was still buildable without GitHub. I realize we have many other dependencies similar to this, but at least we have more control over others, or have alternatives when they go down.

Right now, the master branch is not buildable because of this change in another repo: https://github.com/dotnet/cli/issues/4715

**Comment by weshaggard** [comment]
cc @crummel @dleeapho

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
