### ISSUE TITLE
run tool should use common logic for detecting RID

### ISSUE THREAD

**Issue by weshaggard** [dotnet/buildtools#1229]
The run tool should not use its own custom logic for detecting RID. https://github.com/dotnet/buildtools/blob/master/src/Run/SettingValueProvider.cs#L97

It should use similar logic like https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks/GetTargetMachineInfo.cs#L52

cc @mellinoe

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
