### ISSUE TITLE
Run tool "Setting" values default behavior can be confusing

### ISSUE THREAD

**Issue by MattGal** [dotnet/buildtools#1230]
I noted this while adding whatif / dry-run support to Run.exe.  Specifically, for boolean setting flags the only way to get them to work properly is to set the default value to string.empty, as any other value prevents the user from providing a value at all.  This leads to code like this:

                    Values = new List<string>() { "true", "false" },
                    ValueType = RunToolSettingValueTypeReservedKeyword,
                    Description = "Run tool specific setting.  Set to 'true' to only display commands chosen and not execute them",
                    // Currently, providing a default value for this setting will prevent it being overwritten by the command line.
                    // While it is not intuitive, the code as-is supports "<some command> -whatif" without requiring a boolean argument.
                    DefaultValue = string.Empty
                };
                Settings.Add(WhatIfReservedKeyword, whatIfSetting);

... which makes folks think they will have to provide values like -whatif=true to use it.    This is lower priority but it's definitely the sort of thing you don't figure out until stepping through in a debugger (or noticing the comments I added).

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
