### ISSUE TITLE
Package restore does not trigger when project.json's are in subfolders

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/buildtools#1231]
Example repro:
1) edit `corefx\src\System.Security.Cryptography.X509Certificates\src\win\project.json` to put garbage in it. 
2) `msbuild corefx\src\System.Security.Cryptography.X509Certificates\src\System.Security.Cryptography.X509Certificates.builds`

Result: no error.

Run it manually with `..\..\..\Tools\dotnetcli\dotnet.exe restore . --packages ..\..\..\packages` and you get a syntax error.

The same applies with adding a reference, the syntax error is just to illustrate that restore is not happening.

@joperezr fyi, this is what we were seeing.

**Comment by joperezr** [comment]
this is expected since you are building the `.builds` file. Those will never trigger package restore unless you force it to do so. Did you try changing step 2 to instead build the `.csproj`? If you get a repro in that case, then it is a bug as I would expect building the .csproj to trigger restore.

**Comment by weshaggard** [comment]
@joperezr is correct. Also this will soon not be an issue because we will be eliminating all the project.json files for the projects.
