### ISSUE TITLE
Incremental build of test projects is broken from command-line

### ISSUE THREAD

**Issue by naamunds** [dotnet/buildtools#1240]
When building a test project from the command-line, the project is always re-compiled even when no changes have been made.  This also causes tests to always be re-run when using /t:BuildAndTest.

The CoreCompile target is built because disabledAnalyzers.config is now in its list of Inputs:
>  Input file "C:\Repos\corefx\bin/obj/Windows_NT.AnyCPU.Debug/System.Security.Cryptography.Pkcs.Tests//disabledAnalyzers.config" is newer than output file "C:\Repos\corefx\bin/obj/Windows_NT.AnyCPU.Debug/System.Security.Cryptography.Pkcs.Tests/System.Security.Cryptography.Pkcs.Tests.pdb".

This change appears to be due to `@(AdditionalFiles)` being added to the Inputs of CoreCompile in Microsoft.CSharp.Core.targets from Roslyn; disabledAnalyzers.config is added to AdditionalFiles at https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.CodeAnalysis/PackageFiles/codeAnalysis.targets#L56.  This change is in buildtools version 1.0.27-prerelease-01029-01 but not in 1.0.27-prerelease-01010-02.

/cc @weshaggard @ericstj @dleeapho @AlexGhiondea

**Comment by naamunds** [comment]
The disabledAnalyzers.config file is newer than the .pdb file because it is written with every build.  One possible fix would be to only write to disabledAnalyzers.config if it's actually changed.

**Comment by AlexGhiondea** [comment]
@naamunds yes -- I think we should condition the write so that we only do it if the contents have changed.

**Comment by weshaggard** [comment]
You need to be careful about race conditions when you do that. I think we should try and figure out how to correctly make the target that is writing the file incremental. Either give it proper inputs/outputs.

**Comment by weshaggard** [comment]
Addressed by https://github.com/dotnet/buildtools/pull/1584/. Thanks @danmosemsft
