### ISSUE TITLE
Eliminate separate CopySupplementalTestData target

### ISSUE THREAD

**Issue by naamunds** [dotnet/buildtools#1245]
publishtest.targets currently contains a `CopySupplementalTestData` target for copying the `SupplementalTestData` items to the test directory.  This copy is done in a separate target because it cannot use hard links, whereas the other files being copied to the test directory use hard links by default.  This is because the supplemental test data is shared between multiple projects, so using hard links would result in race conditions between the archiving and copying of different links of the same files.

Having this separate copy adds complexity to the test targets.  It may not be necessary if the supplemental test data were included in Content and the output directory were archived when preparing to run in Helix instead of the test directory being archived, because Content is already copied to the output directory without using hard links.

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
