### ISSUE TITLE
CleanupVSTSAgent task does not handle MAX_PATH+ directories

### ISSUE THREAD

**Issue by MattGal** [dotnet/buildtools#1247]
https://github.com/dotnet/buildtools/blob/72f7b5203c81b0cfb63d3fdc60b3351462d1a809/src/Microsoft.DotNet.Build.Tasks/CleanupVSTSAgent.cs#L103 

Constructing a DirectoryInfo object on a path that hits MAX_PATH (260 chars) blows up. 

You could either handle the path too long exception and log the exact path that hit the issue, or check the length before creating it.  Detecting that the task is running on Windows and pre-pending the long path prefix might just fix everything too.  Printing ANY path that results in an exceptional state seems like a good idea, too.

Either way, after fixing this it's important to test the deleting code on > MAX_PATH paths because this is a likely source of the existing cleanup troubles.

@joperezr  and @weshaggard  I wonder if this started / got worse with the new Unique BuildConfiguration Paths?

@chcosta

**Comment by MattGal** [comment]
@chcosta  isn't this one fixed now?

**Comment by chcosta** [comment]
Yes, fixed with https://github.com/dotnet/buildtools/commit/5f0fac00e68b89b017d7d6fbabcd23a508d8a5d9
