### ISSUE TITLE
BuildTools tests

### ISSUE THREAD

**Issue by eatdrinksleepcode** [dotnet/buildtools#125]
There are no tests in the BuildTools repo. The Tasks project could use tests both for the custom tasks themselves, as well as the targets files (e.g. importing all of the targets into a master build file and at least ensuring that they parse correctly). I haven't looked enough at the other projects in the repo to know what kinds of tests would be appropriate, but they do contain non-trivial logic that could be tested.

**Comment by weshaggard** [comment]
Yes this is something that I think needs to be done as well it just hasn't come to the top of the list yet. Thanks for filing the issue however. My basic thoughts here are that we should have a template repo layout that consumes the build tools and does some basic validation.

**Comment by eatdrinksleepcode** [comment]
I agree, a template repo would be useful both for testing and for demonstrating the expected usage of the build tools to consuming projects. I would be interested in helping out with that.

**Comment by weshaggard** [comment]
@eatdrinksleepcode That would be awesome if you wanted to put that together. We will put you down as working on that.

**Comment by ViktorHofer** [comment]
Closing as the buildtools repository has been archived and replace by https://github.com/dotnet/arcade.
