### ISSUE TITLE
WriteVisualBasicDefineResponseFile does not overwrite existing file

### ISSUE THREAD

**Issue by bbowyersmyth** [dotnet/buildtools#1253]
WriteVisualBasicDefineResponseFile uses File.OpenWrite to update the response file. This means that when the file already exists and the text being written is smaller than the existing text it will do a partial file update. Leading to a corrupted string.

https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks/WriteVisualBasicDefineResponseFile.cs

@terrajobst accurately sums this up https://twitter.com/terrajobst/status/761048968830734336

**Comment by dagood** [comment]
Fixed by https://github.com/dotnet/buildtools/pull/1342, changed to `File.Open`.
