### ISSUE TITLE
Microsoft.VisualBasic resource inclusion

### ISSUE THREAD

**Issue by tarekgh** [dotnet/buildtools#1256]
@bbowyersmyth commented on [Wed Dec 07 2016](https://github.com/dotnet/corefx/issues/14299)

Just doing a `msbuild /t:clean;build` from the src\Microsoft.VisualBasic folder and the compile constant DEBUGRESOURCES doesn't get written to the bin\obj\AnyOS.AnyCPU.Debug\Microsoft.VisualBasic\defines.rsp file.

This shows as the bin\obj\AnyOS.AnyCPU.Debug\Microsoft.VisualBasic\SR.vb file being compiled without fallbacks in debug mode.

---

@danmosemsft commented on [Thu Dec 08 2016](https://github.com/dotnet/corefx/issues/14299#issuecomment-265809765)

Sounds like build issue

---

@karelz commented on [Thu Dec 08 2016](https://github.com/dotnet/corefx/issues/14299#issuecomment-265823727)

Then it's Infra (@danmosemsft only one area label please ;-))

---

@tarekgh commented on [Thu Dec 08 2016](https://github.com/dotnet/corefx/issues/14299#issuecomment-265836118)

just a comment for who is going to look at this issue:

looks we are passing the DEBUGRESOURCES defined constant as expected to 

```
DefineConstants = ,DEBUG,TRACE,LATEBINDING=True;DEBUGRESOURCES;SIGNED

```

but it looks when creating the defines.rsp used with vbc.exe, it doesn't use the property DefineConstants and instead it uses FinalDefineConstants

```
FinalDefineConstants = CONFIG="Debug",_MyType="Empty",PLATFORM="AnyCPU",,DEBUG,TRACE,LATEBINDING=True
```

the fix could be next to the following line in resources.targets
```
    <DefineConstants Condition="'$(ConfigurationGroup)' == 'Debug'">$(DefineConstants);DEBUGRESOURCES</DefineConstants>

```

add another line:

```
    <FinalDefineConstants Condition="'$(ConfigurationGroup)' == 'Debug'">$(FinalDefineConstants),DEBUGRESOURCES</FinalDefineConstants>

```

---

@bbowyersmyth commented on [Thu Dec 08 2016](https://github.com/dotnet/corefx/issues/14299#issuecomment-265868842)

@tarekgh Also I think DEBUGRESOURCES and SIGNED need to be comma delimited for VB. Not sure if that plays into this at all.

---

@tarekgh commented on [Thu Dec 08 2016](https://github.com/dotnet/corefx/issues/14299#issuecomment-265875381)

@bbowyersmyth that is a good point. looks this is working with C# but not VB. do you want give it a try? I mean in your local corefx\Tools\resources.targets fix the semicolon to comma and try to build again Microsoft.VisualBasic. if this fix it, you can submit PR in buildtools repo. Thanks.

---

@karelz commented on [Thu Dec 08 2016](https://github.com/dotnet/corefx/issues/14299#issuecomment-265897934)

BTW: If we confirm it is in buildtools, we should move it there (unless we do the fix right away).

**Comment by bbowyersmyth** [comment]
@tarekgh The semicolon change didn't fix the issue for me, but it still may need to be changed as part of a larger fix.

**Comment by tarekgh** [comment]
right. doing my original proposed fix should fix the issue. I mean adding the following line to resources.targets

```
  <FinalDefineConstants Condition="'$(ConfigurationGroup)' == 'Debug'">$(FinalDefineConstants),DEBUGRESOURCES</FinalDefineConstants>
```

**Comment by weshaggard** [comment]
@bbowyersmyth is this still an issue for you?

**Comment by dleeapho** [comment]
Feel free to reopen @bbowyersmyth if this is still a problem.
