### ISSUE TITLE
Auto-update pull request flow doesn't handle partial matches for PR head branch name

### ISSUE THREAD

**Issue by dagood** [dotnet/buildtools#1259]
When finding an existing PR for an upgrade, the GitHub search API can only perform searches for partial matches. For example, searching for `master-UpdateDependencies-rel-1.0.0-preview2` will find:

```
master-UpdateDependencies-rel-1.0.0-preview2
master-UpdateDependencies-rel-1.0.0-preview2.1
```

The PR search process needs to be improved to pick the exact match.

The PR search API doesn't return the base/head branches for each result, so using that API would require an additional API call per found PR.

We should use the [`GET /repos/:owner/:repo/pulls`](https://developer.github.com/v3/pulls/#list-pull-requests) API, which lets us filter on an exact branch. For example: https://api.github.com/repos/dotnet/corefx/pulls?head=dotnet-bot:master-UpdateDependencies&state=open

@MichaelSimons ran into this with Docker repo auto-update.

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
