### ISSUE TITLE
PullRequestCreator does not work correctly with branch names that are a subset of existing branch names

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/buildtools#1260]
The dotnet-docker-nightly repo utilizes the PullRequestCreator to generate PRs when new CLI builds happen.  

https://github.com/dotnet/dotnet-docker-nightly/blob/master/update-dependencies/Program.cs#L88

Currently this code gets invoked for multiple CLI branches, specifically preview2 and preview2-1.  If a PR exists for preview2-1 and the code runs for preview2, the PullRequestCreator will incorrectly update the existing preview2-1 PR.  An example of this is - https://github.com/dotnet/dotnet-docker-nightly/pull/138.  

The underlying issues appears to be related to the [SearchPullRequestsAsync](https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.VersionTools/Automation/GitHubApi/GitHubClient.cs#L166) method.  The GitHub query api it utilizes doesn't support exact matches therefore the query finds the PRs for the branch `master-UpdateDependencies-rel-1.0.0-preview2` as well as `master-UpdateDependencies-rel-1.0.0-preview2.1`.  The logic simply picks the first item returned.

**Comment by dagood** [comment]
This is more info about the scenario for https://github.com/dotnet/buildtools/issues/1259

**Comment by MichaelSimons** [comment]
Closing as this is a dup of https://github.com/dotnet/buildtools/issues/1259.
