### ISSUE TITLE
Eliminate duplication in GenerateTestExecutionScripts.cs

### ISSUE THREAD

**Issue by naamunds** [dotnet/buildtools#1261]
There is a significant amount of duplication between `WriteShExecutionScript` and `WriteCmdExecutionScript` that should be cleaned up in https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks/GenerateTestExecutionScripts.cs.

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
