### ISSUE TITLE
Repo API should allow for specifying nuget cache location

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/buildtools#1268]
So the cache can be shared when doing multi-repo builds.

**Comment by ellismg** [comment]
@dleeapho, this is probably something we'll want for the source build effort in order to not have to duplicate stuff across repositories.  Do we want to track items for the repo API here or in core-eng?

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
