### ISSUE TITLE
Running tests should copy every project's PDB to the test dir

### ISSUE THREAD

**Issue by naamunds** [dotnet/buildtools#1271]
Having symbols files in the test directory is useful for debugging tests and for generating complete code coverage reports.  Currently, only running tests with `p:TestWithLocalLibraries=true` copies every project's PDB to the test dir.

When running tests with the default properties, the only PDBs which are copied to the test dir are that of the test project and the projects to which the test project has a ProjectReference.  When running tests with `/p:BuildTestsAgainstPackages`, only the test project's PDB is copied to the test dir.  In both of these cases, PDBs for the assemblies from packages should be copied to the test directory.

/cc @karajas @danmosemsft @weshaggard

**Comment by danmosemsft** [comment]
@joperezr is this falling out of the build from source work already

**Comment by joperezr** [comment]
> is this falling out of the build from source work already

this will be includded as part of the dev/eng work, since now we will move to a model where there is only one test runtime folder. Today(in dev/eng) we are only copying the dlls in there, but I believe we do have plans to copy the PDBs in as well.

**Comment by MichaelSimons** [comment]
Not applicable anymore after engineering changes.  No longer building from package references.
