### ISSUE TITLE
Packaging doesn't gracefully handle TargetingPack/Framework-packages

### ISSUE THREAD

**Issue by ericstj** [dotnet/buildtools#1273]
I ran into the following issues when building the combined packages for NETCoreApp.

1. To calculate the identity of the package we were trying to resolve all files.  
 - When we're building an identity package, we don't want to try to resolve the platform specific files for other platforms.
 - This was done to attempt to list the lowest NETStandard version supported by those files but we don't care about this for these TargetingPack/Framework packages.

2. In DetermineRuntimeDependencies we depend on AssignPkgProjPackageDependenciesTargetFramework which depends on GetFiles.  Causing the same problem as issue 1 above.
- This was done to 

3. We call DetermineRuntimeDependencies on all references in the lineup package but should only call it on pkgproj references.

The solution for 1 & 2 is to refactor these to depend on harvesting, which is disabled for these projects.  The solution for 3 is straightforward: just use the pkgproj references already split.

**Comment by ericstj** [comment]
After updating to the latest buildtools I'm also hitting an issue with package reports.

We should make sure we can disable package reports here since we won't be producing packages on a single machine with the full file closure.

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
