### ISSUE TITLE
Add property for specifying XUnit method/class to test

### ISSUE THREAD

**Issue by naamunds** [dotnet/buildtools#1275]
To specify a method or class to run when running tests for a project using the BuildTools `Test` target, one needs to specify `"/p:XunitOptions=-method <method_name>"` or `"/p:XunitOptions=-class <class_name>"`.  As mentioned in https://github.com/dotnet/buildtools/pull/1272#discussion_r93084987, this is unintuitive.

In addition, specifying it using `XunitOptions` overwrites some of the options used by the `Test` target code, most notably `-xml $(XunitResultsFileName)`, meaning that no XML results file is produced when running a single method or class in this way.

Using explicit properties such as `XunitMethodName` and `XunitClassName` would make the usage clearer and solve the overwrite issue.

**Comment by safern** [comment]
Fixed in: #1518
