### ISSUE TITLE
Don't rely on repo's setting BuildToolsTargets45

### ISSUE THREAD

**Issue by ericstj** [dotnet/buildtools#1284]
Currently BuildTools decides which version of its task dll (portable/core vs desktop) to use based on the `BuildToolsTargets45` property.  It relies on the repo to "know" to set this whenever it is running on desktop.

We shouldn't do that.  We can detect when we're running on desktop with the MSBuildRuntimeType property.  When that is set and the value is `core` we are running on core.  If it is not set or the has a different value we're running on desktop (or something else like mono) and using the desktop task dlls is correct.

https://github.com/dotnet/buildtools/blob/3fda2e524d790aad64732d86696d45ece2453cfd/src/Microsoft.DotNet.Build.Tasks/PackageFiles/Build.Common.props#L49

**Comment by ericstj** [comment]
So I started hacking through a change and needed to change the following:
1. Condition on BuildToolsTaskDir in Build.Common.props.
2. Condition on Import Project="$(RoslynPropsFile)" in corefx dir.props
3. OverrideToolHost in Build.Common.props to handle windows w/ dotnet.exe
4. CodeAnalyzerDir in codeAnalysis.targets to be conditioned on MSBuildRuntimeType.

Are there more?

**Comment by AlfredoMS** [comment]
:+1: this would be nice

**Comment by weshaggard** [comment]
I wasn't aware of MSBuildRuntimeType, is it new?

**Comment by ericstj** [comment]
I noticed it when diffing diag logs between Core and desktop.  Looks to me like its been there for a while.  https://github.com/Microsoft/msbuild/commit/fd493e35b1b3253167695ff11f5c22ed5830e9b3
/cc @dsplaisted

**Comment by weshaggard** [comment]
This is done with the merge of corefx changes into BuildTools 2.0
