### ISSUE TITLE
For auto-upgrade commit push, print error logs

### ISSUE THREAD

**Issue by dagood** [dotnet/buildtools#1291]
Currently logs are intentionally not printed because they may contain secrets: [PullRequestCreator.cs#L175-L180](https://github.com/dotnet/buildtools/blob/ed02920c236b7b1b653c72bb828cb4d68095894d/src/Microsoft.DotNet.VersionTools/Automation/PullRequestCreator.cs#L175-L180). In most cases the secrets will automatically be hidden by VSTS, so we should allow push logs to be hidden via the API (for CLI's use case) and default to printing the logs.

At this point in the build, most errors would *typically* have already broken the auto-PR process, but showing logs for this step would help diagnose stranger issues.

**Comment by MichaelSimons** [comment]
Not worth the ROI.  Closing.
