### ISSUE TITLE
Educate buildtools xunit assemblies about netcoreapp2.0

### ISSUE THREAD

**Issue by alexperovich** [dotnet/buildtools#1295]

**Comment by MichaelSimons** [comment]
@alexperovich, Can you elaborate?

**Comment by mellinoe** [comment]
Is this about adding an enum value for the TFM? https://github.com/dotnet/buildtools/blob/master/src/xunit.netcore.extensions/TargetFrameworkMonikers.cs#L22

**Comment by alexperovich** [comment]
Yes, this is adding the enum value.

**Comment by danmosemsft** [comment]
done
