### ISSUE TITLE
Building an individual project doesn't validate tools/cli version

### ISSUE THREAD

**Issue by ericstj** [dotnet/buildtools#1299]
When tools or CLI are updated build.cmd/init-tools will catch this and redo the install, but if you aren't building those you will never know.  I think it should be straight forward to do a similar check during the Build target and give an error that init-tools should be run.

/cc @weshaggard @danmosemsft

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
