### ISSUE TITLE
Signing Workaround to be Integrated

### ISSUE THREAD

**Issue by bryanar** [dotnet/buildtools#1309]
Currently, in the dotnet/standard repository we have a work around for using the tag <UseOpenKey> at the base of the repository.   The work around looks like this:
```
  <PropertyGroup Condition="$(AssemblyOriginatorKeyFile.Contains('Open.snk'))">
    <StrongNameSig />
    <DelaySign>false</DelaySign>
  </PropertyGroup> 
```

Ideally this gets integrated in to the appropriate place in buildtooling without breaking dotnet/standard (or anyone else)

The intention here is to enable full signing with the open.snk in the open.

**Comment by weshaggard** [comment]
This has been fixed with the BuildTools2.0 work and integrated into standard repo.
