### ISSUE TITLE
Revisit how (and when) we do public signing

### ISSUE THREAD

**Issue by ellismg** [dotnet/buildtools#1311]
I think we need to make a few improvements in how our signing targets play with dev-build/community builds.  Where I'd like to get to is this place (but I'm not a signing expert, so maybe this is wrong)

1. For assemblies where we have full keys checked in (open.snk and test.snk?) we always<sup>1</sup> full sign
2. For other assemblies, the default is to public sign, not delay sign the assemblies.
3. If Microsoft is doing an "official" build and plans to sign, we instead delay sign these assemblies so we can full sign in PRSS later.

I'd also like us to start leveraging the /PublicSign switch in CSC (available via the `<PublicSign>` property in MSBuild) instead of using our custom task or FakeSign tool.  This requires that we are using a someway newish version of Roslyn.  This is already supported today when building on *NIX, I assume we use the same compiler for Windows, but I can't recall for sure.  Certainly it's present in VS 2017.

1: On *NIX today, full signing is not supported.  As a workaround we should just public sign in this case on these platforms, until the issue is addressed.

**Comment by weshaggard** [comment]
related to https://github.com/dotnet/buildtools/issues/1221.

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
