### ISSUE TITLE
Almost empty Strings.resx breaks build on OSX and Linux

### ISSUE THREAD

**Issue by tinchou** [dotnet/buildtools#1315]
I think this issue belongs here but let me know otherwise!

I'm writing [this PR](https://github.com/dotnet/corefx/pull/15646), and if you look at the OSX and Linux CI builds they fail with the following error, but the Windows build doesn't:

```
..../tools/Microsoft.Common.CurrentVersion.targets(2718,5): error MSB3554: Cannot write to the output file "..../bin/obj/Unix.AnyCPU.Debug/System.Data.Odbc/netcoreapp/Resources.Strings.resources". Positive number required. [..../src/System.Data.Odbc/src/System.Data.Odbc.csproj]
..../tools/Microsoft.Common.CurrentVersion.targets(2718,5): error MSB3554: Parameter name: bufferSize [.../src/System.Data.Odbc/src/System.Data.Odbc.csproj]
```

For it to work, I just have to add at the very end of the Strings.resx file one `<data>` element as:

```xml
  <data name="something" xml:space="preserve"><value>something.</value></data>
```

Having different behavior makes writing cross-platform code more difficult.

Thanks!

**Comment by bricelam** [comment]
Might have more luck on [Microsoft/msbuild](https://github.com/Microsoft/msbuild) or [dotnet/sdk](https://github.com/dotnet/sdk)

**Comment by tinchou** [comment]
Thanks @bricelam :D

**Comment by weshaggard** [comment]
Yes this repo doesn't handle any of the Microsoft common targets. I see you filed on the msbuild repo which is more appropriate.
