### ISSUE TITLE
Support testing against full framework

### ISSUE THREAD

**Issue by eatdrinksleepcode** [dotnet/buildtools#132]
BuildTools currently only supports testing against Core. However, Microsoft.DotNet.Build.Tasks is built against the full framework, and must continue to be at least until MSBuild is available for Core. Therefore the corresponding unit test project must also be built and run against the full framework. In order for BuildTools to continue dogfooding itself, it must support testing against the full framework.

There are two potential ways to go about this:

1. Allow the TestHost and XunitExecutable properties to be overridden. The project would then be required to set these properties correctly, as well as provide the full framework version of xunit.
2. Expose a UseCoreForTest property (or similar) that makes the required changes automatically, and also pulls in the correct version of xunit. This would make this functionality more reusable, however I am leaning away from it for two reasons:
  * Core vs full framework is already not transparent to the test project; it has to have the correct xunit reference to start with, and the build tools do not provide the compile-time references (although perhaps they could??).
  * It is my impression that few if any projects intend to use these build tools while targeting the full framework. If we put this functionality into the build tools, and then MSBuild becomes available on Core and the BuildTools are converted to Core, then it will be a change to the BuildTools to remove this functionality. If instead we allow these properties to be overridden, and put the full framework references into the unit test project, then it is just a change to the unit test project to take them out. On the other hand, if my assumption is wrong and there are more projects that target the full framework that could benefit from using BuildTools, then that is a stronger argument for 1 over 2.

**Comment by weshaggard** [comment]
I do think we will need to support running tests on multiple frameworks, at least CoreCLR, Full framework, and eventually .NET Native. So I like some flavor of 1 where we allow the appropriate properties to be overridden. I suspect the best place to override them would be in the metadata of the TestTargetFramework item group.
