### ISSUE TITLE
Clean remaining OSEnvironment usages when corefx changes are merged

### ISSUE THREAD

**Issue by mellinoe** [dotnet/buildtools#1323]
https://github.com/dotnet/corefx/pull/15728#discussion_r99920820

There are a handful of things that are still using `$(OSEnvironment)` in here that are not being overridden by files in corefx. When we integrate corefx back into here, we should make sure to clean those up. All instances should most likely be replaced with a check like: `"'$(RunningOnUnix)' == 'true'"`.

**Comment by weshaggard** [comment]
Doing this as part of the BT2 effort

**Comment by weshaggard** [comment]
Done
