### ISSUE TITLE
MSBuild.runtimeconfig.json is getting overridden by a file in Microsoft.Build.Runtime

### ISSUE THREAD

**Issue by mellinoe** [dotnet/buildtools#1325]
When I updated us to the latest version of MSBuild, we switched to using a new package called Microsoft.Build.Runtime. This includes a runtimeconfig.json file for MSBuild, but it is locked at version 1.0.1 of the shared framework. It overrides the one that we have in this repo. We should explicitly copy out our version in init-tools.sh after we have published the tool-runtime project.

**Comment by MichaelSimons** [comment]
Taking ownership.  I am working on updating CoreCLR to take latest tools for another fix.  This needs to be fixed for this to happen.
