### ISSUE TITLE
Create a better minimal MSBuild logger

### ISSUE THREAD

**Issue by ericstj** [dotnet/buildtools#1334]
When running the build in jenkins and on the commandline we only get -v:minimal spew from the console logger.  This is often not enough info to understand the cause of the failure.  In the local build case we can crack open the log, but this is often not convenient or even available for official builds.  Even when we do have the log we need to dig through interleaved messages, and even then we might be missing context (eg: property values) since the log file is rightfully not a diag log.

We should consider adding our own logger that has the same message spew as -v:minimal but includes more detail in Error messages.

Some suggestions:
1. Preceding message spew (Normal and up) from the same node/project.
2. Some properties from the failing project, eg: Configuration.
3. Project stack for the failing project.

All of these should be relatively easy to get, I keep track of some similar things in the binclash logger.

/cc @danmosemsft @stephentoub @mellinoe @alexperovich

**Comment by danmosemsft** [comment]
Is the regular logger sufficient, in higher verbosity?

If so, it would be cheaper to simply automatically attach a second logger that logs at that higher verbosity. Just as we already attach a logger for errors only, and another for warnings only.

This would be easy (edit msbuild.rsp) except on Windows we use the global msbuild.exe still. We do contol the parameters if msbuild is launched with build.cmd, that's where we attach those existing loggers already.

**Comment by danmosemsft** [comment]
Really we should not use the global msbuild, but I'm not sure ther'es an issue for that.That would give us other benefits such as parity with Unix, and the ability to grab up to date fixes as needed.

**Comment by ericstj** [comment]
> Is the regular logger sufficient, in higher verbosity?

No.  The regular logger has both too much information and not enough.  At diag level you have most of the info you need, but it isn't easy to access (due to nodes interleaving, properties being separated, etc).  Additionally, diag is much too large to easily access from Jenkins or in the failure page for the build.

I'm proposing a minimal logger, that will log more info but only on an error.  We could customize the info logged so that it is relevant to our build system.  We could also make it extensible to include additional info (eg: content of an item or property at point of error).

As for using the core msbuild rather than desktop, that's related to https://github.com/dotnet/buildtools/issues/1284 but not sure if we have a separate issue.

**Comment by danmosemsft** [comment]
Fair enough. Implementation wise it might possibly be possible & easier to aggregate or derive from the existing logger.

My point about needing to control our own msbuild.rsp remains, I think. (Or if MSBuild had an environment variable like MSBUILDCOMMANDLINEADDITIONS that build.cmd could set up, that would work. I don't think it does)

**Comment by danmosemsft** [comment]
Another option might work: msbuild looks for any `msbuild.rsp` next to the entrypoint project. If we put one of those next to every project we have, it need only contain a single line like `@..\..\..\global.rsp` and `global.rsp` sits at the root and contains your logger flag.

**Comment by ericstj** [comment]
@danmosemsft good point about the logistics of hooking up a logger.  I think a first step is having a logger and hooking it up for our normal calls to build.cmd|build.sh.  Adding it to arbitrary MSBuild calls is also something to investigate but that's a separate issue.

**Comment by danmosemsft** [comment]
https://github.com/Microsoft/msbuild/issues/1701

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
