### ISSUE TITLE
ApiCompat is not catching mismatched ref return values

### ISSUE THREAD

**Issue by ericstj** [dotnet/buildtools#1339]
@mellinoe and I noticed this when creating a reference assembly for Unsafe.

**Comment by weshaggard** [comment]
Might be fixed by #1377 but we should verify

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
