### ISSUE TITLE
Including ilasm in tool-runtime/project.json causes duplicate CoreCLR files in the Tools directory

### ISSUE THREAD

**Issue by mellinoe** [dotnet/buildtools#1352]
Since we've added ilasm and CoreCLR to the dependencies of tool-runtime/project.json, we now restore and publish extra CoreCLR files next to ilasm, in the root of Tools. These files should be harmless (and identical to the ones under dotnetcli/shared/..., but aren't strictly necessary. coreclr.dll/so is necessary for ilasm, but nothing else.

**Comment by mellinoe** [comment]
We're not doing this anymore.

**Comment by weshaggard** [comment]
We do still need an issue tracking adding ilasm support to BuildTools.
