### ISSUE TITLE
.net standard compilation doesn't resolve dependent types in child .net standard assembly

### ISSUE THREAD

**Issue by Gentlehag** [dotnet/buildtools#1357]
Sorry for muiltiipost but i don't feel sure where to post ist.
I'm not sure wether this is the right place. If not please let me know where i should push this.

When having two .net standard libraries i can't use types of one .net standard project in another one .
It looks like the types of the dependent assembly don't get resolved.

For this I create 2 .net standard 1.4 projects I add a class to the libary project, and try to access the class of this project in the consumer project. but it looks like it can't get resolved.

see also https://stackoverflow.com/questions/42526008/net-standard-doesnt-resolve-child-assemblies
I pushed a sample here: https://github.com/Gentlehag/NetStandardBugSample

![image](https://cloud.githubusercontent.com/assets/4619513/23450737/f59461e4-fe5c-11e6-86d4-94e0ce6d3bd7.png)

**Comment by weshaggard** [comment]
This isn't the correct repo and based on your other issue you seem to have figured out the issue, so closing.
