### ISSUE TITLE
[Dumpling] Traversal test builds should only run "Dumpling install" once

### ISSUE THREAD

**Issue by mellinoe** [dotnet/buildtools#1360]
Right now, we are running the install script multiple times in our traversal builds. This adds a lot of unnecessary spew in the output logs, and just isn't necessary. We should be able to just run it one time before the test traversal, and we can continue to run it per-project if you are building individual projects.

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
