### ISSUE TITLE
Rename $(ProjectDir) to $(RepoDir) or something similar

### ISSUE THREAD

**Issue by eerhardt** [dotnet/buildtools#1367]
`$(ProjectDir)` is a poor name to be used for the directory that is the root of the repository.  When you are looking at MSBuild logic, and come across `$(ProjectDir)` in a .csproj, your first inclination is that this is the directory in which the .csproj (the "project" in msbuild) is contained.

We should rename this property (which is required to be declared in all repos that use build tools) to something that is more understandable to new people.  That way folks don't get confused, and don't need "tribal knowledge" to know that `$(ProjectDir)` really means `$(RepoRootDir)`.

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
