### ISSUE TITLE
Update to latest XUnit

### ISSUE THREAD

**Issue by richlander** [dotnet/buildtools#1372]
Update checked-in xunit to latest xunit. Goal is to include xunit licensed to the .NET Foundation. See #1371.

This search for "outercurve" should no longer return any results in the repository: https://github.com/dotnet/buildtools/search?utf8=%E2%9C%93&q=outercurve

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
