### ISSUE TITLE
Centralize MSBuild resolution logic skip

### ISSUE THREAD

**Issue by chcosta** [dotnet/buildtools#1381]
CoreFx and CoreClr currently have workarounds for MSBuild resolution logic which is throwing MSB3644 because we use our own resolution logic.  We should centralize this logic in BuildTools rather than sprinkling the workaround throughout the corefx / coreclr code base.

https://github.com/dotnet/coreclr/pull/10020/files

/cc @weshaggard

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
