### ISSUE TITLE
README points to wrong package

### ISSUE THREAD

**Issue by jaredpar** [dotnet/buildtools#1393]
The README page points to the following location for viewing the NuGet package:

> http://nuget.org/packages/Microsoft.DotNet.BuildTools

This page says the package is unlisted and has no versions.  Should this be changed to a MyGet link?

**Comment by weshaggard** [comment]
Fixed with https://github.com/dotnet/buildtools/commit/c4d11232976e7439ffcd235e6652ec86fa36ded6
