### ISSUE TITLE
Improve SkipOnTargetFramework for UAP use

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/buildtools#1395]
@danmosemsft commented on [Thu Mar 16 2017](https://github.com/dotnet/corefx/issues/17193)

Right now TFM is defined like this
```
    public enum TargetFrameworkMonikers
    { ...
        NetFramework = 0x800,
        Netcoreapp = 0x1000,
        Uap = 0x2000,
        UapAot = 0x4000,
```
and these map 1:1 to the XUnit traits passed to the runs:
```
        internal static string NonNetfxTest = "nonnetfxtests";
        internal static string NonUapTest = "nonuaptests";
        internal static string NonUapAotTest = "nonuapaottests";
        internal static string NonNetcoreappTest = "nonnetcoreapptests";
```

Code for uap, uapaot, and netcoreapp is 99% the same and functional behavior should be 99% the same between netcoreapp and uap and 98% the same with uapaot. We want most implementation and tests to be oblivious of the differences.

So 
(1) it would be nice to have a shortcut for
 `[SkipOnTargetFramework(TargetFrameworkMonikers.Netcoreapp | TargetFrameworkMonikers.Uap  | TargetFrameworkMonikers.UapAot)]`

(2) it would be nice for `TargetFrameworkMonikers.Uap` to automatically include `TargetFrameworkMonikers.UapAot` just as `#if uap` applies in `uapaot` builds also.

This change would actually be in buildtools but I'll put it here for discussion first.

---

@danmosemsft commented on [Thu Mar 16 2017](https://github.com/dotnet/corefx/issues/17193#issuecomment-287140452)

@jkotas for comment on #2

---

@jkotas commented on [Thu Mar 16 2017](https://github.com/dotnet/corefx/issues/17193#issuecomment-287147810)

This is basically another incarnation of TFM hierarchy.

> it would be nice to have a shortcut for
> [SkipOnTargetFramework(TargetFrameworkMonikers.Netcoreapp | TargetFrameworkMonikers.Uap | TargetFrameworkMonikers.UapAot)]

There is a shortcut for it today used in number of places: `[SkipOnTargetFramework(~TargetFrameworkMonikers.NetFramework, ...)]`. It explains pretty well what it actually is - it is testing behavior that was changed from .NET Framework.

> it would be nice for TargetFrameworkMonikers.Uap to automatically include TargetFrameworkMonikers.UapAot

Agree. Ideally, there would be no UapAot at all.

**Comment by dleeapho** [comment]
@danmosemsft assigning so you can drive consensus on the TFM hierarchy.

**Comment by danmosemsft** [comment]
I think the only work here is to make disabling a test for `TargetFrameworkMonikers.Uap` also automatically disable it for `TargetFrameworkMonikers.UapAot`. I think that means changing
```
        Uap = 0x2000,
        UapAot = 0x4000,
```
to eg
```
        UapAot = 0x4000,
        Uap = 0x6000,
```

and later, cleaning up CoreFX to change any ` TargetFrameworkMonikers.Uap | TargetFrameworkMonikers.UapAot` to just ` TargetFrameworkMonikers.Uap`

**Comment by danmosemsft** [comment]
@safern since you're messing around with similar things would you mind doing this?

**Comment by safern** [comment]
Sounds good. I'll do this later.

**Comment by safern** [comment]
> Agree. Ideally, there would be no UapAot at all.

We could remove UapAot option and have the same trait for both targets or return both keys in the discoverer when SkipOnTargetFramework has flag `UapAot`. 

We currently have: 
```cs
if (platform.HasFlag(TargetFrameworkMonikers.Uap))
    yield return new KeyValuePair<string, string>(XunitConstants.Category, XunitConstants.NonUapTest);
if (platform.HasFlag(TargetFrameworkMonikers.UapAot))
    yield return new KeyValuePair<string, string>(XunitConstants.Category, XunitConstants.NonUapAotTest);
```

we could change it to:
```cs
if (platform.HasFlag(TargetFrameworkMonikers.Uap))
{
    yield return new KeyValuePair<string, string>(XunitConstants.Category, XunitConstants.NonUapTest);
    yield return new KeyValuePair<string, string>(XunitConstants.Category, XunitConstants.NonUapAotTest);
}
```

Which will return: 
```
* "category" "nonuaptests"
* "category" "nonuapaottests"
```

therefore when running on uap xunit will be passed an argument `-notrait category=nonuaptests` and uapaot `-notrait category=nonuapaottests` which will be skipped in both cases as we are returning both categories for that test method flagged with `SkipOnTargetFrameworkMonikers.Uap`

**Comment by danmosemsft** [comment]
We do need separate levers as whether we like it or not some tests are different and likely always will be some.
