### ISSUE TITLE
Need to investigate and fix missing GetTargetFrameworkProperties target when updating buildtools

### ISSUE THREAD

**Issue by MattGal** [dotnet/buildtools#1417]
It's likely a mis-set property or path construction, but when upgrading WCF to the latest build tools version  I ended up having to make the following workaround:

https://github.com/dotnet/wcf/blob/master/src/dir.targets#L28 

While it's fairly innocuous, it should be understood and fixed.  GetTargetFrameworkProperties is defined in Microsoft.Common.CurrentVersion.targets so should always be around.

**Comment by dleeapho** [comment]
Fix could be in WCF or buildtools.

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
