### ISSUE TITLE
GetPackageVersion is defined in two task assemblies.

### ISSUE THREAD

**Issue by ellismg** [dotnet/buildtools#1423]
It's defined in both Microsoft.DotNet.Build.Tasks and Microsoft.DotNet.Build.Tasks.Packaging which means you have to choose one or the other to Using task or everything goes sideways.  Is this expected (I ran into this problem when trying to update buildtools to consume the latest buildtools and packaging.builds pulled in targets files that tried to UsingTask both and it went about as well as you'd expect).

**Comment by ericstj** [comment]
This was accidental.  I suspect we came up with the names independently.  The packaging one is only really ever used for pkgproj and the buildtools one only used for the old nuspec packing targets (only used by buildtools itself AFAIK)

**Comment by dagood** [comment]
The comments already imply it, but to clarify, the tasks do have significantly different functionality:
[Microsoft.DotNet.Build.Tasks/GetPackageVersion.cs](https://github.com/dotnet/buildtools/blob/307a2e958f34e6892e72b3969c00fbc28ed58617/src/Microsoft.DotNet.Build.Tasks/GetPackageVersion.cs)
[Microsoft.DotNet.Build.Tasks.Packaging/src/GetPackageVersion.cs](https://github.com/dotnet/buildtools/blob/307a2e958f34e6892e72b3969c00fbc28ed58617/src/Microsoft.DotNet.Build.Tasks.Packaging/src/GetPackageVersion.cs)
Renaming makes sense.

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
