### ISSUE TITLE
Tests should build and run when building on *nix

### ISSUE THREAD

**Issue by ellismg** [dotnet/buildtools#1430]
Today tests are disabled in the top level dir.props.

There are a few issues:

1. We need to add rids to the test projects
2. We need to ensure NuGetRuntimeIdentifier is getting set correctly (today projects hard code things to win7-x64 which means the wrong assets are deployed)
3. Some tests depend on file system enumerator order and we need to update these tests.

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
