### ISSUE TITLE
Restore OptimizationData package as optional tooling

### ISSUE THREAD

**Issue by dagood** [dotnet/buildtools#1436]
Right now there is a specific target to restore this package, `RestoreOptimizationDataPackage`.

~~Note: this means that optional tooling restore will need to be configured for multiple feeds.~~

**Comment by weshaggard** [comment]
>Note: this means that optional tooling restore will need to be configured for multiple feeds.

Why? Is there some reason we cannot put these on the same feed? I'm OK with supporting multiple feeds but if it isn't necessary we should avoid it.

**Comment by dagood** [comment]
I suppose we could--we could ask whoever's publishing these packages to push it to our tooling feed or just mirror the packages over ourselves.

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
