### ISSUE TITLE
Set AllowMultipleUse to true on SkipOnTargetFrameworkAttribute

### ISSUE THREAD

**Issue by AtsushiKan** [dotnet/buildtools#1446]
If [ActiveIssue] can be used multiple times on the same test, [SkipOnTargetFramework] should be able to do so as well.

I've been adding hundreds of [SkipOnTargetFramework(UapAot, "BlahBlahBlah is not supported on UapAot"] and it's a PITA when there's a [SkipOnTargetFramework(NetFramework)] already there for a completely different reason.

This can be considered part of https://github.com/dotnet/buildtools/issues/1395

**Comment by safern** [comment]
@danmosemsft taking this one as I've been touching this side lately.
