### ISSUE TITLE
TreatSpecificWarningsAsErrors does not work

### ISSUE THREAD

**Issue by bungeemonkee** [dotnet/buildtools#1456]
I'm having a problem with dotnet build not respecting the TreatSpecificWarningsAsErrors  option in the csproj. It's a .net standard 1.4 project being built with version 1.03 of the cli and msbuild 15.1.1012.6693. If I set TreatSpecificWarningsAsErrors to either 'CS1519' or just '1519' it doesn't treat the warning as an error.

I've tried several other error numbers in TreatSpecificWarningsAsErrors and it seems to ignore the value regardless.

Side note: If I set TreatWarningsAsErrors to 'True' it fails for other warnings but CS1519 is now ignored entirely (not displayed as a warning or an error) regardless of the value of TreatSpecificWarningsAsErrors .

Just for reference, CS1519 is the error 'Missing XML comment for publicly visible type or member...'.

Thanks!

**Comment by dleeapho** [comment]
Issue moved to [dotnet/cli #6485](https://github.com/dotnet/cli/issues/6485) via [**ZenHub**](https://www.zenhub.com/)
