### ISSUE TITLE
Remove msbuild from BuildTools package

### ISSUE THREAD

**Issue by weshaggard** [dotnet/buildtools#1458]
Instead of pulling in our own msbuild we should use the msbuild that comes from the CLI. That will require all repo's to update the cli they depend on so once we get those converted we should test this out and do it.

**Comment by mellinoe** [comment]
There seem to be differences in how some properties are being set when using the "built-in" MSBuild assembly with the SDK. Here's the error I get when I try to just run corefx's `build.sh` with it.

```
/home/eric/corefx/Tools/FrameworkTargeting.targets(114,3): error MSB4019: The imported project "/home/eric/corefx/Tools/dotnetcli/sdk/2.0.0-preview1-005724/Microsoft/Portable/v4.5/Microsoft.Portable.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk. [/home/eric/corefx/src/Tools/CoreFx.Tools/CoreFx.Tools.csproj]
```

That line is this:

```
  <Import Project="$(MSBuildExtensionsPath32)\Microsoft\Portable\$(TargetFrameworkVersion)\Microsoft.Portable.CSharp.targets"
          Condition="'$(TargetFrameworkIdentifier)' == '.NETPortable' and '$(MSBuildProjectExtension)' == '.csproj'" />
```

So I guess that `MSBuildExtensionsPath32` is being overridden to the SDK directory, when we don't want it to be. In principle we should be able to get this to work "easily", but there's probably some issues like the above that we don't know about yet.

**Comment by mellinoe** [comment]
It would be really, really nice to eliminate the MSBuild bootstrapping, though. Anything to reduce the craziness of the bootstrapping process is good to pursue.

**Comment by weshaggard** [comment]
@mellinoe agreed. We should probably rip out all that .NETPortable stuff when we do this switch because we now have better support for referencing that doesn't need the portable targets.

**Comment by joperezr** [comment]
@weshaggard Do we want to force using this msbuild on Windows builds as well? Or do we want it still to only be used on non-Windows builds?

**Comment by weshaggard** [comment]
Lets take it one step at a time and just move the non-windows builds to use the CLI msbuild first and then we can look at getting the windows builds to use it.

**Comment by danmosemsft** [comment]
@weshaggard I am marking this Future.

**Comment by weshaggard** [comment]
This is the next step in the tools work for product construction so I don't think it is the far future but it may not be fully completed in 2.1 timeframe.

**Comment by joperezr** [comment]
This has been done for a while, so closing this one.
