### ISSUE TITLE
Fix Microsoft.CSharp.Targets import workarounds

### ISSUE THREAD

**Issue by weshaggard** [dotnet/buildtools#1464]
Microsoft.CSharp.Targets is imported in multiple places with different casing which causes issues on our linux builds which are case-sensitive file systems. Some of the imports are coming from SdK/portable targets and some from ours but we have number of workarounds in places that we should try to reconcile and eliminate.

https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.sh#L146

https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks/PackageFiles/FrameworkTargeting.targets#L70

```
  <!-- workaround file casing issue where it has different casing in different places which fails on linux builds -->
  <PropertyGroup>
    <CSharpTargetsFile>$(MSBuildToolsPath)\Microsoft.CSharp.targets</CSharpTargetsFile>
    <CSharpTargetsFile Condition="!Exists('$(CSharpTargetsFile)')">$(MSBuildToolsPath)\Microsoft.CSharp.Targets</CSharpTargetsFile>
  </PropertyGroup>
```

**Comment by wtgodbe** [comment]
https://github.com/dotnet/buildtools/pull/2048 addresses the workaround in init-tools.

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
