### ISSUE TITLE
BuildTools needs to identify some stable contract for project targeting

### ISSUE THREAD

**Issue by ericstj** [dotnet/buildtools#1465]
Consider that old CSProj has a contract of TargetFrameworkIdentifier/TargetFrameworkVersion and the targets you import.

New SDK projects have the contract of TargetFramework or TargetFrameworks and the rest is handled by the SDK targets.

After either of these are set there are a set of properties that you can depend on being set by the common targets, like TargetFramework(Identifier,Version,Profile), NuGetTargetMoniker, potentially others.

In buildtools we've been sloppy about this sort of thing.  Its changed over time and right now there is no garuntee in what we'd expect the repo to set vs what BuildTools will then derive from what the repo sets.

I reccomend that in order to converge on a common contract we have the repo set TargetFramework (deriving it from TargetGroup or however the repo deems fit) then BuildTools is reponsible for everything else.

/cc @weshaggard

**Comment by weshaggard** [comment]
Seems reasonable.

**Comment by mellinoe** [comment]
Would buildtools be responsible for restoring all of the "targeting pack" assets for different project targeting options, then?

**Comment by ericstj** [comment]
Depends on what scope you want to give this.  If you want to scope in setting up the reference path and populating it, then yes, but I wasn't imagining that as part of the contract.  I was mostly just concerned with an agreed upon set of input properties and output properties.

**Comment by weshaggard** [comment]
I think we should switch to using the common SDK/Nuget properties and eliminate as much as possible our custom properties. We should use TargetFramework (which will be built up from our TargetGroup,OSGroup,ArchGroup).

On top of that we should consider using TargetFrameworks for cross-compiling instead of BuildConfigurations, or at least have our BuildConfigurations set the TargetFrameworks property.

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
