### ISSUE TITLE
Move dir.traversal.targets into BuildTools

### ISSUE THREAD

**Issue by weshaggard** [dotnet/buildtools#1467]
We should move most of the common logic for traversing projects into BuildTools. Things in https://github.com/dotnet/corefx/blob/master/dir.traversal.targets and https://github.com/dotnet/corefx/blob/master/buildvertical.targets for example.

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
