### ISSUE TITLE
Debian and Ubuntu docker files warning "setlocale: LC_ALL: cannot change locale (en_US.UTF-8)"

### ISSUE THREAD

**Issue by eerhardt** [dotnet/buildtools#1471]
When building `dotnet/core-setup/master` inside of a docker container using any of the following images:

```
microsoft/dotnet-buildtools-prereqs:debian-8.2-debpkg-9f87c3c-20173003023006
microsoft/dotnet-buildtools-prereqs:ubuntu-16.10-debpkg-ec863bb-20170003030028
microsoft/dotnet-buildtools-prereqs:ubuntu-16.04-debpkg-e5cf912-20174703024721
microsoft/dotnet-buildtools-prereqs:ubuntu-14.04-debpkg-e5cf912-20175003025046
```

I'm getting warnings during the build that look like:

```
/bin/bash : warning : setlocale: LC_ALL: cannot change locale (en_US.UTF-8) [/root/core-setup/src/pkg/packaging/dir.proj
perl : warning : Setting locale failed. [/root/core-setup/src/pkg/packaging/dir.proj]
perl : warning : Please check that your locale settings: [/root/core-setup/src/pkg/packaging/dir.proj]
perl : warning : Falling back to the standard locale ("C"). [/root/core-setup/src/pkg/packaging/dir.proj]
perl : warning : Setting locale failed. [/root/core-setup/src/pkg/packaging/dir.proj]
```

We've seen this before, and it causes problems when commands' output are trying to be parsed.  See the discussion starting at https://github.com/dotnet/sdk/pull/935#issuecomment-285087032 for when this broke the CLI builds.

We should configure our docker images to not get these warnings.

/cc @MichaelSimons @ellismg @chcosta

**Comment by chcosta** [comment]
I was able to fix this in a docker container I was running last night (Ubuntu 14.04), by running `locale-gen en_US.UTF-8`

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
