### ISSUE TITLE
Generated PlatformNotSupported constructors may not throw PlatformNotSupported.

### ISSUE THREAD

**Issue by ghost** [dotnet/buildtools#1486]
They'll first invoke the base constructor with default(this), default(that). The base constructor could be in another package that has an implementation.

The base constructor might respond to that with an ArgumentNullException or NullReferenceException and the caller will see that rather than the PNSE.

**Comment by weshaggard** [comment]
@AtsushiKan is there a recommended way to fix this?

**Comment by AtsushiKan** [comment]
You could replace ": base(default(T))" with ": base(PNSE<T>())"

private static T PNSE<T>() { throw new PNSE(); }


Of course, this won't work for nullary base constructors but there's probably less risk of a weird exception leaking out in that case.

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
