### ISSUE TITLE
VersionTools and BuildTools have inconsistent version numbers

### ISSUE THREAD

**Issue by eerhardt** [dotnet/buildtools#1489]
Inspect the package versions at:

https://dotnet.myget.org/feed/dotnet-buildtools/package/nuget/Microsoft.DotNet.VersionTools
https://dotnet.myget.org/feed/dotnet-buildtools/package/nuget/Microsoft.DotNet.BuildTools

VersionTools still has `1.0.27`.
BuildTools has `2.0.0`.

This is confusing to understand which versions are in sync.

@dagood also points out that branching can be affected here, because branch build version numbers could overlap without a fix, and we lose version coherency.

**Comment by weshaggard** [comment]
Do we really want all the version numbers to match across all packages we ship in BuildTools? If so then we should probably switch to using the pkgproj's so we an share a common property for it.

**Comment by eerhardt** [comment]
> Do we really want all the version numbers to match across all packages we ship in BuildTools?

I guess I'm not 100% sure on our plans for branching/servicing BuildTools.  It does seem to make things easier to understand when all `X.Y.Z` versions of packages come from the same branch.  Just like in corefx when we moved to all packages to `4.3.0` versions.

> If so then we should probably switch to using the pkgproj's so we an share a common property for it.

Can't we just use a common `.props` file that has the version prefix in it? ... Ah I see that we have checked-in .nuspec files.  An alternative to pkgproj's is to use `dotnet pack` or `msbuild /t:Pack` using the new Microsoft.NET.Sdk.  Or to use a replacement value `$version$`.

**Comment by dagood** [comment]
The versions don't need to be exactly the same, but we do need to bump each version across the entire repo. For example, if we are building BuildTools 1.1.0 and 2.0.0 Git branches with VersionTools `1.0.0-beta-*` in both branches, the best that can happen is thrashing: adjacent VersionTools `1.0.0-beta-*` builds can come from different branches. If we don't have unique build ids (and I don't think we will) we would get last-wins MyGet overwriting behavior.

Keeping everything in exact sync seems the easiest way to maintain this.

**Comment by dagood** [comment]
This is fixed by https://github.com/dotnet/buildtools/pull/1755 in master: all packages are now `2.1.0-prerelease-*`. It should be easy to port to other branches if we encounter overlap (or if the clarification itself is useful enough).
