### ISSUE TITLE
Update dotnet/versions LKG_Packages file automatically

### ISSUE THREAD

**Issue by dagood** [dotnet/buildtools#1514]
This file is like Latest_Packages in that old entries aren't cleared (https://github.com/dotnet/buildtools/pull/1118), but for LKG_Packages, updates should only be performed if the current build produced a stable version. /cc @ericstj @chcosta 

See https://github.com/dotnet/versions/issues/161 (the LKG file being out of date since it's a manual step)

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
