### ISSUE TITLE
Eliminate PackagePlatform from buildtools

### ISSUE THREAD

**Issue by ericstj** [dotnet/buildtools#1519]
See https://github.com/dotnet/buildtools/blob/3309085641d2fe6a6193915dd89ffbb159dad9fb/src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets#L90-L104

This is a remnant of the old way we filtered project builds prior to the configuration system and prior to even the builds files.

No-one should be relying on this anymore, but its presence causes pain for folks in CoreFx and CoreCLR.

We need to completely deprecate it and remove it from packaging.

/cc @chcosta @karajas

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
