### ISSUE TITLE
xunit.console.netcore.exe command line syntax is far too verbose for the simple cases.

### ISSUE THREAD

**Issue by AtsushiKan** [dotnet/buildtools#1538]
Scenario: To run a test I just built: On ToF (closed source Project N test infra that's being replaced for the "superior" xunit), I go to the output directory and type:

         unittests.exe

   In contrast, on corefx:

         xunit.console.netcore.exe System.Runtime.Tests.dll -notrait Benchmark=true -notrait category=nonuapaottests -notrait category=OuterLoop -notrait category=failing -notrait category=nonwindowstests
   
   All this for the default case. For a tool that doesn’t even support response files. That whole mouthful has to be crammed into that tiny little textbox inside VS’s debugger window.

   On ToF, to run a specific test, such as TypeInfoTest.GetMethodTests()

          unittests.exe getmethodtests

  Nice and human-friendly – simple case-insensitive subset matching – use with “-l” switch if you just want to see what test(s) would be run with this pattern. Can also use to run groups of tests.

   On corefx

         xunit.console.netcore.exe System.Runtime.Tests.dll -method System.Reflection.TypeInfoTests.GetMethodTests

I have to type the entirely fully qualified path with no mistakes. This switch is designed for automation, not human input.

  **Ask 1**: xunit.console.netcore.exe should support response files (including multi-line response files.)
         Perfect for when you have a list of methods to focus on – “sed “s/^/-method /g” > foo.rsp; xunit.console.netcore.exe @foo.rsp
     
  **Ask 2**: xunit.console.netcore.exe should automatically read from a default response file (xunit.console.netcore.rsp next to the .exe) RunTests.cmd (or whatever) should create xunit.console.netcore.rsp and invoke “xunit.console.netcore.exe” without the 100+ character command line it does today.

  **Ask 3**: Human-friendly command line switches for browsing and selecting tests. Similar to what ToF supports today.

**Comment by maririos** [comment]
@AtsushiKan your points are valid. We can't afford to diverge from this pattern at this time.

**Comment by karelz** [comment]
@maririos can you shed some light on why we can't diverge? Is it purely resource-limited?
Or are there dependencies which prevent us to change it ever?

**Comment by maririos** [comment]
Resource-limit. During our triage meeting we evaluated the work and the resources for it and decided to close the issue.

@dleeapho

**Comment by karelz** [comment]
In that case I would expect the item to stay on backlog with Future milestone or something like that. If we close it, we lose it. Or is there some process to reopen issues closed due to resource-limitation after a while?
