### ISSUE TITLE
Make sure Helix machines are set up to collect dumps on Windows

### ISSUE THREAD

**Issue by mellinoe** [dotnet/buildtools#1540]
The Dumpling integration targets and scripts require that a crash dump folder be provided for Windows. 

We should make sure that this property is being set: https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/Dumpling.targets#L17.

In order to configure machines to collect crash dumps, we need to set the following registry keys:

```
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps\dotnet.exe                                                                                                                                            
    \DumpFolder = <path to crash dump folder> (String)
    \DumpType = 2 (DWORD)
```

**Comment by mellinoe** [comment]
@MattGal

**Comment by karajas** [comment]
Does it make sense to set a DumpCount and limit it to 1 here? /cc @DrewScoggins

**Comment by DrewScoggins** [comment]
I do not know exactly.  Given what I know about Helix it seems like we reuse machines to run work items, and if we set this to one wouldn't that block dumps from machines that had a dump created on them already, and then have another failure while running other tests.

**Comment by maririos** [comment]
@MattGal

**Comment by DrewScoggins** [comment]
I think we can go ahead and close this.  We are collecting dumps on Windows VMs.

**Comment by MattGal** [comment]
Sounds good to me @DrewScoggins .  I know we've automated this on the VMs but it hasn't happened on the ARM machines.  I'll close for now and we can revisit this if that's ever needed.
