### ISSUE TITLE
Use checked-in definitions for BuildTools official build

### ISSUE THREAD

**Issue by dagood** [dotnet/buildtools#1546]
The VSTS definition is relatively simple, but the benefits of checked-in defs still apply. This is also dogfooding.

**Comment by dagood** [comment]
This would also let us easily pass BuildTools build telemetry to MC.

**Comment by maririos** [comment]
Closing as we are going to take a different approach by testing the Jenkins official builds. 
@dagood por favor open the issue in core-eng
