### ISSUE TITLE
BuildVersion support update for SDK based projects

### ISSUE THREAD

**Issue by eerhardt** [dotnet/buildtools#1548]
We should make the following changes to the BuildVersion support in order to work better with SDK-based .csprojs.

- `BuildVersionFilePath` should be conditional based on whether it is set or not. https://github.com/dotnet/buildtools/blob/78260239e4db68ad5c2df774a27d5f9a54fd92e5/src/Microsoft.DotNet.Build.Tasks/PackageFiles/BuildVersion.targets#L5.  
  - The definition of `$(BaseIntermediateOutputPath)` morphed a bit with SDK-based projects.  It was acceptable with original-style .csproj to have multiple projects pointing to the same `$(BaseIntermediateOutputPath)` location.  However, this is where NuGet writes the project.assets.json file by default, which means it has to be unique across different projects.
- The `BuildVersionFile` should set the `<VersionSuffix>` property.
  - VersionSuffix is a new property that is respected by SDK-based projects.  We are already setting it during the build if the `BuildVersionFile` doesn't exist: https://github.com/dotnet/buildtools/blob/36c522b935eec92c8b0440e9c5dde36e6e122d71/src/Microsoft.DotNet.Build.Tasks/PackageFiles/versioning.targets#L404-L410.  We should ensure this property is set in the file as well.

/cc @chcosta @weshaggard

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
