### ISSUE TITLE
RunnerTemplate.Unix complains when /cores is empty

### ISSUE THREAD

**Issue by mellinoe** [dotnet/buildtools#1552]
OSX machines may not have any crash dumps under /cores/, or the folder may have not been created yet. RunnerTemplate.Unix still runs `ls -A /cores`, which will print out a message if the folder doesn't exist.

https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks/PackageFiles/RunnerTemplate.Unix.txt#L55

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
