### ISSUE TITLE
Simplify init-tools flow

### ISSUE THREAD

**Issue by karajas** [dotnet/buildtools#1554]
Currently we have a process where each repo has an init-tools that calls into the buildtools init-tools.
For the Windows case this further calls into the init-tools.ps1 which has folder dependencies on the inner init-tools. 

It would be nice to simplify this process to a single call.

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
