### ISSUE TITLE
Consider adding a build target which ensures the git repository is clean

### ISSUE THREAD

**Issue by mellinoe** [dotnet/buildtools#1555]
Occasionally, some changes are made which can cause subsequent builds of our repositories to modify parts of the repository. This includes things like our API compat baseline files. Additionally, there are some other components, like our solution files, which can be automatically synchronized, but may fall slightly out-of-sync if contributors do not run the target. There isn't anything right now in our build that will alert us to such cases. Oftentimes an unrelated contributor, at a later time, will realize that something is out of sync, or a solution file is broken, and will not understand what needs to be done to fix it. We should consider building a target which does something like:

* Run commands which potentially modify the repository. `build.cmd`, `msbuild build.proj /t:updatevsconfigurations`, etc.
* Run a "git status" command, or otherwise determine if the repository is dirty.
* Cause a build error if there are any changes to the repository.

On top of this, we could set up an optional leg in corefx which runs this target after the build. At the very least, it would let us determine which files a contributor forgot to update, what commands need to be run, etc.

**Comment by maririos** [comment]
We are closing this for now as it is low in the priority list.
If it becomes a frequent problem we'll re evaluate.

**Comment by wfurt** [comment]
seems shame to close it even if it is low priority. This is going to bite us back and cause wasted time.
