### ISSUE TITLE
init-tools.cmd -> init-tools.ps1 exxecution policy / error handling could be improved

### ISSUE THREAD

**Issue by JosephTremoulet** [dotnet/buildtools#1557]
Possibly two issues here:
 1. We should likely pass `-ExecutionPolicy unrestricted` (and `-NoProfile`?) arguments to powershell, like similar scripts in coreclr repro do.
 2. init-tools.cmd silently drops errors from invoking init-tools.ps1 (such as the effective execution policy refusing to run it), which leads to difficult-to-diagnose failures down the road (e.g. FileNotFound exceptions during coreclr build).

See discussion in dotnet/coreclr#12176

**Comment by ellismg** [comment]
+1 to passing -NoProfile.
