### ISSUE TITLE
Stop building Microsoft.xunit.extensibility.execution.netcore redist package if possible

### ISSUE THREAD

**Issue by dagood** [dotnet/buildtools#1560]
`Microsoft.xunit.extensibility.execution.netcore` is a redist of `xunit.extensibility.execution` when Xunit didn't support netcoreapp, so it might not be required anymore. We should investigate if it's still used/needed and remove it from BuildTools if we can.

/cc @brianrob @karajas

**Comment by weshaggard** [comment]
+1

fyi - @danmosemsft as I know you were looking at similar things

**Comment by danmosemsft** [comment]
I had attempted to upgrade it, but it turned out to need some work, so I put it aside. We alreayd have an issue to upgrade it -- https://github.com/dotnet/buildtools/issues/1372

**Comment by dagood** [comment]
Do you think it makes sense to close this issue as a dupe of #1372, and mention there explicitly that we should stop building the package as part of the work?

**Comment by maririos** [comment]
Closing as dupe
