### ISSUE TITLE
Create more holistic product publish targets in BuildTools

### ISSUE THREAD

**Issue by dagood** [dotnet/buildtools#1562]
Right now CoreFX and CoreCLR have a significant amount of inline logic in their checked-in definition steps to publish correctly. This should be handled in BuildTools, instead.

**Comment by maririos** [comment]
Issue moved to [dotnet/core-eng #1482](https://github.com/dotnet/core-eng/issues/1482) via [**ZenHub**](https://www.zenhub.com/)
