### ISSUE TITLE
Extract restored nupkg to a specified folder - a new build task request

### ISSUE THREAD

**Issue by ravimeda** [dotnet/buildtools#1565]
NuGet packages are restored by running `sync` command. To access the assemblies in a package, the .nupkg has to be expanded manually or writing additional scripts. Consider providing a build task that can extract all the restored packages to a specified folder.

A simple file extraction task is already available at (https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks/ZipFileExtractToDirectory.cs) Extend this to operate over multiple nupkgs.

A usecase for this task is security build where restored packages are extracted so that security extensions can scan the assemblies. Currently, a PowerShell script is being used to extract packages. Using a PowerShell script for now suffices since security extensions are available only for Windows. If extensions become available for non-Windows, then a shell script to extract packages needs to be prepared. Having a build task that can be used cross-plat will provide a consistent experience.

**Comment by dagood** [comment]
Since `ZipFileExtractToDirectory` is a MSBuild task, you must use it through an MSBuild target where it's easy to batch the task to run on multiple zip files. What's the benefit of making the task take multiple inputs?

**Comment by ravimeda** [comment]
Yes, that is true.

Please allow me to clarify the motivation behind logging this issue.  I'm trying to highlight the experience in retrieving official build bits. Currently, `sync` only gets the packages corresponding to the specified build. An additional step (by a developer) is needed to extract the assemblies from the packages.  I think filling that gap would offer a better experience.

**Comment by dagood** [comment]
Ok, I'd go for a new build target or a new property on the sync target, in that case.

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
