### ISSUE TITLE
Pinvoke analyser isn't handling multiple baseline files

### ISSUE THREAD

**Issue by danmoseley** [dotnet/buildtools#1571]
https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.CodeAnalysis/Analyzers/PinvokeAnalyzer.cs#L31

We expect it to potentially pick up a generic one + a target group specific one and it shouldn't ignore all but one.

**Comment by danmosemsft** [comment]
copy the other analyzers

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
