### ISSUE TITLE
Tests skip even if implementation assembly was updated

### ISSUE THREAD

**Issue by danmoseley** [dotnet/buildtools#1585]
The incrementality fix https://github.com/dotnet/buildtools/pull/1584 (so that the tests don't get triggered 100% of the time) exposes the problem that the tests aren't triggered when the product changes.

For example, `msbuild /t:test` in `System.Console\tests` will skip even if `System.Console\src` was rebuilt. The `DiscoverTestInputs` target in `tests.targets` is supposed to include `System.Console.dll` in `@(RunTestsForProjectInputs)` but it does not because it is not present in `@(ReferenceCopyLocalPaths)` because it is an implicit dependency (? I'm not sure how this works)..

@joperezr how should this correctly be fixed?

**Comment by danmosemsft** [comment]
Could be something like adding this in `<Target Name="DiscoverTestInputs"` -- but different for UAP etc.

`      <RunTestsForProjectInputs Include="$(NETCoreAppTestSharedFrameworkPath)\*"/>`

**Comment by joperezr** [comment]
cc @weshaggard

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
