### ISSUE TITLE
init-tools requires 4.5GB of disk space

### ISSUE THREAD

**Issue by jkotas** [dotnet/buildtools#1586]
The total size of `tools\*` and `packages\*` after running `init-tools.cmd` on Windows is 4.5GB. Can we trim this down?

There are many Unix packages under packages. They should not be needed on Windows.

**Comment by weshaggard** [comment]
I recently fixed the fact that it downloads the shared framework for all RID's on each platform with https://github.com/dotnet/buildtools/pull/1577. It would be worth updating build tools to see how much that helps. 

That said I'm sure there is still plenty of room to optimized more stuff here and we should.

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
