### ISSUE TITLE
Auto-upgrade feature: wait for packages to be available on MyGet before creating PR

### ISSUE THREAD

**Issue by dagood** [dotnet/buildtools#1593]
This would let us reduce the constant delay from 10 minutes to something much lower, improving auto-update PR turnaround in the best case. The worst case also improves, because we can wait longer than 10 minutes if necessary.

We need to consider the desired behavior if the packages never become available. I think it makes sense to create the PR anyway, and warn anyone looking at the PR's CI by describing the situation in a comment. This lets users retry the CI to get the PR through, even when indexing takes much longer than normal.

To implement this, we can use http://docs.myget.org/docs/reference/feed-state-api-endpoint to poll until the packages are available/indexed.

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
