### ISSUE TITLE
As a dev, restoring packages always uses NuGet.Config, not "--source" parameters in command line builds

### ISSUE THREAD

**Issue by Chrisboh** [dotnet/buildtools#1597]
@dagood commented on [Wed Nov 09 2016](https://github.com/dotnet/core-eng/issues/109)

Right now there is duplication: VS requires a NuGet.Config, but in command-line builds we use `--source ...` parameters for `dotnet restore`. Unless there's been a regression, we should be able to use `--configfile` to use the same NuGet.Config in both scenarios.

This also opens the door to restore packages from VSTS feeds, because NuGet.Config is compatible with authenticated sources. (`--source ...` doesn't work with auth, and NuGet doesn't want to fix this.)

---

@Chrisboh commented on [Fri Jan 06 2017](https://github.com/dotnet/core-eng/issues/109#issuecomment-270974602)

coordinate with the work @ellismg is doing for build from source.

---

@ellismg commented on [Fri Jan 06 2017](https://github.com/dotnet/core-eng/issues/109#issuecomment-270980819)

This is a nice to have for the build from source work.  It makes changing the sources when building CoreFX (e.g. to augment the package source list to include a private on disk source that contains a freshly built CoreCLR) easier.  We can always work around it by having a custom task that just edit's the .props file where stuff is defined, so it's not blocking any progress.

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
