### ISSUE TITLE
Symbol signing should be refactored

### ISSUE THREAD

**Issue by crummel** [dotnet/buildtools#1598]
Symbol signing depends on some scripts from PipeBuild right now, so if you want to add symbol signing to a build you need to clone the PipeBuild repo as well.  Ideally symbol signing could be one all-inclusive package with just what you need and nothing extra.

**Comment by dagood** [comment]
https://github.com/dotnet/symstore/pull/37 (merged) helps us get here by making the EmbedIndex package and its dependencies into libraries that we can consume and redist in BuildTools.

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
