### ISSUE TITLE
Code Coverage doesn't work if you pass a different-case path to msbuild

### ISSUE THREAD

**Issue by mellinoe** [dotnet/buildtools#1604]
For example, if you run this command:

`msbuild src\system.drawing.common\tests\System.Drawing.Common.Tests.csproj /t:rebuildandtest /p:coverage=true`

the code coverage targets will incorrectly think the name of the assembly being tested is 
"system.drawing.common" instead of "System.Drawing.Common". The tests will still run, but no data is gathered, because the assembly name doesn't match correctly.

We should be able to do some path normalization in this section: https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks/PackageFiles/CodeCoverage.targets#L28-L30

When the above command is given, `$(MSBuildProjectDirectory)` does not match the canonical representation on disk. We should normalize that before we use it to determine `AssemblyBeingTestedName`.

As a workaround, you can just type the path with the correct casing 😄 .

**Comment by maririos** [comment]
per @dleeapho suggesitons we are going to close this issue

**Comment by mellinoe** [comment]
@maririos Did you close the wrong issue?

**Comment by dleeapho** [comment]
@mellinoe , we closed this during triage on the basis that normally inputs would be normalized, hence it wasn't worth fixing. Perhaps this was an incorrect assumption?

**Comment by mellinoe** [comment]
@dleeapho I don't follow -- how are the inputs normalized?

**Comment by dleeapho** [comment]
Sync'd with @mellinoe, this is a minor issue. Does not meet the bar.
