### ISSUE TITLE
Support Portable PDB to Windows PDB conversion on .NET Core

### ISSUE THREAD

**Issue by dagood** [dotnet/buildtools#1607]
https://github.com/dotnet/buildtools/pull/1605 adds the ability to create a derived Windows PDB, and uses it during the symbol archive flow. As of that PR, .NET Core support wasn't needed, and the required workaround wasn't worthwhile.

> Currently I chose not to support this task on .NET Core. The task does compile and ship on Core, and when the dependencies are present, it works fine. But there was no clear way to gather and pack up all the dependencies needed, and full desktop framework is the only scenario. There isn't a whole lot to figure out (or work around) if it's useful to support Core in the future.

**Comment by ctaggart** [comment]
Have a look at https://github.com/dotnet/symreader-converter

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
