### ISSUE TITLE
Remove DiaSymReader runtime binplace workaround

### ISSUE THREAD

**Issue by dagood** [dotnet/buildtools#1608]
https://github.com/dotnet/buildtools/pull/1605 uses `PrereleaseResolveNuGetPackageAssets` during `AfterBuild` to manually grab and binplace some runtime dependencies. We should remove this workaround.

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
