### ISSUE TITLE
Provide a script to retry a build command.

### ISSUE THREAD

**Issue by ravimeda** [dotnet/buildtools#1640]
Build command that involves a network operation such as `git clone` can fail due to network issue. For example https://github.com/dotnet/core-eng/issues/1505.  Such tasks need to be retried.
Provide a script that can wait-retry a given command.

**Comment by smile21prc** [comment]
Merged the fix in  https://github.com/dotnet/coreclr/commit/66d0fed853589e19336b6486f05f9218019ca4c9, and kicked off Pipebuild https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=934009&_a=summary for verification.

**Comment by smile21prc** [comment]
Verified this is fixed in coreclr master and release/2.0.0.
