### ISSUE TITLE
Missing license headers in some python files

### ISSUE THREAD

**Issue by omajid** [dotnet/buildtools#1641]
Most of the files under https://github.com/dotnet/buildtools/tree/master/src/Microsoft.DotNet.Build.CloudTestTasks/RunnerScripts/xunitrunner-perf are missing a license header. Is it safe to assume that they are under MIT?

cc @leecow

**Comment by omajid** [comment]
Also affects files under https://github.com/dotnet/buildtools/tree/master/src/Microsoft.DotNet.Build.CloudTestTasks/RunnerScripts/scriptrunner

**Comment by omajid** [comment]
Also affects https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.CloudTestTasks/RunnerScripts/xunitrunner-func/xunitrunner-func.py

**Comment by maririos** [comment]
@MattGal could you please take a look at this?

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
