### ISSUE TITLE
Add parallel requests to DownloadFromAzure

### ISSUE THREAD

**Issue by dagood** [dotnet/buildtools#1646]
The `DownloadFromAzure` task sequentially downloads files:

https://github.com/dotnet/buildtools/blob/3df4ae209338fc74e29c2395d808a74b9612f0fd/src/Microsoft.DotNet.Build.CloudTestTasks/DownloadFromAzure.cs#L82-L83

I ran into download time problems with a different copy of the `DownloadFromAzure` code, and adding parallel requests reduced total time to ~3% of what it was.

This should have a very large impact on build turnaround: right now, CoreCLR must download packages from intermediate storage in order to publish all build legs together, and the download takes over an hour. This change can reduce the download to 2 minutes.

**Comment by maririos** [comment]
It might be covered by transport feeds. Be careful with timeouts though...

**Comment by weshaggard** [comment]
+1 on fixing this as we are spending too much time downloading stuff in our builds which we can improve a lot.

**Comment by dagood** [comment]
About transport feeds: I don't think they affect this. The primary `DownloadFromAzure` use case I'm aware of is during the publishing leg: it has to download all packages built on all legs for that single build without knowing which packages were built. NuGet can't be used for that unless we had the list stored somewhere else.

**Comment by weshaggard** [comment]
I agree this is independent and we should still do this work. From my recent build work I've seen the download time anywhere from 8-20 minutes to pull down the contents of the container which is quite slow.

**Comment by Chrisboh** [comment]
I have asked @riarenas to take a stab at this issue.

**Comment by Chrisboh** [comment]
It looks like @karajas has already done this.  #1793 

Closing.
