### ISSUE TITLE
default RUNTIME_PATH for RunTests.sh

### ISSUE THREAD

**Issue by wfurt** [dotnet/buildtools#1662]
I was trying to run 
/Users/furt/github/corefx/bin/Unix.AnyCPU.Debug/System.IO.Pipes.Tests/netstandard/RunTests.sh
error: RUNTIME_PATH is not defined. Usage: /Users/furt/github/corefx/bin/Unix.AnyCPU.Debug/System.IO.Pipes.Tests/netstandard/RunTests.sh RUNTIME_PATH

This is something I talk about with @weshaggard : It would be nice if the script is runable directly and defaults RUNTIME_PATH to something reasonable.

RUNTIME_PATH=/XXXX
if [ "$1" != '' ]; then
  RUNTIME_PATH="$1"
fi
export RUNTIME_PATH=$RUNTIME_PATH

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
