### ISSUE TITLE
[To-Do] Remove workaround in init-tools that is renaming the compilers to have a .exe extension

### ISSUE THREAD

**Issue by joperezr** [dotnet/buildtools#1669]
In our repos we use a custom task library in order to launch the compilers, and this task will try to find them like: `csc.exe` and `vbc.exe` in order to spawn them. The problem is that newer versions of roslyn have changed the extension of the compilers to be `csc.dll` and `vbc.dll` instead. This causes the custom task library to not be able to find them anymore. As a workaround, PR #1661 added a line in init-tools that would rename the extension which will make it all work, but this issue is to track the work of removing that workaround and instead use the real task library.

**Comment by joperezr** [comment]
Note that we will soon move to using the msbuild that comes with the CLI for non-Windows, which will get rid of this problem, since we wouldn't have to construct all of msbuild our selves.

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
