### ISSUE TITLE
The 'dotnet/buildtools' repo does not build on Debian 9 Stretch

### ISSUE THREAD

**Issue by johnbeisner** [dotnet/buildtools#1675]
_From @bazzilic on September 9, 2017 9:19_

On Debian 9 (Stretch), do

```
git clone https://github.com/dotnet/buildtools.git
cd buildtools
./build.sh
```

It will fail due to inability to detect an OS while executing a script from this repository located at `scripts/obtain/dotnet-install.sh`.

After taking a closer look at the script, it is clear that this function does not detect Debian 9: https://github.com/dotnet/cli/blob/8e756edce1573c30c0c5a0708ff323dda0f673fc/scripts/obtain/dotnet-install.sh#L58-L109

_Copied from original issue: dotnet/cli#7622_

**Comment by johnbeisner** [comment]
_From @livarcocc on September 10, 2017 2:27_

@johnbeisner please, take a look.

**Comment by johnbeisner** [comment]
@bazzilic 
It appears that you are using an old version of dotnet-install.sh - please use the version at: https://dot.net  [specifically: https://dot.net/v1/dotnet-install.sh]

**Comment by johnbeisner** [comment]
_From @bazzilic on September 12, 2017 2:8_

How could a script in master branch be outdated? And why do other dotnet projects use the outdated script then?

**Comment by johnbeisner** [comment]
_From @bazzilic on September 12, 2017 2:13_

Btw, the script you linked to has exactly same issue of not detecting Debian 9.

**Comment by johnbeisner** [comment]
@bazzilic
Looking into this further I can state a few more facts:
1. The dotnet/buildtools build is downloading a "1.0.0-preview2-1-003182" version of the SDK
2. In any version of the script we do not detect Debian 9 because in the 1.0 and 1.1 releases we did not publish Debian 9 specific packages. The list of platforms is finite and targeted.
3. Moving forward, we support Debian 9 with generic Linux portable packages - unfortunately that does not solve your current problem.

I cannot see a method to build the dotnet/buildtools repo on Debian 9 at this time.
I will move this issue into dotnet/buildtools backlog to see if they can solve this.

**Comment by omajid** [comment]
The latest version of `dotnet-install.sh` is normally in the master branch of `dotnet/cli`. 

- Maybe some automated script can go and sync every repo where this is duplicated?
- Maybe we should tell developers to use the version from `dotnet/cli`?

**Comment by johnbeisner** [comment]
This is not an install-script problem - it is a dotnet/buildtools build problem.
One way to resolve the problem is to move your SDK installation forward - install 2.0 instead of a preview version of 1.0

**Comment by omajid** [comment]
The latest version of `dotnet-install.sh` is normally in the master branch of `dotnet/cli`. 

- ~~Maybe some automated script can go and sync every repo where this is duplicated?~~ Edit. Scratch that. `bootstrap.sh` downloads its:  https://github.com/dotnet/buildtools/blob/master/bootstrap/bootstrap.sh#L180

- ~~Maybe we should tell developers to use the version from `dotnet/cli`?~~ Maybe bootstrap.sh could always download `dotnet-install.sh` from cli's `master` branch rather than from the older branch?

**Comment by johnbeisner** [comment]
To reiterate:
This is not an install-script problem - it is a dotnet/buildtools build problem.

In any version of the script that exists, it is not possible to install any version of 1.0 on Debian 9

**Comment by bazzilic** [comment]
@johnbeisner however, I am still looking at the latest version of the script in `master` (https://github.com/dotnet/cli/blob/master/scripts/obtain/dotnet-install.sh) and it still doesn't seem to detect Debian 9 (I also foresee issues with Alpine, as the current version is 3.6.*).

@omajid buildtools could also detect if there already _is_ SDK installed and not install it in that case.

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
