### ISSUE TITLE
Release Microsoft.DotNet.BuildTools-1.0.16-prerelease on GitHub

### ISSUE THREAD

**Issue by ghost** [dotnet/buildtools#169]
Please release Microsoft.DotNet.BuildTools-1.0.16-prerelease on GitHub. Currently it is available on Nuget.org: http://nuget.org/packages/Microsoft.DotNet.BuildTools, but not in GitHub releases: https://github.com/dotnet/buildtools/releases.
Thanks.

**Comment by weshaggard** [comment]
@jasonwilliams200OK, may I ask why you are wanting that? We have many release post 16 that we have only been publishing to our myget feed.

**Comment by jasonwilliams200OK** [comment]
Mostly for the GH repository watchers who are interested in semver'd / tagged releases.
And why not, I mean it is just a matter of pushing `git tag 1.0.1.6-prerelease && git push --tags` and selecting the tag for release: https://github.com/dotnet/buildtools/releases/new.

**Comment by weshaggard** [comment]
@jhendrixMSFT Is this something on your radar as part of our release process?

**Comment by jhendrixMSFT** [comment]
I've added it to the list, thanks for bringing this to my attention.

**Comment by MichaelSimons** [comment]
Triage: old release. No longer applicable.
