### ISSUE TITLE
Remove workaround that copies RID specific assets when initializing buildtools in non-Windows

### ISSUE THREAD

**Issue by joperezr** [dotnet/buildtools#1697]
On PR #1687 we had to make a workaround that manually copied a few assets that were getting published to RID specific locations into the tools directory when running init-tools on non-Windows. This issue is to track the work of removing that workaround, and instead trying publishing the tool runtime to the right RID so this is won't be required.

Workaround is here: https://github.com/dotnet/buildtools/pull/1687/files#diff-519820c77125188495c6a22d71f859ceR112

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
