### ISSUE TITLE
run.exe should default {OSRid} to win10 when on a win10 machine

### ISSUE THREAD

**Issue by eerhardt** [dotnet/buildtools#1714]
When building on a win10 machine, the `{OSRid}` parameter in config.json files should be `win10` instead of `win7`.

https://github.com/dotnet/buildtools/blob/78260239e4db68ad5c2df774a27d5f9a54fd92e5/src/Run/SettingValueProvider.cs#L24

When building non-portable assets on Windows (like we do in `source-build`), we are producing `runtime.win10` packages when building on `win10`.  Then later when we want to consume those packages from a higher repo (like core-setup), `run.exe` is setting the repo's `OSRid` to `win7`.  So when we are restoring the packages, it is trying to find `runtime.win7` or `runtime.win` packages, but they haven't been created.  Only `runtime.win10` packages have been created.

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
