### ISSUE TITLE
Set checksum algorithm using csc task parameter instead of response file

### ISSUE THREAD

**Issue by joperezr** [dotnet/buildtools#1726]
Before, the csc msbuild task didn't support passing in a checksum algorithm as a parameter, so currently we are passing a response file that would set the algorithm. This may cause problems since VS won't pass in response files when building, so it could lead to having to different outputs whether you build in VS or if you don't. We should instead move and use the MSBuild task parameter to set the checksum property to fix this.

cc: @weshaggard

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
