### ISSUE TITLE
MS.DotNet.Build.Tasks.dll references MSBuild 4.0, causing Mono's implementation to be loaded when building corefx

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/buildtools#173]
I just tried building corefx with the new Mono 4.0.1SR1 (it backports a fix that made us require >= Mono 4.1). However, it now complains about not having `StandardOutputImportance` parameter for a Task when building the tests, which is odd because we're using the open-sourced MSBuild which has those (Mono has them too on >= 4.1).

From my observation the issue is that the custom task project in this repo references [Microsoft.Build.Tasks.v4.0](https://github.com/dotnet/buildtools/blob/a6e01c871a35fe3b36b7a8225ded215fdb2ade75/src/Microsoft.DotNet.Build.Tasks/Microsoft.DotNet.Build.Tasks.csproj#L42) and [Microsoft.Build.Utilities.v4.0](https://github.com/dotnet/buildtools/blob/a6e01c871a35fe3b36b7a8225ded215fdb2ade75/src/Microsoft.DotNet.Build.Tasks/Microsoft.DotNet.Build.Tasks.csproj#L49), which isn't there in the open-sourced MSBuild and thus Mono tries in it's GAC and finds Mono's implementation of the assemblies which don't have the required parameter.

While it doesn't cause problems on Mono >= 4.1 right now since it has an implementation for the missing parameter (I actually added it a while back when trying to build corefx with xbuild), this is probably something that should be fixed so it loads the MSBuild 14 assemblies instead. I can see this being very confusing otherwise down the road ;)

/cc @JeremyKuhne

**Comment by weshaggard** [comment]
Triage: Mono is no longer an interesting target for BuildTools not that we have it running in .NET Core.
