### ISSUE TITLE
Need to port release/2.0 changes to master

### ISSUE THREAD

**Issue by eerhardt** [dotnet/buildtools#1730]
We made https://github.com/dotnet/buildtools/pull/1707 in just the release/2.0.0 branch.

This is to track getting these same changes ported to master, so repos that use buildtools can use these changes in master as well.

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
