### ISSUE TITLE
Figure out/clarify mirroring process for packages the BuildTools build depends on

### ISSUE THREAD

**Issue by dagood** [dotnet/buildtools#1760]
Right now, BuildTools master is configured with a few feeds we don't control:

https://github.com/dotnet/buildtools/blob/b68dbb06bb69535f849770c4487afe8ed6e8777c/dir.props#L89-L92

To be sure old BuildTools builds won't break if one of those feeds removes a package, we typically mirror them to the `dotnet-buildtools` feed. As things are currently, there is no way for a dev to know that these packages should be mirrored: simply upgrading package versions works because the feeds are configured, and if we removed the feeds to only depend on mirrored packages, the feeds would probably just be added back eventually.

We should figure out our strategy, and how to make it discoverable.

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
