### ISSUE TITLE
Microsoft.CCI dependency needs to be able to build from source

### ISSUE THREAD

**Issue by weshaggard** [dotnet/buildtools#1762]
A lot of our tools in this repo depend on Microsoft.CCI which currently isn't fully open. We depend on a package we built internally. The source has been opened at https://github.com/microsoft/cci but that doesn't have a package build currently nor does it fully support an official build. We will need to do that in order to fully build BuildTools from source.

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
