### ISSUE TITLE
Problem with baselining ApiCompat error 

### ISSUE THREAD

**Issue by maryamariyan** [dotnet/buildtools#1784]
In corefx, System.ComponentModel.Composition project had to skip running apicompat in order to skip the following error:

```
ApiCompat Error: 0 : Unable to resolve assembly 'Assembly(Name=System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)' referenced by the contract assembly 'Microsoft.Cci.DummyModule'.
```

When using the msbuild option /p:BaselineAllAPICompatError the src project of System.ComponentModel.Composition succeeds. 
But even when the apicompat txt file exists and without the above baseline option the build will fail.

Note: After this issue gets fixed we'll need to enable running apicompat again on System.ComponentModel.Composition

cc: @weshaggard @danmosemsft

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
