### ISSUE TITLE
Support running MSBuild on .NET Core on Windows

### ISSUE THREAD

**Issue by dagood** [dotnet/buildtools#1811]
We need to port this line to init-tools.cmd:

https://github.com/dotnet/buildtools/blob/eb41c61550c769023ba1e946ca819cdf007d5a20/src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.sh#L88-L89

Then users can run `.\Tools\dotnetcli\dotnet.exe .\Tools\MSBuild.dll`.

We should also consider also providing a script like `msbuild.cmd` but using the CLI to make usage cleaner.

This is useful to run any tooling that only works on the Core runtime on Windows.

**Comment by weshaggard** [comment]
@Chrisboh is this covered by another issue? As I think we should still do this.

**Comment by dagood** [comment]
I didn't know a concrete valuable scenario for this in triage. The symbol tooling was the only thing I knew of that only works on the Core runtime, but it turned out that's supposed to run on Desktop as well.

I think I made a mistake by including the "We should also consider" part... losing the ability to run `.\Tools\dotnetcli\dotnet.exe .\Tools\MSBuild.dll` is itself a regression that should maybe be fixed just because of that.

In the mail thread this came from, you mentioned @joperezr is working on this scenario as part of the effort to remove msbuild from BuildTools, but it sounds like a larger effort than porting that init-tools line. Is that tracked anywhere, or should this issue be edited into shape and used to track it?

**Comment by weshaggard** [comment]
I guess I read the title and though this was a bigger issue. As for the issue of removing msbuild.dll it is tracked by https://github.com/dotnet/buildtools/issues/1458. I'm fine with closing this issue but sometimes it might be helpful to add a note about why we are closing things in triage.

**Comment by dagood** [comment]
That's a good point, the close looks like "we won't support running MSBuild on Core on Windows" from the title, but it's really about this specific way of supporting it and that helper script. Thanks for the link.
