### ISSUE TITLE
Reimplement Azure tasks using official Azure API NuGet packages

### ISSUE THREAD

**Issue by dagood** [dotnet/buildtools#1816]
Currently we have custom implementations using the REST API: https://github.com/dotnet/buildtools/blob/f3694f40462f458f9253a3df6d333cdcfd6e17b1/src/Microsoft.DotNet.Build.CloudTestTasks/DownloadFromAzure.cs

Moving to the official .NET client could make our downloads/uploads more reliable and faster, and it would give us less to maintain.

/cc @MattGal

**Comment by weshaggard** [comment]
I like the idea but we need to be sure we can build the dependency from source.

**Comment by weshaggard** [comment]
See comments on https://github.com/dotnet/buildtools/pull/1814, and we should widen this to include the other Azure tasks like UploadtoAzure as well.

**Comment by jcagme** [comment]
Tracking issue on the engineering side: https://github.com/dotnet/core-eng/issues/2152

**Comment by MattGal** [comment]
Given it's all on Github build from source is feasible https://github.com/Azure/azure-storage-net , I'm curious if there's any specific test for whether a repo meets our build-from-source needs though.

**Comment by dagood** [comment]
I haven't seen a comprehensive list (would be nice to have a pointer to something like this from the source-build readme). A few big points:

 * Must be buildable on the target platform (Linux)
 * Dependencies must also be built/buildable from source (no prebuilt binaries)

It helps if the repo can do all that without any patches, too, so it's easier for source-build to uptake fixes.

We can prune out dependencies that source-build doesn't actually use, but this list is pretty scary: https://github.com/Azure/azure-storage-net#dependencies

**Comment by jaredpar** [comment]
Why are we considering build from source here? There is 0 use of azure in a build from source scenario hence our use of azure is immaterial. The code here is not a part of our shipping product but rather an implementation detail of how we construct it. It doesn't impact source build. 

The code which depends on this should simply be excluded from the build.

**Comment by weshaggard** [comment]
@jaredpar as I called out in my other comment in #1814 we either need to do work to break this dependency out or support it either way we need to do work. Also if we ever expect to use source-build to build our official builds we will still be publishing to Azure blobs so it will need to be present there as well.

**Comment by jaredpar** [comment]
> we either need to do work to break this dependency 

Then lets do that work. Can't let buildtools hold back the reliability of our orchestrated builds. 

> Also if we ever expect to use source-build to build our official builds we will still be publishing to Azure blobs so it will need to be present there as well.

That is a non-goal and provides no value to our official builds. What good is building the azure .NET SDK from source when we will never depend on the output for an official build?

**Comment by weshaggard** [comment]
@jaredpar we are planning to take the dependency on the Azure SDK, no one is saying differently here. We are simply calling out there is work that needs to be done to deal with the new dependency. 

>That is a non-goal

It might be currently but it has been brought up numerous times.

**Comment by jaredpar** [comment]
> It might be currently but it has been brought up numerous times.

I think it's brought up under the assumption that we still automatically roll forward all our version dependencies. That is no the plan for source build anymore. Lacking auto-roll forward there is no real benefit in doing this.

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
