### ISSUE TITLE
Copying of test assets should resolve to highest package version.

### ISSUE THREAD

**Issue by nguerrera** [dotnet/buildtools#182]
Currently, in the CopyTestsToTestDirectories target, we sometimes end up with the same dll from different package versions (I believe this happens when product dependencies outpace the coreclr/buildtool package dependencies but I did not confirm). Right now,  we just arbitrarily copy the last one in the list over the previous ones with the same file name. In addition to not being very well defined, it breaks SkipCopyUnchnagedFiles.

**Comment by nguerrera** [comment]
I'm making a tactical fix for the SkipCopyUnchangedFiles issues, but the root issue will still need to be addressed.

**Comment by MichaelSimons** [comment]
Triage: no longer applicable.
