### ISSUE TITLE
Problem building the build-managed.sh for an x86 CoreFX Linux build

### ISSUE THREAD

**Issue by philippweidhas** [dotnet/buildtools#1820]
Hallo Github Community,

im facing following problems building the build-managed.sh for an corefx x86 build:
```
/home/arbeit/Tools/depProj.targets(83,5): error : Error no assets were resolved from NuGet packages. [/home/arbeit/corefx/external/netstandard/netstandard.depproj]
/home/arbeit/Tools/depProj.targets(83,5): error : Error no assets were resolved from NuGet packages. [/home/arbeit/corefx/external/docs/docs.depproj]
/home/arbeit/Tools/depProj.targets(83,5): error : Error no assets were resolved from NuGet packages. [/home/arbeit/corefx/external/ILLink/ILLink.depproj]
```
I was following these steps:

```
git clone https://github.com/dotnet/corefx.git
cd corefx
sudo ./cross/build-rootfs.sh x86

./build-native.sh -debug -- clang3.8
./build-native.sh -debug -buildArch=x86 -- cross clang3.8
./build-managed.sh -BuildTests=false
```
The build-native.sh builds working fine, but the managed build not. I also tried -release instead of -debug.

I found [these  issue with a workaround](https://github.com/dotnet/corefx/issues/15274) from @joperezr  but i have no 
src/Tools/CoreFx.Tools/CoreFx.Tools.csproj.

Can someone help me with that problems?

Greetings

Philipp.

**Comment by joperezr** [comment]
Sounds to me that you are missing some dependencies for the managed build. You can find more details on the dependencies for that here: https://github.com/dotnet/corefx/blob/master/Documentation/building/unix-instructions.md

Which distro are you using?

> I found these issue with a workaround from @joperezr Jose Perez Rodriguez FTE but i have no
src/Tools/CoreFx.Tools/CoreFx.Tools.csproj.

That was some time ago, and those tools where refactored, but as I said I believe your issue is more of a missing dependency. 

I'll close this issue for now but feel free to reopen it if you don't find the requirements for your distro so we can help you out.

**Comment by philippweidhas** [comment]
Hi @joperezr, 
thank you for your quick answer.
Im Using Ubuntu 17.04 for my build.
I looked up that guide and the only thing different is that i was using clang3.8 not 3.9. 

sudo apt-get install git clang-3.9 cmake make libc6-dev libssl-dev libkrb5-dev libcurl4-openssl-dev zlib1g-dev
[sudo] password for arbeit: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
cmake is already the newest version (3.7.2-1).
make is already the newest version (4.1-9.1).
zlib1g-dev is already the newest version (1:1.2.11.dfsg-0ubuntu1).
clang-3.9 is already the newest version (1:3.9.1-5ubuntu1.1).
git is already the newest version (1:2.11.0-2ubuntu0.3).
libc6-dev is already the newest version (2.24-9ubuntu2.2).
libcurl4-openssl-dev is already the newest version (7.52.1-4ubuntu1.3).
libkrb5-dev is already the newest version (1.15-1ubuntu0.1).
libssl-dev is already the newest version (1.0.2g-1ubuntu11.3).
The following packages were automatically installed and are no longer required:
  linux-headers-4.10.0-19 linux-headers-4.10.0-19-generic
  linux-image-4.10.0-19-generic linux-image-extra-4.10.0-19-generic
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 137 not upgraded.


 sudo apt-get install libunwind8 libicu57 curl 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libunwind8 is already the newest version (1.1-4.1ubuntu2).
curl is already the newest version (7.52.1-4ubuntu1.3).
libicu57 is already the newest version (57.1-5ubuntu0.2).
The following packages were automatically installed and are no longer required:
  linux-headers-4.10.0-19 linux-headers-4.10.0-19-generic
  linux-image-4.10.0-19-generic linux-image-extra-4.10.0-19-generic
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 137 not upgraded.


Actually i get this 3 Errors
/home/arbeit/Tools/depProj.targets(83,5): error : Error no assets were resolved from NuGet packages. [/home/arbeit/corefx/external/netstandard/netstandard.depproj]
/home/arbeit/Tools/depProj.targets(83,5): error : Error no assets were resolved from NuGet packages. [/home/arbeit/corefx/external/docs/docs.depproj]
/home/arbeit/Tools/depProj.targets(83,5): error : Error no assets were resolved from NuGet packages. [/home/arbeit/corefx/external/ILLink/ILLink.depproj]
    94 Warning(s)
    3 Error(s)

Any other ideas how i can solve this problem?

**Comment by joperezr** [comment]
Our builds run against 14.04 so I would recommend switching to that if possible, but if not, here is what we have as a list of dependencies for 17.04:

```
        clang-3.9
        cmake
        liblldb-3.9-dev
        lldb-3.9
        llvm-3.9
        make
        git
        nodejs
        nodejs-legacy
        npm
        tar
        zip
        gettext
        libcurl4-openssl-dev
        libgdiplus
        libicu-dev
        libkrb5-dev
        liblttng-ust-dev
        libssl-dev
        libunwind8
        libunwind8-dev
        uuid-dev
```

**Comment by philippweidhas** [comment]
Thanks for your quick Answer again.
I will try it with this dependencies and if im not succesful i will try 14.04.
I will give you feedback later.

**Comment by wfurt** [comment]
We do not cross-compile for 32bit right @joperezr I would think this may be more related to cross compilation than particular OS version. 

I would also strongly recommend cleanup between tries @philippweidhas (unless you already do)

**Comment by philippweidhas** [comment]
@wfurt could you please tell me a quick way to cleanup. At the moment i made a snapshot for an vm running ubuntu and i can start restart the complete ubuntu at its pre try status. Not the best way...

**Comment by wfurt** [comment]
you can always do git clean -dfx. That will remove all files unknown to git. 
That will also remove Tools
I often do just "rm -rf bin packages" from the root directory.

**Comment by philippweidhas** [comment]
Thank you for all your help. With Ubuntu17.04, the dependencies, cleanup the same error occurs. Can i install this dependencies manually or prepare them with an x64 .net Core Build.
Now i will try the Ubuntu 14.04 Build. If someone of you has any other idea im very thankful for all.

**Comment by joperezr** [comment]
Can you try just running `build.sh`? @wfurt brought up a good point which is that corefx build currently is only supported for x64 in non-Windows OSes.

**Comment by philippweidhas** [comment]
I will try that build.sh as soon as possible. I now that its not supported but i found some people working on this in the github forum. But they dont got that problems crosscompiling for x86 Linux. So im looking for the solution for the errors.
