### ISSUE TITLE
PublishOutputLeg target doesn't exst

### ISSUE THREAD

**Issue by mmitche** [dotnet/buildtools#1822]
From https://github.com/dotnet/buildtools/blob/280705d9d12af2fe0997509474825d2c9cbe7932/src/Microsoft.DotNet.Build.Tasks.Feed/PackageFiles/Microsoft.DotNet.Build.Tasks.Feed.targets#L1

This shouldn't set the default target

**Comment by weshaggard** [comment]
Agreed.

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
