### ISSUE TITLE
Configurable init-tools restore: enable/disable certain packages

### ISSUE THREAD

**Issue by dagood** [dotnet/buildtools#1824]
We should support turning off certain packages when they can't be used for some reason, e.g. source-build. Devs may also want to skip some to speed up init-tools time. The main BuildTools package has not been split yet, but there is a Feed Tasks package and Symbol Publisher package already. 

The init-tools.msbuild should be configurable somehow:
https://github.com/dotnet/core-setup/blob/edce50fc0abd3f5ed8db17897427e2d4b5d81ddf/init-tools.msbuild

This could be a step towards selectively restoring BuildTools packages needed by a repo.

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
