### ISSUE TITLE
Add support for signing .NuPkgs to existing BuildTools workflow

### ISSUE THREAD

**Issue by MattGal** [dotnet/buildtools#1826]
Currently, files which require signing

- Product assemblies pick up a default props file which specifies an AssemblyKey property.  This can be customized [like this](https://github.com/dotnet/corefx/blob/45d30e6bdf44d4a0e55df5a6064e8275cdf14d25/src/System.IO.Pipes.AccessControl/dir.props#L6) to specify different keys (PRSS / Microbuild must know these key monikers)
- A task named ReadSigningRequired figures out all assemblies built by all CoreFX projects which expect to be signed and the key they will use. 
- A task named WriteSigningRequired places marker files adjacent to all assemblies we want to sign.
- All the files with an adjacent marker are discovered into an ITaskItem group. 
- Microbuild signing tasks are invoked on this group of items.

Now, we will need to do the same thing for nupkgs.  Potentially, we may not want to sign ALL nupkgs at once, or sign some with different keys (as the assemblies are).  So, we'll need a build-tools friendly way for a repo to specify:

- Store value of desired assembly key name somewhere relevant.  An obvious place is inside the [pkgproj files](https://github.com/dotnet/corefx/blob/master/src/Microsoft.CSharp/pkg/Microsoft.CSharp.pkgproj).  
- Make sure ReadSigningRequired can traverse these and produce the signing required files adjacent to nupkgs.
- submit these to microbuild AFTER all other signing and packaging work happens.

**Comment by weshaggard** [comment]
>Store value of desired assembly key name somewhere relevant. An obvious place is inside the pkgproj files.

I wouldn't expect an assembly key, just a cert which I hope we can default to the same for all packages. So I would suggest we just start dropping the requires_signing files for the pkgproj's but nothing else needs to change.

**Comment by MattGal** [comment]
I was mostly referencing what we use for Assemblies, ```<AssemblyKey>```.   

Are there any circumstances we'd not want to sign something that has a pkgproj in a repo?  It may not even need to be configurable if there's no case we wouldn't.

**Comment by weshaggard** [comment]
Not sure but if there are cases then that project should opt-out of signing via setting a property.

**Comment by morganbr** [comment]
PRSS is now able to sign packages and NuGet will require signatures starting on 5/15.

**Comment by MattGal** [comment]
Technically that's ESRP, PRSS will never sign NuPKgs.

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
