### ISSUE TITLE
Move "GenerateReferenceSource" target into buildtools

### ISSUE THREAD

**Issue by weshaggard** [dotnet/buildtools#1833]
@mellinoe commented on [Wed May 24 2017](https://github.com/dotnet/corefx/issues/20258)

We should move this new target into buildtools if we decide that the functionality is general-purpose enough to warrant it. This might involve cleaning it up, making it "automatic", and fixing some of the problems around multiple build configurations.

**Comment by weshaggard** [comment]
This would be nice to include with the genapi package.

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
