### ISSUE TITLE
Make new VersionTools tests run during build/CI

### ISSUE THREAD

**Issue by dagood** [dotnet/buildtools#1839]
While working on orchestration, I added a `Microsoft.DotNet.VersionTools.Tests` project. It uses the new simplified MSBuild project style, so I only run it in Visual Studio right now. It doesn't run in CI or command line builds. We need to either:

 1. Convert the project to the old test project style.
    * I tried this briefly without much success. I managed to make it work at one point in command-line builds on Windows, but with an intensely degraded dev flow in VS--not what I want when working on time-sensitive orchestration features.
 2. Upgrade BuildTools' CLI to support running the new test project style.

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
