### ISSUE TITLE
Teach genapi and apicompat about tuple syntax

### ISSUE THREAD

**Issue by weshaggard** [dotnet/buildtools#1850]
tuple arguments/returns: (int My1, int My2) MyMethod()

We should update the CSharp writer in CCI Extensions to understand tuple syntax. We should also update apicompat to validate parameter names for tuples with names.

**Comment by natemcmaster** [comment]
Just FYI - we'll need this in aspnet soon so we can start generating ref assemblies.

**Comment by weshaggard** [comment]
@natemcmaster just to set context I don't think this is currently on our radar to get fixed but we do accept PR's if someone wishes to help add support.

**Comment by natemcmaster** [comment]
Good to know. I'll add this to a list of things we'll need to help fix before we can make progress on 3.0 work.

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
