### ISSUE TITLE
Create build output manifests in non-orchestrated-build scenarios

### ISSUE THREAD

**Issue by dagood** [dotnet/buildtools#1853]
https://github.com/dotnet/core-setup/pull/3572#discussion_r160189684

> [eerhardt] Would it make sense if these manifests were built during the normal build as well, not just during publish?
> 
> That way we can use it in other places - ex. source-build, or even in normal dev box scenarios.

> [dagood] It would, but the way things are factored right now this would either require some decent sized refactoring or some scenario-specific work. So that non-BuildTools repos can create manifests easily, the manifest code is in the `Feed` package and built into the `PushToBlobFeed` task. That task and the `Feed` package in general depend on some non-source-build-friendly libs.
> 
> **The refactoring way is to create a new independent MSBuild task package that is included by both main BuildTools and Feeds.** Creating these is pretty painful with the current BuildTools structure.
> 
> **Adding additional manifest tasks to the main BuildTools package would be the way to get the dev + source-build scenarios working quickly**, but that would be specific to the non-orchestrated-build scenarios so I haven't done it.

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
