### ISSUE TITLE
PushToBlobFeed error when two items have same Identity and different RelativeBlobPaths

### ISSUE THREAD

**Issue by dagood** [dotnet/buildtools#1855]
> error : Unable to upload to [...] due to System.IO.IOException: The process cannot access the file '[...]' because it is being used by another process.

The error seems to be that `PushToBlobFeed` is trying to do both uploads at the same time and the two reads collide. The scenario is the way to upload the same file to two places. In orchestrated build, aspnet uses this.

@jcagme

**Comment by jcagme** [comment]
Ack'd. I'll take a look when have some cycles off of FR

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
