### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/buildtools#1858]
Hi,

I followed the instructions in [this](https://github.com/dotnet/corefx/wiki/Build-and-run-tests) article.

After `sync`ing, running the `build` command fails with the following errors:

>
> D:\Users\Shimmy\Source\Repos\corefx\Tools\Packaging.targets(1068,5): error : Files D:\Users\Shimmy\Source\Repos\corefx\
> bin\AnyOS.AnyCPU.Debug\mscorlib\netcoreapp\mscorlib.dll and D:\Users\Shimmy\Source\Repos\corefx\bin\obj\shims\netcoreap
> p\facades\mscorlib.dll have the same TargetPath runtime.win-x64.Microsoft.Private.CoreFx.NETCoreApp/runtimes/win-x64/li
> b/netcoreapp2.1/mscorlib.dll. [D:\Users\Shimmy\Source\Repos\corefx\pkg\Microsoft.Private.CoreFx.NETCoreApp\Microsoft.Pr
> ivate.CoreFx.NETCoreApp.pkgproj]
> D:\Users\Shimmy\Source\Repos\corefx\Tools\Packaging.targets(1068,5): error : Files D:\Users\Shimmy\Source\Repos\corefx\
> bin\obj\shims\netcoreapp\facades\System.dll and D:\Users\Shimmy\Source\Repos\corefx\bin\AnyOS.AnyCPU.Debug\System\netco
> reapp\System.dll have the same TargetPath runtime.win-x64.Microsoft.Private.CoreFx.NETCoreApp/runtimes/win-x64/lib/netc
> oreapp2.1/System.dll. [D:\Users\Shimmy\Source\Repos\corefx\pkg\Microsoft.Private.CoreFx.NETCoreApp\Microsoft.Private.Co
> reFx.NETCoreApp.pkgproj]
> 
> Build FAILED.
> 
> D:\Users\Shimmy\Source\Repos\corefx\Tools\Packaging.targets(1068,5): error : Files D:\Users\Shimmy\Source\Repos\corefx\
> bin\AnyOS.AnyCPU.Debug\mscorlib\netcoreapp\mscorlib.dll and D:\Users\Shimmy\Source\Repos\corefx\bin\obj\shims\netcoreap
> p\facades\mscorlib.dll have the same TargetPath runtime.win-x64.Microsoft.Private.CoreFx.NETCoreApp/runtimes/win-x64/li
> b/netcoreapp2.1/mscorlib.dll. [D:\Users\Shimmy\Source\Repos\corefx\pkg\Microsoft.Private.CoreFx.NETCoreApp\Microsoft.Pr
> ivate.CoreFx.NETCoreApp.pkgproj]
> D:\Users\Shimmy\Source\Repos\corefx\Tools\Packaging.targets(1068,5): error : Files D:\Users\Shimmy\Source\Repos\corefx\
> bin\obj\shims\netcoreapp\facades\System.dll and D:\Users\Shimmy\Source\Repos\corefx\bin\AnyOS.AnyCPU.Debug\System\netco
> reapp\System.dll have the same TargetPath runtime.win-x64.Microsoft.Private.CoreFx.NETCoreApp/runtimes/win-x64/lib/netc
> oreapp2.1/System.dll. [D:\Users\Shimmy\Source\Repos\corefx\pkg\Microsoft.Private.CoreFx.NETCoreApp\Microsoft.Private.Co
> reFx.NETCoreApp.pkgproj]
>     0 Warning(s)
>     2 Error(s)
> 
> Time Elapsed 00:02:13.28
> Command execution failed with exit code 1.

**Comment by maririos** [comment]
Issue moved to [dotnet/corefx #26277](https://github.com/dotnet/corefx/issues/26277) via [**ZenHub**](https://www.zenhub.com/)
