### ISSUE TITLE
Deprecate/remove CreateRequest.cmd symbol archiving/indexing flow

### ISSUE THREAD

**Issue by dagood** [dotnet/buildtools#1864]
The new Microsoft.SymbolUploader.Build.Task package handles all our symbol indexing/archiving needs, using VSTS Symbol. The old flow that uses a file share and CreateRequest.cmd should be removed from BuildTools (and anywhere it's used) in favor of the new utility.

/cc @mikem8361

**Comment by mikem8361** [comment]
This new build task can also convert Portable PDBs to Window PDBs and upload them automatically.

We may want to consider not posting/archiving the symbol nuget packages to MyGet since they are only needed as a “transport” after this work is done.

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
