### ISSUE TITLE
PushToBlobFeed manifest creation should use VSTS default variables from env as a fallback

### ISSUE THREAD

**Issue by dagood** [dotnet/buildtools#1866]
For Core repos (and maybe more) these values don't match what we need, but adding this fallback would make the implementation in some places have less code. (See https://github.com/dotnet/core-eng/issues/2404#issuecomment-358389341.)

https://docs.microsoft.com/en-us/vsts/build-release/concepts/definitions/build/variables

 * `BUILD_REPOSITORY_NAME`
 * `BUILD_SOURCEVERSION`
 * `BUILD_SOURCEBRANCHNAME`
   * In my experience this has chopped off the `release` part of `release/2.0` so it might not work. `BUILD_SOURCEBRANCH` contains more info than needed but might be better.
   * (Edit) Confirmed that in a CoreCLR `release/2.0.0` build, this var is `2.0.0`. SOURCEBRANCH is `refs/heads/release/2.0.0`.
 * `BUILD_BUILDID`

/cc @tmat @tannergooding

**Comment by dagood** [comment]
> When do they not match? Alternatively, the task could read this information from the Git repo itself using LibGit2Sharp library. See e.g. https://github.com/tmat/repository-info/blob/master/src/Microsoft.Build.Tasks.Git/Implementation.cs#L60

CoreFX: [DotNet-Trusted-Publish.json#L568](https://github.com/dotnet/corefx/blob/67d240ed07342544cd5c09d1765952fe8c9d9036/buildpipeline/DotNet-Trusted-Publish.json#L568)
CoreCLR: [DotNet-Trusted-Publish.json#L752](https://github.com/dotnet/coreclr/blob/abe3c4635e2fcfcc928aa01903b873c2fca2a614/buildpipeline/DotNet-Trusted-Publish.json#L752)

Any time a "utility" repo is cloned and the product repo is cloned manually. This was originally done to get around some VSTS restrictions--in theory I think we could change this now. (I don't think making those changes is going to make it into any plan because it isn't blocking anything and it would be throwaway work.)

We actually already get the git commit via git commands during BuildTools-powered builds. We don't have a dependency on LibGit2Sharp. The hash is placed in packages, but we don't (currently) use it for the manifest. I didn't investigate this at the time and just went for the quick solution of passing in the property in the VSTS build definition.

**Comment by dagood** [comment]
There's also an overall style issue: we generally avoid depending on environment variables in the Core repo tasks/targets. (/cc @weshaggard )

That all said, this isn't hard to add. If it makes it significantly easier to onboard new builds, I think we should add it as a fallback.

**Comment by tmat** [comment]
If it'd be just a fallback then I wouldn't bother.

**Comment by weshaggard** [comment]
I do not think we should rely on env variables as that usually cause very hard to diagnose issues. Fallbacks might be OK but I wouldn't do that either unless we have a scenario and a consumer.

As for using git I'm not sure that would work in all cases either. It wouldn't really give us the branch because in most cases we are going directly to a sha instead of building a particular branch. The repo name also is hard because we need to map it to a simple name and we also cross between github and VSTS which have different repo names.

**Comment by dagood** [comment]
Thanks for the input, I'm closing this issue and we'll move forward with the explicit manifest info args.
