### ISSUE TITLE
Need a way to build (but not run) tests for a different platform.

### ISSUE THREAD

**Issue by ellismg** [dotnet/buildtools#187]
Today test build and execution are intertwined.  This means if I have tests with platform specific code (at build time) it's not easy for me to build them on a different platform than I would run them on.

We should enable this.  CoreFX could then use this to build Linux and OSX versions of the tests instead of always using the windows versions when running cross platform.

**Comment by nguerrera** [comment]
Does #189 help or hurt with this?

**Comment by ellismg** [comment]
@nguerrera I am not sure.  It seems like we should be able to leverage the CopyTestToTestDirectory target, but I do not fully understand how the infrastructure works.  I had thought doing something like:

```
> msbuild /t:Build,CopyTestToTestDirectory
```

Would both build the test and construct the test directory, but it would appear that while the copy step moves over the dependencies, it doesn't copy the test itself.
