### ISSUE TITLE
Split CloudTestTasks into Cloud/Azure tasks and CloudTest tasks

### ISSUE THREAD

**Issue by dagood** [dotnet/buildtools#1878]
"Test" doesn't make sense for almost all tasks in there--it's become a dumping ground for anything that talks to Azure. There are only a handful that seem like they belong:

 * `FilterForUpload`
 * `SendJobsToHelix`
 * `SendToHelix`
 * `SimulateHelixExecution`
 * `ValidateWorkItems`
 * `WriteBuildStatsJson`

The CloudTestTasks PackageFiles and RunnerScripts are more consistently related to testing.

(There is a overarching desire to make BuildTools more granular, this tracks a part of that.)

**Comment by maririos** [comment]
FYI @chcosta

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
