### ISSUE TITLE
GenApi should preserve order for com types

### ISSUE THREAD

**Issue by weshaggard** [dotnet/buildtools#1880]
See https://github.com/dotnet/standard/pull/631

Order matters for sequential structs and com interfaces so we need to be sure to not sort the members of those types.

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
