### ISSUE TITLE
Build BuildTools using 2.x+ CLI

### ISSUE THREAD

**Issue by dagood** [dotnet/buildtools#1885]
We're still on:

https://github.com/dotnet/buildtools/blob/b76c4b6e773f85efa9566b7a0090a8bca98cb57c/.cliversion#L1

Using 2.x+ with csproj-based projects (rather than csproj + project.json + nuspec) is the way forward.

**Comment by dagood** [comment]
I'm not completely sure how it will affect this issue (if it will) but we might need to consider https://github.com/NuGet/NuGet.Client/pull/2254. `EncryptedConfigNuGetRestore` might need to be [changed to MSBuild-style restore](https://github.com/dotnet/buildtools/issues/1550) before we can upgrade CLI, if we need to move the NuGet library to a very new version as a result of the CLI upgrade.

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
