### ISSUE TITLE
Base VersionTools package dependencies on dependencies.props

### ISSUE THREAD

**Issue by dagood** [dotnet/buildtools#1886]
If we do this and make sure dependency validation stays on during builds, we would avoid mismatches between the VersionTools project.json and nuspec. (https://github.com/dotnet/buildtools/pull/1884)

This wouldn't take very long to do, but it might be preempted by https://github.com/dotnet/buildtools/issues/1885 eliminating the duplication.

**Comment by dagood** [comment]
We should just flow the properties into the nuspec using `NuspecProperties`.

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
