### ISSUE TITLE
Source code lookup for certain .NET Core DLLs fails. (SourceLink support for GenFacades)

### ISSUE THREAD

**Issue by vancem** [dotnet/buildtools#1896]
Since Version 2.0 of the .NET Core Runtime publishes its PDBs on the public Microsoft symbol server and these PDBs have SourceLink information.   This allows easy stepping into .NET Core framework dlls.  (see https://github.com/dotnet/core/issues/897, and https://blogs.msdn.microsoft.com/vancem/2017/12/20/update-debugging-through-the-net-core-framework-v2-0-3-windows/) 

However this support is not complete.   In particular it does not work with the following framework DLLs.  
```
Microsoft.Win32.Registry.AccessControl
System.AppContext
System.Buffers
System.Collections
System.Diagnostics.Contracts
System.Diagnostics.Debug
System.Diagnostics.StackTrace
System.Diagnostics.Tools
System.Diagnostics.Tracing
System.Globalization
System.Globalization.Calendars
System.Globalization.Extensions
System.IO.FileSystem
System.IO.UnmanagedMemoryStream
System.Memory
System.Reflection
System.Reflection.Emit
System.Reflection.Emit.ILGeneration
System.Reflection.Emit.Lightweight
System.Reflection.Primitives
System.Reflection.TypeExtensions
System.Resources.ResourceManager
System.Runtime
System.Runtime.Extensions
System.Runtime.InteropServices
System.Runtime.InteropServices.WindowsRuntime
System.Runtime.Intrinsics
System.Runtime.Loader
System.Text.Encoding
System.Text.Encoding.Extensions
System.Threading
System.Threading.Overlapped
System.Threading.Tasks
System.Threading.Tasks.Extensions
System.Threading.Thread
System.Threading.ThreadPool
System.Threading.Timer
System.Xml.ReaderWriter
System.Xml.XDocument
System.Xml.XmlDocument
System.Xml.XmlSerializer
System.Xml.XPath
System.Xml.XPath.XDocument
```
That is because these DLLs need extra processing during build time.  The tool that does this is called 'GenFacades', and each of the above DLLs is run through this tool as part of the build.   This tool however does NOT support propagating the SourceLink information from its inputs, and as a result the PDBs for these DLLs do not have the information for fetching the source code. 

You can work-around this problem by opening looking at the 'ProductVersion' field of the DLL of interest s (the FileVer tool with the -v option will show that), and that will tell you show you something like this
```
        ProductVersion  4.6.26131.0 @BuiltBy: vancem-VANCEM1 @SrcCode: https://github.com/dotnet/corefx/tree/258238f492e952535d053a3bd2176c70684f947c
```
That URL shows the correct source code.  If you download (clone) that you can then point visual Studio at those source files to continue stepping.

The real solution of course is to fix GenFacades so that it propagates the SourceLink information

**Comment by vancem** [comment]
I should mention, that while the set of DLLs above seems large, the problem is not as large as it may seem.   The reason is that the reason these DLLs need special processing is that they are facades that forward some (often most) of their functionality to another DLL (often a private DLL like System.Private.Corelib).   If the actually code lives another DLL, then there is no problem that the façade (the dll in the list above) is missing source link information.   Thus the problem only occurs when the implementation is NOT forwarded to another DLL.   This is relatively rare.   System.Collections definitely has  SOME code in it, as does System.Threading.Thread, but for many of them the code lives elsewhere.

**Comment by mikem8361** [comment]
GenFacades also doesn't seem to add a debug directory in the resulting DLL to point to any pdb.

**Comment by vancem** [comment]
Also see issue #705.   Basically genFacades can't generate PDBs on Linux (since it only knows how to generate MicrosoftPDBs using Windows-specific DLLs).   Because of this, while on Windows the only issue is that we don't have SourceLink (source code) information, on Linux we have NO pdbs (thus only very limited debugging capabilities).   

Perhaps the most interesting point here however is that a fix for #705 will fix this issue.

Still this issue is got a pretty easy fix, where #705 requires genFacades to be ported/rewritten to get off of CCI (which does not support portable PDBs).

**Comment by vancem** [comment]
The most likely classes to be impacted are

System.Collections.Generic  HashSet, Queue Statck, TreeSet LinkedList
System.IO.File  System.IO.Directory.
System.Memory
System.Runtime.Extensions (Stopwatch, HashTable, ArrayList, StringReader, StringWriter)

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
