### ISSUE TITLE
Reuse Azure download code more

### ISSUE THREAD

**Issue by dagood** [dotnet/buildtools#1897]
Right now some of the core download code is shared, but there's still a significant amount of important code at each call site. More should be centralized.

I started working on this in https://github.com/dagood/buildtools/commit/a52905777c02ff50ebbf01e53501375895dd24a4, but split it off from a PR (https://github.com/dotnet/buildtools/pull/1894) due to time constraints and the amount of code it touches.

This may be obviated by https://github.com/dotnet/buildtools/issues/1816 (using azure storage libs).

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
