### ISSUE TITLE
UploadToAzure Overwrite=false doesn't work on container with many blobs

### ISSUE THREAD

**Issue by dagood** [dotnet/buildtools#1903]
Overwrite=false relies on this hash set filling up with all blob names that could potentially be overwritten:

https://github.com/dotnet/buildtools/blob/ba72a3dc435f0e450b4ded1226dc20d53a8c4dc0/src/Microsoft.DotNet.Build.CloudTestTasks/UploadToAzure.cs#L93-L96

However, it only makes one HTTP call, and the response only contains a certain number of blobs plus a continuation token (NextMarker). This means that even with Overwrite=false, this task can still blindly overwrite blobs since it doesn't know which ones already exist.

This unintended overwriting can happen on `dotnetcli`/`dotnetclichecksums` because they're organized as a single container with all builds in them as blobs.

@Chrisboh @MattGal @dleeapho @markwilkie we should figure out priority/who can work on it. This doesn't block prodcon, but it's a risk. (This is the issue I talked about in standup.)

(FYI @weshaggard I discovered this when validating the idempotency options. When rerunning publish to dotnetcli, the final publish step overwrote the target when I expected it to download and compare it. I didn't see this in my testing because my container didn't have much in it.)

**Comment by weshaggard** [comment]
Oh no that sucks. So it will cause problems whenever we do any sort of batch pushing of packages.

**Comment by dagood** [comment]
> So it will cause problems whenever we do any sort of batch pushing of packages.

Packages are fine--this task is only for "raw" uploads to blob storage (not a blob feed). This is used for publish the Core-Setup, CLI, and ASPNet installers and checksums.

> Does using the Azure api's account for this?

It would be harder to accidentally implement this bug using the Azure Storage SDK proper, yes. :smile: Ideally that library supports conditional headers so that we don't need to fetch a list of all blobs in the first place.

**Comment by MattGal** [comment]
I did the quick and simple fix for the time being last night; testing it now, should be out for PR in ~20 mins.

**Comment by MattGal** [comment]
Addressed by https://github.com/dotnet/buildtools/pull/1904 , closing;  please reopen if I am mistaken.

**Comment by eerhardt** [comment]
See also - https://github.com/dotnet/buildtools/issues/1788 which for some reason was moved to core-eng and then lost?

**Comment by weshaggard** [comment]
Lets try and use the "If-None-Match" header to fix this if we don't move to Azure SDK.

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
