### ISSUE TITLE
Make VersionTools use new cryptographic standards

### ISSUE THREAD

**Issue by dagood** [dotnet/buildtools#1905]
During the scheduled one-hour old crypto standards disable that GitHub ran (https://githubengineering.com/crypto-removal-notice/), VersionTools wasn't able to access On February 22, 2018 19:00 UTC this should start to cause failures in builds (when updating dotnet/versions) and some forms of auto-update (when reading from dotnet/versions).

Poking around briefly, I saw this:

```
System.Net.ServicePointManager.SecurityProtocol |= SecurityProtocolType.Tls12
```

**Comment by dleeapho** [comment]
Issue moved to [dotnet/core-eng #2679](https://github.com/dotnet/core-eng/issues/2679) via [**ZenHub**](https://www.zenhub.com/)
