### ISSUE TITLE
VS v MSBUILD commandline

### ISSUE THREAD

**Issue by grahamehorner** [dotnet/buildtools#1906]
Not sure if this is the correct place to log a possible issue with a behaviour difference between vs and msbuild command line, but I believe I may have discovered this when looking at the aspnet/Blazor repo and using it in my own projects outside of the repo folder using relative paths see https://github.com/aspnet/Blazor/issues/89

**Comment by danmosemsft** [comment]
Hi @grahamehorner . This is the repo actually for tools that build .NET itself, so not the right repo. It's hard to say based on the error messages, but I suggest opening an issue at https://github.com/NuGet/Home. They'll probably want help reproducing though.
