### ISSUE TITLE
BuildTools can cause VS 2015 to deadlock in the design-time build when loading a project that uses them

### ISSUE THREAD

**Issue by agocke** [dotnet/buildtools#191]
Roslyn uses the buildtools for core-clr projects and we've found that VS 2015 deadlocks while running the dnx.exe binary continuously in the background when loading a project that imports the buildtools targets. Try opening https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/CscCore/CscCore.csproj in VS 2015 for a repro of the issue.

**Comment by nguerrera** [comment]
Hitting this with corefx too. I think doing #192 would address this.

**Comment by agocke** [comment]
@JeremyKuhne When can I expect a build with these changes?

**Comment by JeremyKuhne** [comment]
@agocke Build 48 has dropped and has the change.

**Comment by agocke** [comment]
@JeremyKuhne Great, thanks!

**Comment by JeremyKuhne** [comment]
Er, sorry, mistyped- 58 :)
