### ISSUE TITLE
MakePri.exe - Error Message Useless - PRI277: 0xdef00532 - Conflicting values for resource ''

### ISSUE THREAD

**Issue by MelbourneDeveloper** [dotnet/buildtools#1912]
I am getting this error when I try to build a UWP app. The Windows build version is 16299. I can see that the error message comes up from MakePri.exe. I'm on VS Version 15.5.6. This is the command line called:

> C:\Program Files (x86)\Windows Kits\10\bin\10.0.16299.0\x64\MakePri.exe New -ProjectRoot C:\AdaptSource\src\Xivic\Adapt.Presentation.XamarinForms\Adapt.Presentation.Xivic.UWP\ -ConfigXml obj\x86\Debug\priconfig.xml -OutputFile C:\AdaptSource\src\Xivic\Adapt.Presentation.XamarinForms\Adapt.Presentation.Xivic.UWP\bin\x86\Debug\resources.pri -IndexName AdaptSolutionsPty.Ltd.Xivic-Helpdesk -Verbose -Overwrite

The error message doesn't give me enough information to figure out what the problem is. I'm guessing I have a duplicate reference, or duplicate resource file, but I can't locate anything like that. I've been over and over my project. I only have the bare minimum image files for the app. Can you please look in to the error message and make sure that it's giving us as much information as possible on build? It's stopped me in my tracks many times. Every time it burns hours or days of my time.

This is the non-descript error message:

> error PRI175 : 0x80073b0f - Processing Resources failed with error : Duplicate Entry.
>     
> GENERATEPROJECTPRIFILE : error PRI277: 0xdef00532 - Conflicting values for resource ''
> 
> Build FAILED.

**Comment by MelbourneDeveloper** [comment]
This problem seems to be related to having multiple versions of an assembly in the solution. In my case, I had multiple versions of Xamarin.Forms across multiple projects.  When I consolidated the versions, my UWP app started compiling. So, the moral of the story is that MakePri needs to give a better error message. It should say something like:

> GENERATEPROJECTPRIFILE : error PRI277: 0xdef00532 - Conflicting assembly reference versions. The following versions of the assembly Xamarin.Forms exist in the solution: 2.5.0.122203, 2.5.0.121934. This project cannot be built until all referenced versions match.

**Comment by maririos** [comment]
@joshfree could you help us redirect this issue to the Windows SDK team?

**Comment by joshfree** [comment]
Hi @MelbourneDeveloper, for UWP app questions you can email  dotnetnative@microsoft.com ([more details](https://github.com/Microsoft/dotnet/tree/master/releases/UWP#provide-feedback)) for assistance.

**Comment by MelbourneDeveloper** [comment]
@joshfree I can do that, but this is clearly an issue with MakePri.exe. Which team is responsible for this tool?

**Comment by MelbourneDeveloper** [comment]
@joshfree BTW: this has nothing to do with dot net native. I am not compiling with dot net native tool chain.

**Comment by joshfree** [comment]
@MelbourneDeveloper sorry, I don't know which specific team in Windows owns that Windows SDK tool.  If you email the address above, the folks on that distribution list can redirect your report.  Alternately you can file a bug via the [Report a Problem](https://aka.ms/vs-rap) tool, which is integrated with the [VS Developer Community Portal](https://developercommunity.visualstudio.com/); or through [Product Support](https://support.microsoft.com/en-us/contactus?ws=support) if you have a contract.

**Comment by MattGal** [comment]
Closing, as buildtools does not produce this binary.
