### ISSUE TITLE
Honor install location defined by the user

### ISSUE THREAD

**Issue by caioproiete** [dotnet/buildtools#1915]
Hello and apologies if this is not the right repo to report this issue (kindly point me to the right one, if that's the case).

When installing the Visual Studio Build Tools, the user is allowed to define a custom location where those build tools will be installed, but unfortunately the installer pretty much ignores the custom location and installs almost 90% of the components in a hard-coded location in the C: drive.

![image](https://user-images.githubusercontent.com/177608/36288288-4ee6cfd2-1290-11e8-83a2-95e206ad540e.png)

# Please fix this! :pray:

**Comment by danmosemsft** [comment]
@caioproiete this isn't the right place -- can you please use the mechanism built into VS to send this feedback:
https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017

I know that they are aware of this and I believe are working to improve it, but if you report it, that's another +1 vote certainly.

If that sounds good please go ahead and close this issue.

**Comment by caioproiete** [comment]
Perfect. Thanks @danmosemsft
