### ISSUE TITLE
Make buildtools defer to built-in nuget package resolution when available

### ISSUE THREAD

**Issue by nguerrera** [dotnet/buildtools#192]
The buildtools resolution of nuget assets was a bootstrapping mechanism as we got things to build with the .NET Core packages pending official support. Once the official support is broadly available, we should change the targets to detect this and use the built-in targets wherever possible. 

I'm currently preparing a temporary hack to rename some things such that buildtools does not conflict with VS and always uses its own targets. This is just to unblock things for internal devs quickly. 

Once possible, we will need to decide if we can take a required dependency on a version of VS with the built-in targets or if we want to allow building with older versions of VS by falling back to the code in buildtools.

cc @ericstj @ljw1004

**Comment by MichaelSimons** [comment]
Triage: nothing we can do for the moment.
