### ISSUE TITLE
Update BuildTools to use a new BuildTools toolset

### ISSUE THREAD

**Issue by dagood** [dotnet/buildtools#1934]
We're currently on 1.0.27-prerelease-01205-03, built on 2017/01/05.

https://github.com/dotnet/buildtools/blob/d5e58559ea1265daa6c6aacd72e6c40ed0030741/.toolversions#L1-L3

I saw two approaches:

 1. Work through breaking changes and make it so BuildTools works with the current CLI version being used. Most importantly, `project.json` is still used. The furthest I got was getting Csc running but unable to find any libraries (due to no packages being resolved, I think): https://github.com/dagood/buildtools/commits/add-project.json
 2. Upgrade the CLI version that BuildTools uses and take changes from CoreFX to fix other breaks. This is tracked by https://github.com/dotnet/buildtools/issues/1885.

I'm dropping it for now because it doesn't fit the First Responder scope.

**Comment by kasper3** [comment]
@dagood, can the project.json -> csproj migration also take place in the same iteration?

**Comment by dagood** [comment]
It can/might, but keep in mind that we don't have a iteration/schedule/goal for either this issue or https://github.com/dotnet/buildtools/issues/1885. In my experience, BuildTools issues are usually only proactively worked on when there's a hard blocker on it in a Core repo (CoreCLR, CoreFX, Core-Setup).

**Comment by kasper3** [comment]
Understood, hopefully someday. :)
btw, isn't the migration tooling that dotnet-cli provided (project.json -> csproj) solved this problem? Can that be used for bulk transform to reduce the manual effort?

**Comment by dagood** [comment]
I gave that a quick shot once, and it gave me some nasty looking errors when I tried to restore/build it. It's probably a useful starting point, but not far enough for me to do on a whim. :smile:

**Comment by kasper3** [comment]
Found an interesting tool to convert projects in bulk: https://github.com/hvanbakel/CsprojToVs2017

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
