### ISSUE TITLE
Add task to Feed package that generates manifest on disk, rather than PushToBlobFeed

### ISSUE THREAD

**Issue by dagood** [dotnet/buildtools#1937]
Just extract this method into a task and use that task in `PushToBlobFeed`:

https://github.com/dotnet/buildtools/blob/033355d2fd6cf5f2d4f69b71d32e69273cf02ac2/src/Microsoft.DotNet.Build.Tasks.Feed/PushToBlobFeed.cs#L142

Context: ASP.NET would like to be able to use the manifest creation logic, and it would be a waste to have to reimplement the parts that are in `PushToBlobFeed` (and worse: potentially diverge).

Might make sense to move this to Arcade, I don't know if Feed stuff is ported over yet.

/cc @natemcmaster

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
