### ISSUE TITLE
No Commit hash goes into InformationVersion in 2.0.0

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/buildtools#1940]
https://github.com/dotnet/buildtools/blob/release/2.0.0/src/Microsoft.DotNet.Build.Tasks/PackageFiles/versioning.props#L8 is not getting a commit hash inserted into it, because at the time that versioning.props is imported in versioning.targets (https://github.com/dotnet/buildtools/blob/release/2.0.0/src/Microsoft.DotNet.Build.Tasks/PackageFiles/versioning.targets#L27), no value has yet been set for SrcCodeRef (https://github.com/dotnet/buildtools/blob/release/2.0.0/src/Microsoft.DotNet.Build.Tasks/PackageFiles/versioning.targets#L295-L303). This appears to have already been fixed in master, we need a similar fix for 2.0.0, as without it, our assemblies are not being stamped with their corresponding commit hashes. @vancem are you already aware of this issue?

CC @eerhardt

**Comment by vancem** [comment]
I was not previously aware of this issue, but I don't tend to look at old versions.   Thanks for the info.

**Comment by eerhardt** [comment]
I don't think we should ship anymore `2.0.x` versions without this.  Adding `blocking release`.

**Comment by wtgodbe** [comment]
https://github.com/dotnet/buildtools/pull/1946 should resolve

**Comment by wtgodbe** [comment]
Resolved by https://github.com/dotnet/buildtools/pull/1946
