### ISSUE TITLE
Resx files are not working for F# and VB project

### ISSUE THREAD

**Issue by Lanayx** [dotnet/buildtools#1942]
I've already created an issue in another repo https://github.com/dotnet/cli/issues/8697 , but the week has passed and no action has been done, probably that was incorrect repo to submit an issue. For me inability to add localization to F# and VB is a very serious issue.

**Comment by dleeapho** [comment]
Thank you @lanayx dotnet/cli#8697 is indeed the correct place to log this issue and to engage with the team.
