### ISSUE TITLE
Buildtools has an outdated build process

### ISSUE THREAD

**Issue by mellinoe** [dotnet/buildtools#195]
Currently, we're using a really old version of buildtools, and the .NET Core Xunit assemblies we build in this repo are building against very old versions of our NuGet packages (very different from the latest packages), and are still using packages.config files. We should update these to be in line with corefx.

**Comment by ericstj** [comment]
I'd like to fix this with https://github.com/dotnet/corefx/issues/2427 instead

**Comment by mellinoe** [comment]
Did you mean to close this? I'm fine with making the same improvement to both repos if that's what we intend to do.

**Comment by weshaggard** [comment]
Given @JeremyKuhne reverted your update @mellinoe we should reopen this issue. I think @ericstj is referring to a more general update away from dnx and less of you intended with this issue which is to update the buildtools repo itself to use the latest buildtools.

**Comment by mellinoe** [comment]
Sounds good to me. I think it makes sense to get this repo on the latest buildtools, because then when we make improvements to corefx's build process, we can just apply them here as well, instead of having to jump straight from this old build process.

**Comment by mellinoe** [comment]
#205 merged and the official build went through fine. This particular issue (being on an old version of buildtools) should be resolved now.

**Comment by weshaggard** [comment]
@mellinoe Have you tried the new build against CoreFX to ensure everything still works as expected?

**Comment by mellinoe** [comment]
CoreFx is already on the new tools and hasn't hit any issues so far. There aren't really any functional changes here, other than possibly the fact that we are using new packages as opposed to the months-old ones.
