### ISSUE TITLE
Fix resources.pri problem in uwp6.1

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/buildtools#1954]
In the WCF repo we recently had to move our release/uwp6.1 branch to buildtools version "2.0.0-uwp61-02602-01", this version of build tools was forked of [a commit from back in July](https://github.com/dotnet/buildtools/commits/release/uwp6.1) which is shortly before a breaking change in CoreClr related to 'resource lookup fallback' necessitated a buildtools updated, see dotnet/wcf#2157.

I believe we need the fix made in buildtools master branch by @safern ported to the buildtools uwp6.1 branch in order to fix our WCF uwp6.1 branch. I'm not sure exactly which changes in buildtools are needed, there are several commits that appear to be related around the same time frame.

@safern could you assist with this?

FYI: @tarekgh @zhenlan @MattGal 

Related commits...
https://github.com/dotnet/buildtools/commit/c45406f85a56c903d02eab582db455afa98dce3d 
https://github.com/dotnet/buildtools/commit/8ecf1097f182c65de6122d729f27ab35d98dffaf 
https://github.com/dotnet/buildtools/commit/579bdc0a7cfb65f99b5e3221cc599c4cf4c1ba71 
https://github.com/dotnet/buildtools/commit/31b3b224a1ea47d5fb6a13384a42147d3d6fe3ea

**Comment by safern** [comment]
I diffed the commits that you currently have in buildtools uwp6.1 branch and I see the following commits missing related to the resources extraction:

https://github.com/dotnet/buildtools/commit/34df12c76df040faa512dd8cc47bd996ad246454
https://github.com/dotnet/buildtools/commit/bbbede8fef122f43180b343ca93d1032904a6cb7#diff-dccabf83e08d3281efb7ebb5798da47a
https://github.com/dotnet/buildtools/commit/1f57d19b4a19c972d7e94050cd839a4b992f39fc#diff-dccabf83e08d3281efb7ebb5798da47a

The other commits that you point out are already in that branch.

Do you need help porting this changes? Could you please confirm this fixes your issue?

**Comment by StephenBonikowsky** [comment]
We know this is the failure we are currently hitting when we use buildtools version "2.0.0-uwp61-02602-01".
I would prefer that you do the ports since this package is being used by CoreClr and Corefx in their uwp6.1 branches and I don't want to do something unintended that breaks them.

**Comment by StephenBonikowsky** [comment]
Fixed by #1955
