### ISSUE TITLE
Create uwp6.0 branch

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/buildtools#1957]
WCF needs a uwp6.0 buildtools branch in order to best be able to service our WCF release/uwp6.0 branch and reduce the chances of some unexpected buildtools change breaking our build.

The current state of the buildtools uwp6.1 branch works for WCF's uwp6.0 branch so snapping from it would be good.

**Comment by StephenBonikowsky** [comment]
@MattGal @dagood could you or someone else help with this?

**Comment by MattGal** [comment]
the branch already exists.  Do you mean like a build definition or ?

**Comment by StephenBonikowsky** [comment]
Hmm, I don't see a branch called uwp6.0 in this repo, am I missing something?

the uwp6.1 buildtools branch will work now for WCF's uwp6.0 branch now that we ported some missing commits from Master. I guess we are concerned that using one buildtools branch for two release branches that will be serviced separately will eventually be a problem or confusing.

@zhenlan We were discussing this, thoughts?

**Comment by dagood** [comment]
Created the branch at `release/uwp6.1`'s current commit, and I'll submit a PR to make the package versions unique shortly.

**Comment by dagood** [comment]
The branch is created--and I agree, we should be able to use the same build definition for it.

**Comment by StephenBonikowsky** [comment]
Awesome, thanks!
