### ISSUE TITLE
Update sign.targets with signing on non-windows

### ISSUE THREAD

**Issue by jcouv** [dotnet/buildtools#1966]
https://github.com/dotnet/roslyn/issues/8210 has been resolved and Roslyn now supports signing on non-windows.

https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks/PackageFiles/sign.targets#L40

```
    <!--
      Setting DelaySign to true when running build on unix because of Roslyn doesn't support full signing on non-windows.
      See issue https://github.com/dotnet/roslyn/issues/8210.
    -->
    <DelaySign Condition="'$(RunningOnUnix)' == 'true'">true</DelaySign>
```

**Comment by Chrisboh** [comment]
Can you clarify the need for this in buildtools?

**Comment by jcouv** [comment]
I'm just pointing out that this comment used to be valid (before Roslyn supported signing cross-platform), but isn't any longer. I'll let you draw the conclusions as to what is an appropriate action.

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
