### ISSUE TITLE
Support <PackAsTool>

### ISSUE THREAD

**Issue by huanwu** [dotnet/buildtools#1976]
We are trying to build svcutilcore as a tool so it can be installed by global tool as described [here](https://github.com/dotnet/core/tree/master/samples/dotnetsay)
I added `<PackAsTool>true</PackAsTool>` in [svcutilcore.csproj](https://github.com/dotnet/wcf/blob/master/src/svcutilcore/src/svcutilcore.csproj), and then run command to build package. It won't build a package as expected. Could you provide a solution or workaround?

**Comment by dleeapho** [comment]
@huanwu can you provide more context on the scenario?
@markwilkie per our discussion this should probably go to arcade.

**Comment by maririos** [comment]
Please reopen when there is more information
