### ISSUE TITLE
Have VersionTools create a GitHub fork for the auto-update branch if one doesn't exist yet

### ISSUE THREAD

**Issue by dagood** [dotnet/buildtools#1981]
This removes an unnecessary manual step when adding auto-updates to a new repo.

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
