### ISSUE TITLE
Minimize the set of targets and properties needed to consume buildtools

### ISSUE THREAD

**Issue by mellinoe** [dotnet/buildtools#200]
Over time, we have increased the amount of settings and configuration needed to get a blank project building with the buildtools package. From the https://github.com/dotnet/corefx repo, the following msbuild files are all needed to build, or exist because of workarounds on various platforms, etc:
- build.proj
- dir.props
- dir.targets
- dir.traversal.targets
- mono.targets
- override.targets
- roslyn.xplat.targets
- src/BuildValues.props
- src/dir.props
- src/dir.targets
- src/dirs.proj
- src/.nuget/packages.Windows_NT.config
- src/.nuget/packages.Unix.config

Not all of the configuration above is strictly necessary for a blank build, but a lot of it is. There's also a very substantial amount of stuff in some of the files, like dir.props, dir.targets, and dir.traversal.targets.

We should try to consolidate some of the common properties into buildtools itself, and perhaps provide a sample template for minimal builds using buildtools.

**Comment by ViktorHofer** [comment]
Closing as the buildtools repository has been archived and replace by https://github.com/dotnet/arcade.
