### ISSUE TITLE
GenAPI misses new modifier on nested classes

### ISSUE THREAD

**Issue by ericstj** [dotnet/buildtools#2004]
In the case a derived class defines a nested class with the same name as the base, GenAPI misses emitting the new keyword.  /cc @weshaggard

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
