### ISSUE TITLE
Update RID lists used for packaging to match the officially supported RIDs

### ISSUE THREAD

**Issue by ericstj** [dotnet/buildtools#2016]
@weshaggard mentioned https://github.com/dotnet/buildtools/pull/2015#discussion_r182895387 that we might need to further update our RID lists to match the officially supported list.

We have a couple places where this is listed and they don't agree so I'm reluctant to make the update at the moment.  We should get a good list somewhere public and make sure that buildtools matches that.

**Comment by weshaggard** [comment]
Here is a link to our onenoe with OS info.
https://microsoft.sharepoint.com/teams/netfx/CLR/ProjectK/_layouts/OneNote.aspx?id=%2Fteams%2Fnetfx%2FCLR%2FProjectK%2FDocuments%2FTactics%2FNET%20Core%20Release%2Fnet-core-release&wd=target%28net-core-release.one%7C0CF34A20-F342-FA43-8944-18B555589A6B%2FUpcoming%20OS%20releases%7C349DD0D0-5504-AC4A-83D3-94668317C8EB%2F%29

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
