### ISSUE TITLE
xunit fails with System.InvalidOperationException when -serialize option is used

### ISSUE THREAD

**Issue by marek-safar** [dotnet/buildtools#2017]
We are running manually CoreFX xunit tests and when xunit `-serialize` option is used xunit fails to load CoreFX tests due to

```
System.InvalidOperationException: Could not de-serialize type 'Xunit.NetCore.Extensions.SkippedTestCase' because it lacks a parameterless constructor.
```

**Comment by danmosemsft** [comment]
@marek-safar what do you use `-serialize` for? The docs imply it's needed when running tests in VS, but currently we do not integrate properly with that.
If you add the ctor [here](https://github.com/dotnet/buildtools/blob/master/src/xunit.netcore.extensions/SkippedTestCase.cs) and copy over xunit.netcore.extensions.dll into tools, are there any other fixes required?

**Comment by marek-safar** [comment]
@danmosemsft we use it when runtime behaves unexpectedly (e.g. because of regression) adding empty default ctor is not enough as xunit seems to call the other properties which requires _testCase to be initialized to non-null value

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
