### ISSUE TITLE
SupportedFramework notes in projects may have ordering issues

### ISSUE THREAD

**Issue by weshaggard** [dotnet/buildtools#2025]
See comments at https://github.com/dotnet/corefx/pull/29148/files#r184111719. It appears that if we are harvesting supported versions and listing out just the earliest versions we have to explicitly list out every version that we harvested otherwise they don't correctly get promoted.

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
