### ISSUE TITLE
Need to track disabled/skipped test cases

### ISSUE THREAD

**Issue by caesar-chen** [dotnet/buildtools#2041]
For attributes which return trait instead of test cases, XUnit won't notify developer how many test cases are "skipped", instead just silently not running them (like `ActiveIssue` and `SkipOnTargetFramework`, and the newly introduced `ConditionalClass`).

We want those attributes to report skipped test cases as well. Here are some ideas to fix it: 
https://github.com/dotnet/buildtools/pull/2040#issuecomment-390739764
https://github.com/dotnet/buildtools/pull/2040#issuecomment-390742435

Example:

When we do `[ConditionalFact/Theory]`, we have the `Condition(s) not met` message and information like `Skipped: 4`

```
Discovering: System.Net.HttpListener.Tests
  Discovered:  System.Net.HttpListener.Tests
  Starting:    System.Net.HttpListener.Tests
     System.Net.Tests.HttpListenerTimeoutManagerUnixTests.IdleConnection_Roundtrips [SKIP]
        Condition(s) not met: \"IsManagedImplementation\"
     System.Net.Tests.HttpListenerTimeoutManagerUnixTests.UnsupportedProperties_Throw [SKIP]
        Condition(s) not met: \"IsManagedImplementation\"
     System.Net.Tests.HttpListenerTimeoutManagerUnixTests.Properties_DefaultValues [SKIP]
        Condition(s) not met: \"IsManagedImplementation\"
     System.Net.Tests.HttpListenerTimeoutManagerUnixTests.DrainEntityBody_Roundtrips [SKIP]
        Condition(s) not met: \"IsManagedImplementation\"
  Finished:    System.Net.HttpListener.Tests

  === TEST EXECUTION SUMMARY ===
     System.Net.HttpListener.Tests  Total: 676, Errors: 0, Failed: 0, Skipped: 4, Time: 16.804s
```

But using `[ConditionClass]` or `[ActiveIssue]`, here is the output: (notice there is no output message in console, and `Skipped: 0`)

```
Discovering: System.Net.HttpListener.Tests
  Discovered:  System.Net.HttpListener.Tests
  Starting:    System.Net.HttpListener.Tests
  Finished:    System.Net.HttpListener.Tests

  === TEST EXECUTION SUMMARY ===
     System.Net.HttpListener.Tests  Total: 631, Errors: 0, Failed: 0, Skipped: 0, Time: 13.847s
```

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
