### ISSUE TITLE
Binplacing assumes config system properties

### ISSUE THREAD

**Issue by ericstj** [dotnet/buildtools#2046]
I ran into an issue where I was trying to use our config system and promote ArchGroup to a significant property (since I needed to cross-compile with it).

Just doing that was not sufficient because we assume that tacking ConfigurationGroup to the end of the config string  will result in a "full" configuration:
https://github.com/dotnet/buildtools/blob/b76c4b6e773f85efa9566b7a0090a8bca98cb57c/src/Microsoft.DotNet.Build.Tasks/PackageFiles/FrameworkTargeting.targets#L354

I worked around it by re-ordering ArchGroup to come before ConfigurationGroup but this is a bit of hack.

We should avoid assuming these *Group properties in buildtools.  Buildtools should define a system with which to compose the *Group properties for multi-targeting, but avoid coupling to those specific properties or string ordering when dealing with configuration strings.

To fix this problem we should set a property that represents the selected configuration out of BuildConfigurations, and use just that, rather than tacking ConfigurationGroup onto the end.

Similarly we should use that property here:
https://github.com/dotnet/buildtools/blob/b76c4b6e773f85efa9566b7a0090a8bca98cb57c/src/Microsoft.DotNet.Build.Tasks/PackageFiles/FrameworkTargeting.targets#L288-L289

Elsewhere in buildtools we should try to eliminate the use of the *Group properties, or at least formalize their meaning and requirements.  We should never try to construct configuration strings in buildtools as their format should be owned by the consuming repo.

/cc @weshaggard @safern @joperezr

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
