### ISSUE TITLE
msbuild given a folder path will ignore the pp argument

### ISSUE THREAD

**Issue by maryamariyan** [dotnet/buildtools#2064]
Example:

`msbuild folder_containing_csproj\csproj_file.csproj /pp`

works as expected but:

`msbuild folder_containing_csproj\ /pp` 

doesn't pick up the `/pp` option.

**Comment by maririos** [comment]
@dsplaisted could you rout this to MsBuild please?

**Comment by dsplaisted** [comment]
This issue was moved to Microsoft/msbuild#3462
