### ISSUE TITLE
crossgen: Microsoft.DotNet.Build.Tasks.dll" or one of its dependencies was not found

### ISSUE THREAD

**Issue by am11** [dotnet/buildtools#2073]
Crossgen is failing on multiple legs:

```
/Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/Tools/csc.dll -> /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/Tools/csc.ni.dll
Error compiling /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/Tools/Microsoft.DotNet.Build.Tasks.dll: Could not load file or assembly 'Microsoft.Build.Framework, Version=14.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
 (Exception from HRESULT: 0x80070002)
Error: file "/Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/Tools/Microsoft.DotNet.Build.Tasks.dll" or one of its dependencies was not found
Unable to successfully compile /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/Tools/Microsoft.DotNet.Build.Tasks.dll
```

although it is a benign error and can be ignored (https://github.com/dotnet/corert/issues/5962#issuecomment-398466845), can it be silenced?

**Comment by maririos** [comment]
The fix is to not crossgen the msbuild task dll as it is a desktop assembly

**Comment by am11** [comment]
@maririos, thanks. Would it be a good idea to add a filter for `'Microsoft.DotNet.Build.Tasks.dll` similar to the existing one: https://github.com/dotnet/buildtools/blob/7ae2813/src/Microsoft.DotNet.Build.Tasks/PackageFiles/crossgen.sh#L37

It was showing up in docker output when I was building CoreRT, later I found that CoreRT build logs in Jenkins are also showing these.

**Comment by maririos** [comment]
I don't see why not. Do you mind opening a new issue with that information?

**Comment by BruceForstall** [comment]
@am11 @maririos Did another issue get opened to track this? Did another "filter" fix to crossgen.sh go it?

I'm seeing this in dotnet/coreclr jobs, e.g.: https://ci.dot.net/job/dotnet_coreclr/job/master/job/checked_ubuntu_tst/4929/consoleText

**Comment by maririos** [comment]
Not from my side and haven't seen a change for this.
