### ISSUE TITLE
dotnet build and custom target with a depenedency on Json.Net: File name: 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'

### ISSUE THREAD

**Issue by abatishchev** [dotnet/buildtools#2074]
Hi,
I have a project (Service Fabric if that matters) which uses a custom props and targets files which call a DLL winch has a dependency on Newtonsoft.Json.dll which is shipped alongside.
When I build inside VS2017 I have no errors.
But when I run `dotnet build` I'm getting this:

> BuildLayout.targets(21,5): error MSB4018: The "GenerateArmTemplateTask" task failed unexpectedly. [DeploymentAgent.sfproj]
BuildLayout.targets(21,5): error MSB4018: System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621) [DeploymentAgent.sfproj]
BuildLayout.targets(21,5): **error MSB4018: File name: 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'** [DeploymentAgent.sfproj]
BuildLayout.targets(21,5): error MSB4018:    at BuildLayout.Generators.TemplateGenerator.Generate(BuildLayoutOptions args, ApplicationManifestType appManifest) [DeploymentAgent.sfproj]
BuildLayout.targets(21,5): error MSB4018:    at BuildLayout.Generators.BuildLayoutGenerator.Generate(BuildLayoutOptions args) in e:\bt\921388\repo\src\product\buildlayout\Generators\BuildLayoutGenerator.cs:line 23 [DeploymentAgent.sfproj]
BuildLayout.targets(21,5): error MSB4018:    at BuildLayout.Tasks.GenerateArmTemplateTask.Execute() in e:\bt\921388\repo\src\product\buildlayout\Tasks\GenerateArmTemplateTask.cs:line 46 [DeploymentAgent.sfproj]
BuildLayout.targets(21,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [DeploymentAgent.sfproj]
BuildLayout.targets(21,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [DeploymentAgent.sfproj]
BuildLayout.targets(21,5): error MSB4018:  [DeploymentAgent.sfproj]

Please help me to understand how it works and why i'm getting it.

**Comment by maririos** [comment]
Issue moved to [dotnet/cli #9578](https://github.com/dotnet/cli/issues/9578) via [**ZenHub**](https://www.zenhub.com/)
