### ISSUE TITLE
Testing: Should 'UnsupportedPlatforms' instead/also be 'SupportedPlatforms'?

### ISSUE THREAD

**Issue by bartonjs** [dotnet/buildtools#210]
We have a couple of Windows-only libraries:
* System.Security.Principal.Windows
* System.Security.Cryptography.Csp
* System.Security.Cryptography.Cng
* Probably others
and each of these libraries has to mark their tests as
```xml
<UnsupportedPlatforms>Linux;OSX</UnsupportedPlatforms>
```
When we define a new platform (e.g. FreeBSD) all of these test libraries are going to have to be touched to say that they won't support it.

For something which is a common-Unix concept (such as the OpenSsl crypto sub-library) `<UnsupportedPlatforms>Windows_NT</UnsupportedPlatforms>` might make sense, but otherwise it feels to me like once it's platform-specific it should be opt-in.

**Comment by stephentoub** [comment]
I actually question whether we need this mechanism at all.  We already have ```[PlatformSpecific(...)]``` and ```[ActiveIssue(..., PlatformID.*)]```.  If we were to just make small tweaks to those such that they could be applied/respected at the assembly/class/method level instead of just at the method level, then we could put ```[assembly: PlatformSpecific(PlatformID.Windows)]``` on those test assemblies and call it a day.

**Comment by davidsh** [comment]
+1 to @stephentoub suggestion.

**Comment by bartonjs** [comment]
Assuming that works, I'd be happy with that answer.  My hesitant concern is that the platform-specific-ness might be something which would cause reflection to fail and xUnit might not handle that gracefully.

Really I just want a way to express an opt-in model :smile:.

**Comment by ellismg** [comment]
Given the new .builds model of configuring what platforms we build things for, you basically have this as opt-in now.  We no longer use `<UnsupportedPlatforms>`, instead we just test all tests that are produced by the build and use the .builds to control if we build an assembly for a given group or not.
