### ISSUE TITLE
UpdateVSConfigurations should use Windows new line on Unix

### ISSUE THREAD

**Issue by hughbe** [dotnet/buildtools#2105]
Otherwise things get a bit weird when running this on Unix

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
