### ISSUE TITLE
Add TargetFrameworkIdentifier to generated configuration.props

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/buildtools#2110]
Current we generate a configuration.props file which contains the following properties:

```
<When Condition="$(_parse_Configuration.Contains('-netcoreapp2.0-'))">
    <PropertyGroup>
        <TargetGroup>netcoreapp2.0</TargetGroup>
        <NuGetTargetMoniker>.NETCoreApp,Version=v2.0</NuGetTargetMoniker>
        <NuGetTargetMonikerShort>netcoreapp2.0</NuGetTargetMonikerShort>
    </PropertyGroup>
</When>
```

We should also set the `TargetFrameworkIdentifier` as external props/targets rely on this being set. E.g. `Microsoft.NET.Test.Sdk` which is used for xunit unit test explorer integration.

cc @weshaggard @ericstj @eerhardt

**Comment by ViktorHofer** [comment]
cc @weshaggard @ericstj @eerhardt

**Comment by weshaggard** [comment]
@ViktorHofer you do that by adding that property in the targets file in corefx https://github.com/dotnet/corefx/blob/master/tools-local/targetgroups.props. All the generated configuration stuff does is copy over those properties.

**Comment by maririos** [comment]
Thanks to Wes' reply, closing this issue

**Comment by ViktorHofer** [comment]
Why do you do close the issue when it isn't yet fixed??

**Comment by ViktorHofer** [comment]
Issue moved to [dotnet/corefx #31435](https://github.com/dotnet/corefx/issues/31435) via [**ZenHub**](https://www.zenhub.com/)
