### ISSUE TITLE
ApiCompat misses several API differences

### ISSUE THREAD

**Issue by tannergooding** [dotnet/buildtools#2114]
Whatever tool does the checks to ensure the CoreFX ref assemblies match up with the System.Private.Corelib signatures (I believe this is ApiCompat) misses a few differences.

Namely, https://github.com/dotnet/corefx/pull/31528 and https://github.com/dotnet/corefx/pull/31515 should have initially failed because the various classes had the following changes:
* Added a base class to many classes
* Added the `new` modifier to several methods which were purposefully hiding methods in a base class

CC. @ericstj, @weshaggard

**Comment by tannergooding** [comment]
Removed the issue with it not catching the `sealed` modifier, it is failing with that now, perhaps the PR got into a bad state.

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
