### ISSUE TITLE
Multiple enumeration problem in VersionTools DependencyUpdateUtils.Update

### ISSUE THREAD

**Issue by dagood** [dotnet/buildtools#2122]
I haven't looked any deeper, but this problem is why this shows up as CoreFXLab's auto-PR message:

> Update CoreFx, CoreFx, CoreFx, CoreFx, CoreFx, CoreSDK to preview1-26813-02, preview1-26813-02, preview1-26813-02, preview1-26813-02, preview1-26813-02, 0.2.0, respectively

vs. the expected

> Update CoreFx, CoreSDK to preview1-26813-02, 0.2.0, respectively

CoreFXLab passes `DependencyUpdateUtils.Update` iterator IEnumerables that create new objects. VersionTools seems to run the iterator multiple times, ending up with a lot more dependency info objects than it should.

`DependencyUpdateUtils.Update` should call ToArray on the args (or something similar) to make sure this doesn't happen.

---

A workaround (added to CoreFXLab and Core-SDK) is adding `ToArray()` before calling `DependencyUpdateUtils.Update`. (See https://github.com/dotnet/corefxlab/pull/2427/files.)

**Comment by dagood** [comment]
FYI @eerhardt this is almost definitely the cause of this in CLI, too.

**Comment by danmosemsft** [comment]
@dagood can close now?

**Comment by eerhardt** [comment]
I believe the change @dagood made to `dotnet/core-sdk` was just a temporary workaround the underlying bug in buildtools (which hasn't been fixed yet).

**Comment by dagood** [comment]
@eerhardt has it right--the usage-side workaround is pretty trivial, but there is an underlying VersionTools bug here. I moved the workaround paragraph to the end of the issue description to make it clearer.

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
