### ISSUE TITLE
"Removing the archaic two spaces after peroid in our copyright" needs to be ported to Release branches

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/buildtools#2144]
https://github.com/dotnet/buildtools/pull/2136

We need this in the Release branches before releasing packages after September 7.

CC @weshaggard @eerhardt 

- [ ] 1.0.0
- [ ] 1.1.0
- [ ] 2.0.0
- [ ] 2.1

**Comment by wtgodbe** [comment]
1.0.0 - https://github.com/dotnet/buildtools/pull/2146

**Comment by wtgodbe** [comment]
1.1.0 - https://github.com/dotnet/buildtools/pull/2147

**Comment by wtgodbe** [comment]
2.0.0 - https://github.com/dotnet/buildtools/pull/2148

**Comment by wtgodbe** [comment]
2.1 - https://github.com/dotnet/buildtools/pull/2149

**Comment by weshaggard** [comment]
Remember you will likely need to manually update the BuidTools version in the older branches.

**Comment by wtgodbe** [comment]
1.0.0 Buildtools build - https://devdiv.visualstudio.com/DevDiv/Net%20CoreFX/_build/results?buildId=1989787
1.1.0 Buildtools build - https://devdiv.visualstudio.com/DevDiv/Net%20CoreFX/_build/results?buildId=1989801

I'm not sure where the 2.0.0 or 2.1 buildtools builds are, @weshaggard or @mmitche do you know?

**Comment by weshaggard** [comment]
>I'm not sure where the 2.0.0 or 2.1 buildtools builds are, @weshaggard or @mmitche do you know?

They share the same build definition as master.

**Comment by mmitche** [comment]
There's also a 2.2 build.

**Comment by mmitche** [comment]
(which should auto update)
