### ISSUE TITLE
Are the Roslyn checks still necessary?

### ISSUE THREAD

**Issue by stephentoub** [dotnet/buildtools#2206]
In a variety of places, we check MSBuildToolsVersion to determine whether we're using Roslyn, e.g.
https://github.com/dotnet/buildtools/blob/e4b8152e37d3dd866fe8127114ae9780f58d405c/src/Microsoft.DotNet.Build.Tasks/PackageFiles/ReferenceAssemblies.targets#L9
and
https://github.com/dotnet/buildtools/blob/28606b8791ccf507651febbf41c480dd87d4a507/src/Microsoft.DotNet.Build.Tasks/PackageFiles/Build.Common.props#L48-L55
Is this still necessary?  Or can we just assume we're using Roslyn everywhere and simplify these checks?

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
