### ISSUE TITLE
Network build failures in 'official/corefx/master/' - '20181215.02'

### ISSUE THREAD

**Issue by robertborr** [dotnet/buildtools#2210]
@dotnet-mc-bot commented on [Sat Dec 15 2018](https://github.com/dotnet/core-eng/issues/4808)

There were a set of failures during this build. Here is a summary of these:
* https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=2280719
  - **Agent:** DDVSOWINAGE057
  - **Error log:** 1>E:\A\_work\0\s\corefx\Tools\CloudTest.Helix.targets(0,0): error : A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host h...

@jcagme, @markwilkie

---

@robertborr commented on [Mon Dec 17 2018](https://github.com/dotnet/core-eng/issues/4808#issuecomment-447921507)

This is an unhandled System.Net.Sockets.SocketException. If you want to fix it, here's an example of how:
https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.CloudTestTasks/SendJobsToHelix.cs#L161-L178   - Handle System.Net.Sockets.SocketException

copying to build-tools

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
