### ISSUE TITLE
DownloadFilesFromUrl task vs. MSBuild's DownloadFile

### ISSUE THREAD

**Issue by am11** [dotnet/buildtools#2211]
In MSBuild 15.8, a new task `<DownloadFile>` was introduced: https://github.com/Microsoft/msbuild/pull/3297. With that we can do stuff like:

```sh
#!/usr/bin/env sh

dotnet --version
# 2.2.101

mkdir ~/TestDownloadTask

cat > ~/TestDownloadTask/on-the-fly-compilation.csproj <<'EOF'
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.2</TargetFramework>
  </PropertyGroup>

  <Target BeforeTargets="ApplyImplicitVersions" Name="FetchSources">
    <DownloadFile
      SourceUrl="https://raw.githubusercontent.com/dotnet/corert/635cf21/samples/HelloWorld/Program.cs"
      DestinationFolder="$(MSBuildThisFileDirectory)" />
  </Target>

</Project>
EOF

dotnet run -p TestDownloadTask
# prints 'Hello World'
````

There is a similar task present in this repo: https://github.com/dotnet/buildtools/blob/6736870/src/Microsoft.DotNet.Build.Tasks/DownloadFilesFromUrl.cs, which can be replaced by the one coming from upstream.

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
