### ISSUE TITLE
BuildTools official build broken, fails to publish to dotnet/versions

### ISSUE THREAD

**Issue by dagood** [dotnet/buildtools#2217]
BuildTools was fixed with https://github.com/dotnet/buildtools/pull/2213 for other repos like CoreCLR and CoreFX, however BuildTools needs to uptake a new BuildTools toolset to get the fix.

Example: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2340542

Until this is fixed, BuildTools versions on dotnet/versions need to be updated manually after a build, like https://github.com/dotnet/versions/pull/414.

This might not trivial, the toolset this repo is on now is very old (last update Jan 10, 2017):

https://github.com/dotnet/buildtools/blob/044ecfcca4fb78bc959ac63d728598006e76c180/.toolversions#L1

This is also needed on `release/2.1` / `release/2.2` to fix those branches' official builds.

See https://github.com/dotnet/buildtools/pull/2213 for info about the cause.

**Comment by tommcdon** [comment]
@dagood Is there a rough ETA when the fix will be available?  UWP is blocked on this issue.

**Comment by dagood** [comment]
https://github.com/dotnet/buildtools/pull/2213 made the fix available in BuildTools `master` and https://github.com/dotnet/buildtools/pull/2214 should make the fix available on `release/2.1`. Right now, builds should publish packages fine, but don't publish versions to dotnet/versions. This means it's harder to tell what the latest version is and auto-upgrade won't work, but manual upgrade should be fine. I don't think I was clear about this in the PR threads, sorry about that.

`master`: `3.0.0-preview1-03617-02`
`release/2.1`: `2.1.0-rc1-03620-01`

I pushed through the `master` build primarily to unblock myself in core-setup, but I'm not planning to work on this further.

@stephentoub, @mmitche, @ericstj, do you know who is right to fix up the infra?
(Sorry if this is spam to you, I picked names from recent committers. IIRC dnceng doesn't support buildtools.)

**Comment by dagood** [comment]
Since this affects release branches, dnceng FR can help. Filed https://github.com/dotnet/core-eng/issues/5054.

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
