### ISSUE TITLE
Fix GitHubVersionsRepoUpdater retries for "Update is not a fast forward"

### ISSUE THREAD

**Issue by dagood** [dotnet/buildtools#2221]
`GitHubVersionsRepoUpdater.UpdateBuildInfoAsync` *should* retry when it hits "Update is not a fast forward". That exception simply means some other repo updated dotnet/versions between the beginning of the current update and submission. But it looks like there’s a bug where [GitHubVersionsRepoUpdater.cs#L149](https://github.com/dotnet/buildtools/blob/e4fcde0f2de731312ad10f93428d0c8007e858f6/src/Microsoft.DotNet.VersionTools/Automation/GitHubVersionsRepoUpdater.cs#L149) doesn't catch [`NotFastForwardUpdateException`](https://github.com/dotnet/buildtools/blob/e4fcde0f2de731312ad10f93428d0c8007e858f6/src/Microsoft.DotNet.VersionTools/Automation/GitHubApi/NotFastForwardUpdateException.cs).

This is ironic aftermath of the ProdCon v1 work: I added this exception type so I could add tests that make sure ProdCon v1's build manifest publish will do retries.

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
