### ISSUE TITLE
Using eval dotnet command instead of dotnet command in buildscripts

### ISSUE THREAD

**Issue by Anipik** [dotnet/buildtools#2224]
There has been some recent changes in how dotnet cli parser is parsing the arguments. https://github.com/dotnet/cli/pull/9892

Earlier they were directly passing the  command line arguments to the MSBuild command line as `/p:RestorePackagesPath="/git/packages"`; thus, MSBuild will strip the quotes out when setting the property because it parses its own command line.

But now they are trying to treat `"/git/packages"` as the path to expand before passing the full path to MSBuild. since quotes are valid directory characters, this would expand this path parameter to `<cwd>/"/git/packages"`.

One of the proposed solution
https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.sh#L82

is to convert these lines 
`$__DOTNET_CMD restore "${__PORTABLETARGETS_PROJECT}" $__INIT_TOOLS_RESTORE_ARGS`
to
`eval "$__DOTNET_CMD restore \"${__PORTABLETARGETS_PROJECT}\" $__INIT_TOOLS_RESTORE_ARGS"`

Creating an issue to discuss about the pros and cons of using this solution 

Related issue https://github.com/dotnet/cli/issues/10802

cc @danmosemsft @eerhardt @safern

**Comment by eerhardt** [comment]
Since build tools is basically "dead", we should probably just do whatever it takes to make this work. We will move to arcade, and all of this will be replaced.

**Comment by safern** [comment]
I agree. Also, if eval works with 2.1 SDK then it should technically be safe to do this change. I don't see anyone using an older SDK and using latest buildtools from master.
