### ISSUE TITLE
Can we disable master ?

### ISSUE THREAD

**Issue by danmoseley** [dotnet/buildtools#2269]
@safern @ViktorHofer do the servicing branches of the old repos consume the v3.0 branch? If so would it make sense to tag and delete master in this repo as we did in those? That would help make clear that this repo is dead.

**Comment by safern** [comment]
Machine learning repo is still using buildtools, however I don't know how many fixes they often need... I think the plan for them is already to move to arcade soon, so it might just make sense to delete the master branch. 

cc: @eerhardt @frank-dong-ms

**Comment by frank-dong-ms** [comment]
Can somebody please help us understand the impact of disable master? 
We have a discussion on arcade but seems we don't have bandwidth to move to arcade in near future due to the cost.

cc: @harishsk

**Comment by ViktorHofer** [comment]
I would not delete master before all repos moved off it. My recommendation for dotnet/machinelearning would be to invest in moving to arcade. Maybe @markwilkie's team can help with that?

**Comment by danmosemsft** [comment]
Ah, I didn't realize ML was still on it. Well, if it works..

**Comment by terrajobst** [comment]
Is ML the only repo still using buildtools?

**Comment by safern** [comment]
I think so. I don't know of any other repo using buildtools.

**Comment by eerhardt** [comment]
It's the only one I know of as well.

@harishsk - are there any plans of moving dotnet/machinelearning to arcade?

**Comment by harishsk** [comment]
Yes, we have discussed moving to Arcade internally several times. We had deferred it earlier because we had other blocking test issues and it wasn't clear whether moving to Arcade would improve that. We are now close to resolving our other test issues and we can bring this back on the table. 

Is there a particular timeline you are looking at for the transition?

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
