### ISSUE TITLE
Create Cross-Plat Versions of GenFacades

### ISSUE THREAD

**Issue by mellinoe** [dotnet/buildtools#228]
Right now, we are only producing a Windows version of GenFacades. When we have cross-plat NuGet packages to consume, we should be able to add additional build configurations for other platforms.

**Comment by pgavlin** [comment]
@weshaggard has there been any progress on this? If we have something that even sort-of works, I'd be happy to test things out locally.

**Comment by pgavlin** [comment]
> We are still missing some of the necessary x-plat libraries in the packages. We are hoping to have all the x-plat packages ready in the next week or so and then we should be able to enable this after my work to switch it to run on .NET Core.

Are the packages the only thing that's blocking the cross-plat work? If you can provide a version of GenFacades that runs on .NET Core but does not yet work cross-platform due to the package issues, I can put together the layout myself on my machines.

**Comment by pgavlin** [comment]
Excellent; thanks!

**Comment by weshaggard** [comment]
Yes @dotnet-bot is correct :)

**Comment by mellinoe** [comment]
This is done.
