### ISSUE TITLE
build fails on AArch64, Fedora 33 

### ISSUE THREAD

**Issue by LutzWeischerFujitsu** [dotnet/buildtools#2284]
[jw@cn05 buildtools]$ ./build.sh
dotnet_install: Error: OS name could not be detected
dotnet-install: Downloading https://dotnetcli.blob.core.windows.net/dotnet/preview/Binaries/1.0.0-preview2-1-003182/dotnet-dev--x64.1.0.0-preview2-1-003182.tar.gz
dotnet_install: Error: Download failed
/home/jw/dotnet/buildtools/run.sh: line 14: /home/jw/dotnet/buildtools/Tools/dotnetcli/dotnet: No such file or directory
[jw@cn05 buildtools]$

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
