### ISSUE TITLE
Switch to official xunit console runner

### ISSUE THREAD

**Issue by stephentoub** [dotnet/buildtools#244]
The xunit netcore console runner has drifted significantly from the full xunit console runner.  We should work with the xunit team to incorporate whatever changes are necessary to support .NET Core, and then adopt the official runner in build tools rather than having a forked runner.

**Comment by mellinoe** [comment]
I was hoping we could easily update ourselves, but there are a lot of things that need to be changed in the official runner to make it compatible with .NET Core. Just a few to start:

* System.Configuration dependency, not supported at all in .NET Core
* Assembly loading
* Old reflection usage (some non-replacable, like Assembly.Load(path), Assembly.GetExecutingAssembly, Assembly.CodeBase, etc., others easily replacable)

**Comment by MichaelSimons** [comment]
Triage: this stands to be investigated but the drift might just need to persist. We should look at what it takes to have a blessed test runner going forward.

**Comment by stephentoub** [comment]
Can we take another run at this now?  We're now missing some very useful functionality.  For example, the official xunit console now has support for notifying about long running tests, e.g. as an example I added this test:
```C#
[Fact] public void SleepLong() => System.Threading.Thread.Sleep(30000);
```
and I added this config file:
```C#
{
  "diagnosticMessages": true,
  "methodDisplay": "classAndMethod",
  "longRunningTestSeconds": 3
}
```
after which xunit generates diagnostic output like this:
```
   System.Net.Http.Functional.Tests: [Long Running Test] 'System.Net.Http.Functional.Tests.StringContentTest.SleepLong', Elapsed: 00:00:05
   System.Net.Http.Functional.Tests: [Long Running Test] 'System.Net.Http.Functional.Tests.StringContentTest.SleepLong', Elapsed: 00:00:08
   System.Net.Http.Functional.Tests: [Long Running Test] 'System.Net.Http.Functional.Tests.StringContentTest.SleepLong', Elapsed: 00:00:11
   System.Net.Http.Functional.Tests: [Long Running Test] 'System.Net.Http.Functional.Tests.StringContentTest.SleepLong', Elapsed: 00:00:14
   System.Net.Http.Functional.Tests: [Long Running Test] 'System.Net.Http.Functional.Tests.StringContentTest.SleepLong', Elapsed: 00:00:17
   System.Net.Http.Functional.Tests: [Long Running Test] 'System.Net.Http.Functional.Tests.StringContentTest.SleepLong', Elapsed: 00:00:20
   System.Net.Http.Functional.Tests: [Long Running Test] 'System.Net.Http.Functional.Tests.StringContentTest.SleepLong', Elapsed: 00:00:23
   System.Net.Http.Functional.Tests: [Long Running Test] 'System.Net.Http.Functional.Tests.StringContentTest.SleepLong', Elapsed: 00:00:26
```
Obviously we wouldn't set this for 3 seconds, but we could set it for 1 minute or something like that, and it would be a significant help in tracking down hangs in CI, as until we have better dump support, we'd at least have a very good sense of what test is hanging, just from looking at the console output.  We currently don't have this functionality with the runner we forked off years ago.
cc: @danmosemsft

**Comment by danmosemsft** [comment]
I had a brief look but wasn't successful: https://github.com/dotnet/corefx/issues/20674#issuecomment-306101172
I'm sure it's totally doable and a good idea.

**Comment by ViktorHofer** [comment]
Closing as the buildtools repository has been archived and replace by https://github.com/dotnet/arcade. Aside from that, we switched to the official runner (even though we forked it soon after) some years ago.
