### ISSUE TITLE
Test targets don't copy satellite resource assemblies

### ISSUE THREAD

**Issue by mellinoe** [dotnet/buildtools#246]
It seems like our current test targets (or perhaps resource targets) don't copy over satellite resource assemblies for other languages, if they exist. I could take a stab at this if someone pointed me to where the fix should be made. I mainly wanted this so I could add some tests to ResourceManager that tried grabbing strings from other languages than the default.

**Comment by MichaelSimons** [comment]
Triage: @naamunds can you verify if this was addressed by #1116?

**Comment by sdmaclea** [comment]
This issue still exists see https://github.com/dotnet/corefx/pull/33650#discussion_r236480611

**Comment by sdmaclea** [comment]
@vivmishra @ViktorHofer @ericstj 
This is making it difficult to write localization tests to provide coverage for .Net Core 3.0 

It would be nice to put a 3.0 milestone on this...

**Comment by ViktorHofer** [comment]
As stated for now I would just create a copy target. For a long term solution I think it makes sense to reduce the binplacing we currently do for tests to get back to a sane state.

cc @ericstj

**Comment by ericstj** [comment]
I’ll take a look.

FWIW I don’t think this is a blocking issue.  BinPlacing is really just a convenience for n*m copying and it’s really open ended and extensible. The ability to consider more inputs is already there.

**Comment by sdmaclea** [comment]
> I don’t think this is a blocking issue

It is not for me.  I can get it to work.  As a MSBuild newbie this took ~20 hours so far ...

> The ability to consider more inputs is already there.

The client side extensibility is not obvious to me as a new user.  This could easily be ignorance...

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
