### ISSUE TITLE
GenFacades should not emit nested exported type entries if the nested type is not visible outside the assembly

### ISSUE THREAD

**Issue by nguerrera** [dotnet/buildtools#274]
See [Program.cs#L488](https://github.com/dotnet/buildtools/blob/4607a6f4036458006ed5ca232236bcf345c9b64c/src/GenFacades/Program.cs#L488)

We replicated the behavior of csc.exe at the time. However, some tools get upset when they find an exported type entry that can't resolve even if there is no actual use of the entry encountered. Those tools should be hardened appropriately, but we might as well also help them out by not emitting what isn't necessary.

Things to consider:
* InternalsVisibleTo: I am not certain how type forwards behave relative to it, but I believe it would depend on whether the caller is a friend of the destination. We may want to keep anything that is visible to friends and only cull things invisible outside assembly even in the face of InternalsVisibleTo.

* Check the behavior of Roslyn. Does it still emit these from a [TypeForwardedTo(TopLevelTypeWithPrivateNestedTypes)]?) If so, we should file a bug against the compiler as well.

**Comment by joperezr** [comment]
@nguerrera Thanks for filing the issue, I'll fix this.

**Comment by nguerrera** [comment]
Thanks. I can't assign it to you for some reason, so please assign yourself.

**Comment by nguerrera** [comment]
cc @weshaggard

**Comment by joperezr** [comment]
Closed with #275
