### ISSUE TITLE
Should ToolRuntime be deployed to obj, not bin?

### ISSUE THREAD

**Issue by ellismg** [dotnet/buildtools#286]
Today the runtime to run our tools under gets deployed to a ToolRuntime folder in `$(BaseOutputPath)\$(OSPlatformConfig)`, I think that `$(IntermediateOutputRootPath)` (e.g. `bin\obj\Linux.AnyCPU.Debug`) is a better place for it.  What do you think @weshaggard?

**Comment by weshaggard** [comment]
@ellismg I put it under bin because that is where we deploy the test-runtime as well, however I don't have a strong opinion about this. What benefits do you feel intermediate has over bin?

**Comment by ellismg** [comment]
My preference is that things produced by the build are in bin and things used to produce the build are in obj.  I think both the tools and test runtime should be in obj (and for now when we build out the tests folders for each test, we continue to copy the test runtime into there).

**Comment by weshaggard** [comment]
I'm cool with this. I will try to get this this at some point but feel free to submit a PR.

**Comment by mellinoe** [comment]
Just wanted to add my support for this. I'd like if everything under bin/* were actual product binaries. It would even be nice to split test binaries and framework product binaries into separate directories.

**Comment by joperezr** [comment]
I'll do this now since I need it as part of consuming the new version of buildtools from the coreclr repo. Will send PR soon.
