### ISSUE TITLE
Remove aspnetcore50 folder from xunit.console.netcore NuGet package

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/buildtools#287]
The aspnetcore50 TFM is obsolete.  We should remove it from the xunit.console.netcore NuGet package and update [test.targets](https://github.com/dotnet/buildtools/blob/65d93460c83bdcabfc1c0e53ff74f1f344cafa47/src/Microsoft.DotNet.Build.Tasks/Targets/tests.targets#L47) to refer to a different folder.

**Comment by akoeplinger** [comment]
There are also a couple of [ASPNETCORE50 ifdefs](https://github.com/dotnet/buildtools/search?utf8=%E2%9C%93&q=aspnetcore50) that probably aren't required anymore.

**Comment by weshaggard** [comment]
Triage: we are no longer dependent on aspnetcore50.
