### ISSUE TITLE
Microsoft.DotNet.BuildTools.1.0.25-prerelease-00097 is broken on Linux

### ISSUE THREAD

**Issue by pgavlin** [dotnet/buildtools#292]
...at least on non-Ubuntu distros: an incorrect tool runtime is being deployed, which causes `chmod a+x <ToolRuntimePath>/corerun` to fail.

**Comment by jasonwilliams200OK** [comment]
I am hitting the same issue on FreeBSD, when rehearsing dotnet/coreclr#1633 with CoreFX master.

Thanks for the fix @ellismg! Should we instead pursue to make the name consistent: `corerun` vs. `corerun.exe` vs `CoreRun.exe`? For example I am getting:

> 
  Restoring all packages...
  chmod: /root/corefx/bin/FreeBSD.AnyCPU.Debug/ToolRuntime//corerun: No such file or directory
/root/corefx/packages/Microsoft.DotNet.BuildTools.1.0.25-prerelease-00097/lib/toolruntime.targets(55,5): error MSB3073:
The command "chmod a+x "/root/corefx/bin/FreeBSD.AnyCPU.Debug/ToolRuntime//corerun"" exited with code 1. [/root/corefx/s
rc/dirs.proj]
>
    0 Warning(s)
    1 Error(s)

Here is what I have found:

```
$ find /root/corefx/bin/FreeBSD.AnyCPU.Debug/ToolRuntime -iname "core*"

/root/corefx/bin/FreeBSD.AnyCPU.Debug/ToolRuntime/CoreConsole.exe
/root/corefx/bin/FreeBSD.AnyCPU.Debug/ToolRuntime/coreclr.dll
/root/corefx/bin/FreeBSD.AnyCPU.Debug/ToolRuntime/CoreRun.exe
```
