### ISSUE TITLE
TemporaryTestHost for CoreFX on FreeBSD

### ISSUE THREAD

**Issue by jasonwilliams200OK** [dotnet/buildtools#300]
Currently to run the tests on FreeBSD, one of the stoppers is TemporaryTestHost. We tried building with Linux test-host, but it fails all the tests as discussed here https://github.com/dotnet/coreclr/issues/1633#issuecomment-143669303. The error message when using linux temporary host is:

```
./run-test.sh: line 172:  3844 Abort trap              (core dumped) ./corerun xunit.console.netcore.exe $testDllName -x
ml testResults.xml -notrait category=failing -notrait category=OuterLoop -notrait category=$xunitOSCategory
```

Please make the buildtools available for FreeBSD at:
https://www.myget.org/F/dotnet-buildtools/api/v2/package/Microsoft.DotNet.CoreFx.FreeBSD.TemporaryTestHost/0.0.2-prerelease

which is required at [corefx/run-test.sh#L100-L104](
https://github.com/dotnet/corefx/blob/cb17885/run-test.sh#L100-L104), so we can further our progress.

/cc @mmitche, @akoeplinger, @josteink

**Comment by ellismg** [comment]
After my run-tests.sh work, this is no longer needed.

**Comment by jasonwilliams200OK** [comment]
Thanks @ellismg ! :+1: 
Forgot to close this issue.
