### ISSUE TITLE
Use Console.WindowWidth/Height in the (.NET Core) CommandLine helper

### ISSUE THREAD

**Issue by mellinoe** [dotnet/buildtools#310]
Now that this is supported in the portable System.Console library: https://github.com/dotnet/corefx/issues/3558, we should be able to use it in the command line parsing helper. See:
https://github.com/dotnet/buildtools/blob/master/src/common/CommandLine.cs#L1705

**Comment by MichaelSimons** [comment]
Triage: lower pri cleanup.

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
