### ISSUE TITLE
Marking test as ActiveIssue should not always disable the test

### ISSUE THREAD

**Issue by sepidehMS** [dotnet/buildtools#313]
Currently there is no straight forward way to annotate the test with ActiveIssue without disabling it.

I have couple of tests which do not fail but test design decisions which need to be reevaluated.

I want to annotate the tests so it is easy to find them when fixing the issue but not disable them.

Currently you can workaround by using:

``` csharp
[ActiveIssue(1234, default(PlatformID))]
```

or hacking with Xunit's Trait attribute and passing the right magic values.

**Comment by sepidehMS** [comment]
Should we add PlatformID.None or a new Attribute for that?

**Comment by weshaggard** [comment]
Why do you want to use ActiveIssue for such cases? I would like to avoid using ActiveIssue attribute for things that aren't being disabled. I don't believe this is worth the overloading. If you want to have a marker in the code I would simply put the issue id in a comment or even link to that line in the issue itself.

**Comment by weshaggard** [comment]
Triage: We shouldn't be using ActiveIssue for such cases.
