### ISSUE TITLE
ResolveNugetReferences needs an option to not copy files locally

### ISSUE THREAD

**Issue by ChadNedzlek** [dotnet/buildtools#322]
A recent change was made so that the ResolveNugetReferences now populates the ReferenceCopyLocalPaths item group.  This causes every nuget file to copied locally, with no way to prevent it.

At least one tools needs to be able to prevent that behavior, so that only the built files end up in the output directory.

A property should be created to prevent this default behavior. Perhaps SkipNugetCopyLocal, or something.

**Comment by ChadNedzlek** [comment]
It would still be helpful if the assemblies that *would* have been copied local are saved into an ItemGroup

**Comment by MichaelSimons** [comment]
Triage: @ChadNedzlek please clarify.

**Comment by ChadNedzlek** [comment]
I have no idea, this bug is months old.

**Comment by weshaggard** [comment]
Closing as we don't have the context any more.
