### ISSUE TITLE
Const enums are missing a cast

### ISSUE THREAD

**Issue by billwert** [dotnet/buildtools#355]
This code:

``` csharp
namespace ClassLibrary4
{
    public class Class1
    {
        public const MyEnum Enum = MyEnum.Two;

    }

    public enum MyEnum
    {
        One,
        Two,
        Three
    }
}
```

Turns into this code:

``` csharp
namespace ClassLibrary4
{
    public partial class Class1
    {
        public const ClassLibrary4.MyEnum Enum = 1;
        public Class1() { }
    }
    public enum MyEnum
    {
        One = 0,
        Three = 2,
        Two = 1,
    }
}
```

Which of course doesn't compile.

**Comment by weshaggard** [comment]
Can you be more specific about what this bug is referring to? Is this a bug with GenAPI/Microsoft.CCI.Extensions?

**Comment by billwert** [comment]
Ah, sorry. Not sure where the bug is specifically. I hit it through GenApi.exe.

**Comment by krwq** [comment]
I believe this is what they mean:
```csharp
public const ClassLibrary4.MyEnum Enum = 1;
```

**Comment by billwert** [comment]
Yes.

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
