### ISSUE TITLE
Add an unzip task to the .NET build tools

### ISSUE THREAD

**Issue by livarcocc** [dotnet/buildtools#364]
We can use it to unzip the dotnet cli.

**Comment by joperezr** [comment]
This wouldn't be super helpful once we move into using .NetCore MSBuild, because when that happens, we will need dotnet cli to restore msbuild and wouldn't be able to run a task before that.

**Comment by livarcocc** [comment]
How are you planing to unzip the package you will get for the cli? For mac and linux that easy, just use tar, but for windows I am not aware of a command line to do that. For corefxlab I have a task to do that using System.IO.Compression.FileSystem.ZipFile. However, over there, we use msbuild and then dotnet cli to restore/compile/publish projects.

**Comment by joperezr** [comment]
For now we are calling into a powershell cmdlet to do that in windows. This is the line we have:
```
powershell -NoProfile -ExecutionPolicy unrestricted -Command "(New-Object Net.WebClient).DownloadFile('https://dotnetcli.blob.core.windows.net/dotnet/dev/Binaries/Latest/dotnet-win-x64.latest.zip', '%DOTNET_PATH%' + '\dotnet-win-x64.latest.zip')"
```

This is called from our build.cmd. As I said, my previous comment was very specific to corefx repo, if different repos are not planning on moving to .NetCore msbuild then I guess that a Task in buildtools would be usefull.
