### ISSUE TITLE
BuildTools packaging work

### ISSUE THREAD

**Issue by ericstj** [dotnet/buildtools#366]
Remaining from https://github.com/dotnet/buildtools/pull/351
- [ ] Enable build of nuspecs using coreCLR (requires NuGet API)
- [x] Pack nuspecs
- [ ] Integrate with @weshaggard's build refactoring
- [x] Docs

**Comment by ericstj** [comment]
Docs completed with https://github.com/dotnet/corefx/pull/5013.

**Comment by ericstj** [comment]
Pack PR available: https://github.com/dotnet/buildtools/pull/369

**Comment by weshaggard** [comment]
Triage: I believe this is done.
