### ISSUE TITLE
Validate API version of references

### ISSUE THREAD

**Issue by ericstj** [dotnet/buildtools#370]
A common problem across the repo today is folks building against newer references than are actually needed.  For instance, there are no API changes between 4.0.0 and 4.0.1 but folks build against and depend on the 4.0.1 package.

We should introduce validation to prevent this.

Additionally, we should avoid reshipping packages with no changes if they only contain reference assemblies.  I'm looking into modifying our packaging/versioning strategy to avoid this.

**Comment by weshaggard** [comment]
Trigage: Not really applicable any more.
