### ISSUE TITLE
GenAPI doesn't add "new" keyword on members when required.

### ISSUE THREAD

**Issue by bartonjs** [dotnet/buildtools#379]
I don't know if this requires a cross-assembly inheritance, or what, but i encountered it when rebuilding the contract for System.Security.Principal.Windows:

```C#
public class ClaimsIdentity
{
    public const string DefaultIssuer = "LOCAL AUTHORITY";
    // ...
}

// In a different assembly, if it matters
public class WindowsIdentity : ClaimsIdentity
{
    public new const string DefaultIssuer = "AD AUTHORITY";
    // ...
}
```

When producing the new contract.cs file GenAPI emitted the latter without the keyword `new`, resulting in a compile error.

**Comment by bartonjs** [comment]
@ericstj I feel like you ran into this and fixed it... true?

**Comment by ericstj** [comment]
Indeed.  https://github.com/dotnet/buildtools/commit/7481a711710edf88c04058a3ce2b6368435f77db
