### ISSUE TITLE
MSBuild Exec of $(DnuRestoreCommand) should capture and report stdout and stderr if fails

### ISSUE THREAD

**Issue by roncain** [dotnet/buildtools#381]
Currently, any failure in package restore only says dnu.cmd exited with code -1, which is not useful for debugging what failed.  We see these failures in CI logs and have no idea what happened. The Exec task supports capturing console output, so the .targets files that Exec dnu.cmd should be updated to log any failure messages if dnu.cmd fails.

**Comment by MattGal** [comment]
@roncain  can this be closed given all restore is done from dotnet now?

**Comment by MichaelSimons** [comment]
Triage: not applicable since dnu is no longer used.
