### ISSUE TITLE
Packaging: There is no "public" equivalent to Dependency for pre-release extra references

### ISSUE THREAD

**Issue by bartonjs** [dotnet/buildtools#382]
When a project reference can be made to a prerelease package (from another package) the version gets correctly built with the prerelease versioning stamp.

For manually encoded dependencies, registering a `_FilePackageReference` will accomplish this goal, but with the underscore prefix it suggests it wasn't intended for direct use.

@ericstj asked me to file this to be able to avoid using _FilePackageReference directly from corefx.

**Comment by MichaelSimons** [comment]
Triage: lower-pri.

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
