### ISSUE TITLE
By default, only download the runtime of the host platform

### ISSUE THREAD

**Issue by Clockwork-Muse** [dotnet/buildtools#398]
...and potentially only matching packages too.

With the release of the new build tools, it now downloads the runtimes into the Tools directory.  Unfortunately, it downloads **all** of them, even if they're never going to be used.  

I would imagine most of us are building and running on the same platform, and only one at that.  Those of us building and running on more than one are also most likely hosting on both platforms.  The proportion of runtimes downloaded to used is only going to increase as more runtimes are brought up.  Few people have access to an AS/400, say, if somebody created a runtime for that platform.  Making additional runtime-download opt-in solves this issue.

(Of course, I'm mostly only complaining about this at the moment because the build process has been timing out trying to download the Ubuntu runtime; I'm on Windows and don't have access to another OS...)

**Comment by weshaggard** [comment]
@Clockwork-Muse can you point out which runtime files you are referring too here? I wouldn't expect us to be download/creating a tool-runtime for any OS other then the one we are running on.

**Comment by Clockwork-Muse** [comment]
@weshaggard - strange, I can't find them now.  Looks like it might have resolved itself - I re-cloned the project and rebuilt the tools directory as part of trying to get things working for me again.

Sorry, I should have included a list of things it was attempting to download.  I can't remember where it was they were ending up, but it was attempting to grab package `runtime.ubuntu.14.04-x64-Microsoft.NETCore.Runtime.CoreCLR` (and timing out), among others.

**Comment by weshaggard** [comment]
Perhaps there was an intermittent state but I wouldn't have expected us to be downloading that on windows. If you see us doing something strange like that again please capture what you are seeing and I can take a deeper look.
