### ISSUE TITLE
ValidatePackage task doesn't fail the build when it fails

### ISSUE THREAD

**Issue by weshaggard** [dotnet/buildtools#401]
@ericstj ValidatePackage task doesn't fail the build when it fails. See http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/windows_nt_debug_prtest/1117/consoleFull as an example where the package validation failed but the exit code of msbuild was 0.

**Comment by weshaggard** [comment]
I suspect we are going to need to do something like https://github.com/dotnet/corefx/blob/master/dir.traversal.targets#L77

**Comment by ericstj** [comment]
This does now fail the build
