### ISSUE TITLE
Remove tool-runtime project.json and move all of those dependencies into the package declared dependencies.

### ISSUE THREAD

**Issue by joperezr** [dotnet/buildtools#413]
Currently we restore the runtime for the build tools package by restoring a specific project.json inside the package. What we want to do, is to change this such that the package itself should declare the runtime dependencies and we should remove that project.json.

The steps required for this are:
- [x] In BuildTools repo: Move dependencies from tool-runtime.project.json into the BuildTools package dependencies list. (Available in branch AddBuildToolsPackageDependencies)
- [ ] In Corefx repo: Update the version of BuildTools consumed.
- [ ] In Corefx repo: Change init-tools.sh to publish the runtime of the buildtools dependencies.

**Comment by am11** [comment]
@joperezr, is this issue still up for grabs? I looked a bit, but not sure if it is already resolved in CoreFX. Related to this. are all the `project.json` files going to be converted to `csproj` from CoreFX and CoreCLR repos? For example, the SOS debug extension project (`coreclr/src/ToolBox/SOS/NETCore/project.json`) and some other projects are still using `project.json` files.

**Comment by joperezr** [comment]
hello @am11, this is not yet resolved in CoreFx as we still need to eventually move all of buildtools dependencies into package dependencies, as opposed to having to restore/publish a project.json as we do today. I did mark it as up for grabs, but it is not a trivial issue, as I believe it does require some background in order to complete.

> Related to this. are all the project.json files going to be converted to csproj from CoreFX and CoreCLR repos?

CoreFx has already removed most of its project.json files, and now we are strictly only restoring external dependencies. If you sync to latest in master, you'll see how there are hardly any left.
For CoreClr we haven't fully moved to this model (called 'Build from Source') but just like in corefx, we will still need to keep some project.jsons for things that are built externally

**Comment by am11** [comment]
Thanks for the answer @joperezr!

> some project.jsons for things that are built externally

I was wondering, will those project.json be replaced by the latest SDK/CLI csproj equivalents at some point. For instance: 

```json
  "frameworks": {
    "netstandard1.4": {
      "dependencies": {
        "System.Collections": "4.3.0",
        "System.Collections.Concurrent": "4.3.0",
        "System.Runtime.Serialization.Primitives": "4.3.0"
    }
  }
```

will become:

```xml
<!-- csproj -->
<ItemGroup Condition=" '$(TargetFramework)' == 'netstandard1.4' ">
  <PackageReference Include="System.Collections" Version="4.3.0" />
  <PackageReference Include="System.Collections.Concurrent" Version="4.3.0" />
  <PackageReference Include="System.Runtime.Serialization.Primitives" Version="4.3.0" />
</ItemGroup>
<!-- etc. -->
```

**Comment by joperezr** [comment]
I believe that is the plan in the long term yes, and maybe even use the CLI to build the repo instead of using msbuild, but it's not what we are focusing now.

**Comment by MichaelSimons** [comment]
Triage: this will be supplanted by buildtools bootstrapping work.

**Comment by weshaggard** [comment]
Triage: bootrapping issue
