### ISSUE TITLE
Move the portable targets dependency with the rest of the runtime dependencies once dotnet cli supports content files

### ISSUE THREAD

**Issue by joperezr** [dotnet/buildtools#414]
Currently the CLI doesn't support content files so we need a workaround to manually copy some folders and files into the build tools runtime. Once dotnet supports them, we should remove this workaround.

**Comment by joperezr** [comment]
This work is currently blocked until dotnet cli supports content files.

**Comment by weshaggard** [comment]
@joperezr can you link against the CLI issue.

**Comment by joperezr** [comment]
I'm not sure if it is exactly what we need, but there is this existing issue dotnet/cli#66 which is currently in progress.

**Comment by MichaelSimons** [comment]
Triage: bootstrap issue.

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
