### ISSUE TITLE
Why do some nuget packages have netcore50 and dnxcore50 but not dotnet5.X

### ISSUE THREAD

**Issue by CppStars** [dotnet/buildtools#424]
Some packages like System.Dynamic.Runtime don't have the dotnet5.4 package in libs, have have a ref and in libs it is only dnxcore50 and netcore50

Can you explain this discrepancy?

**Comment by ericstj** [comment]
We're just in the middle of moving things to choose defaults and package those as "dotnet".  In most cases we try to package one implementation as the default and then special case the other, the goal being that a future TFM can ideally use the default.

Expect by the next RC that any package applicable to both NETCore and DNXCore has one asset packaged as DotNet.  This is part of the work planned to enable "netstandardapp".
