### ISSUE TITLE
Fix no Revision Number on buildtools packages after moving away from nuget.exe

### ISSUE THREAD

**Issue by joperezr** [dotnet/buildtools#430]
With [my change](https://github.com/dotnet/buildtools/pull/416) for moving away from nuget.exe and using NugetPack instead, I introduced a bug where the package version does not contain a revision number any more.

**Comment by bryanar** [comment]
Test

**Comment by joperezr** [comment]
This was fixed by adding nuget.exe back. For the time being this is the plan since Nuget.exe is still required for the 'pushing' of the packages. Hopefully dotnet will support push command, so we don't depend on nuget.exe anymore.
