### ISSUE TITLE
Provide helper script for computing rid for a *NIX platform

### ISSUE THREAD

**Issue by ellismg** [dotnet/buildtools#437]
Everyone is doing their own thing in different ways.  We should have a common script that does the work of reading `/etc/os-release` and friends and computing a rid.

**Comment by MichaelSimons** [comment]
Triage: we need a design to share this logic.

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
