### ISSUE TITLE
DropURI property has incorrect value

### ISSUE THREAD

**Issue by rahku** [dotnet/buildtools#460]
Below lines in CreateAzureStorage target in cloudtest.targets is not correct:
    
    <CreateProperty Value="$(DropUriRoot)/$(BuildArch)$(BuildType)">
      <Output TaskParameter="Value" PropertyName="DropUri" />

ListURI does not have $(BuildArch)$(BuildType) in its path. It works in corefx because they don't specify any property BuildArch and BuildType. This needs to be fixed. Coreclr does specify these two properties.

**Comment by jhendrixMSFT** [comment]
This has been fixed and will show up in build tools version 00172.
