### ISSUE TITLE
Make time out for tests configurable

### ISSUE THREAD

**Issue by rahku** [dotnet/buildtools#467]
In cloudtest.targets there is no option to configure timeout for the tests. This is required for some of the long running tests in coreclr

       </FunctionalTest>
        <Command>$(HelixPythonPath) $(RunnerScript) --dll %(Filename).dll $(OtherRunnerScriptArgs) -- $(XunitArgs)</Command>  
            <CorrelationPayloadUris>[$(CorrelationPayloadUris)]</CorrelationPayloadUris>  
            <PayloadUri>$(DropUri)$(Platform)$(ConfigurationGroup)/Tests/%(Filename)%(Extension)$(DropUriReadOnlyToken)</PayloadUri>  
            <WorkItemId>FunctionalTest.%(Filename)</WorkItemId>  
       </FunctionalTest>

**Comment by jhendrixMSFT** [comment]
Fix will appear in build tools version 00174.
