### ISSUE TITLE
Add support for merging IBC training data into libraries

### ISSUE THREAD

**Issue by weshaggard** [dotnet/buildtools#476]
As a optimization step a number of libraries like System.Reflection.Metadata and System.Collections.Immutable embed some IBC training data so when they get ngen'ed they will be more optimized for particular scenarios. Currently we don't have a way to do this in our open source builds which is what this issue is tracking.

**Comment by markwilkie** [comment]
Wes - I think I heard you mention this was done?

**Comment by weshaggard** [comment]
Yes @AlexGhiondea has completed this.
