### ISSUE TITLE
GenFacades should have a dedicated MSBuild task

### ISSUE THREAD

**Issue by mellinoe** [dotnet/buildtools#482]
I did a quick experiment to see how much faster a dedicated task would be for GenFacades rather than having to launch an entirely new process. Right now, when building System.Runtime.builds in corefx (which builds 3 facades), my machine takes about 3500 ms on the FillPartialFacade task (from a diagnostic log) out of a total 16000 ms. After switching to a dedicated build task, that number dropped to around 700 ms. This seems like a relatively easy thing to change for a decent speedup. Since we are building so many facades individually now (instead of running GenFacades once in batch), it probably makes sense to make this optimization.

My rough work on this is here: https://github.com/mellinoe/buildtools/commit/e26d50f22dbca41455b2ad2b6524d7c3dfe8b3a0. Note that this could be even faster because I am just passing all of the arguments from MSBuild in a single string and parsing them again in the GenFacades code. Instead, we could just pass them as real task properties because they are already stored in the form we need them in the MSBuild target. That probably represents a not-insignificant speedup, as well.

Ideally GenFacades would be split into three components:
- A shareable library with the actual logic in it, accepting strongly-typed parameters; does no parsing of any kind.
- A Console program which parses command-line arguments and passes them to the shareable library.
- An MSBuild task which accepts pre-processed arguments as task properties and passes them to the shareable library.

@weshaggard

**Comment by mellinoe** [comment]
A better version which separates out the components as outlined above is here: (https://github.com/mellinoe/buildtools/tree/genfacades-task)

**Comment by weshaggard** [comment]
I like this idea thanks for filing the work item.

**Comment by mellinoe** [comment]
@weshaggard Can we do this now, for GenFacades and ApiCompat? Are we running these at all in TFS / Razzle anymore?

**Comment by weshaggard** [comment]
We just turned off our TFS mirror but I'm hesitant to start knowingly breaking that here. I think we should hold off a little more here or at least make it additive.

**Comment by mellinoe** [comment]
@weshaggard I did another take of my changes here: https://github.com/dotnet/buildtools/compare/master...mellinoe:genfacades-buildtask

It would be awesome if we could move forward with it, but it requires moving the "desktop tool-runtime" (corefx/tools/net45) to net46 from net45, because Microsoft.Cci only supports netstandard1.3. Personally I think we should really just bite the bullet and ignore razzle support since it's been holding us back for so long...

**Comment by weshaggard** [comment]
>Personally I think we should really just bite the bullet and ignore razzle support since it's been holding us back for so long...

I don't want to make that decision in isolation. @Petermarcu @gkhanna79 @ericstj @markwilkie What are your guys thoughts on moving forward buildtools such that it will no longer work in razzle?

**Comment by ericstj** [comment]
+1.  The only reason it doesn't work in Razzle is the franken build of private framework (not quite 4.5, not quite 4.6).  Folks can fix that if they want to use it.

**Comment by markwilkie** [comment]
+1  Double checking we can still build sni?  cc @dleeapho

**Comment by gkhanna79** [comment]
SNI still builds in TFS though they are working to move to open. If they cannot, then we can consider moving them to other non-TFS build options as @markwilkie and I discussed today.

Given that, I think it should be fine to drop razzle support since we dont intend to build there. However, if there is no impending rush to get this, I would suggest we wait until end of next week to ensure stopping the mirror has no one broken (nothing came out so far as broken).

**Comment by dleeapho** [comment]
+1 on discarding razzle support for buildtools but also agree with @gkhanna79 to wait until end of next week as a precaution.

**Comment by weshaggard** [comment]
Done with https://github.com/dotnet/buildtools/pull/1222.
