### ISSUE TITLE
ApiCompat uses floating NuGet version numbers causing build failures.

### ISSUE THREAD

**Issue by jhendrixMSFT** [dotnet/buildtools#485]
Build tools no longer builds after a recent merge to add ApiCompat tools (see https://github.com/dotnet/buildtools/pull/415).  Here's an example.

D:\git\buildtools\build.proj(38,5): error : Floating dependency detected: Microsoft.Cci 4.0.0-* in D:\git\buildtools\src\ApiCompat\project.json

**Comment by jhendrixMSFT** [comment]
Here's another example.

D:\git\buildtools\build.proj(38,5): error : Dependency validation error: for System.Console 4.0.0-* in D:\git\buildtools\src/ApiCompat\project.json package prerelease is '-', but expected 'rc2-23816' for packages matching '^((System\..*)|
(Microsoft\.CSharp)|(Microsoft\.NETCore.*)|(Microsoft\.Win32\..*)|(Microsoft\.VisualBasic))(<!TestData)$'

**Comment by venkat-raman251** [comment]
Fixed #486
