### ISSUE TITLE
Depend on existing project model for project(.lock).json validation

### ISSUE THREAD

**Issue by dagood** [dotnet/buildtools#517]
Currently we use Json.NET calls which were coded only to the scenarios I've encountered. Using an existing library that creates models from project.json files removes the logic duplication. A project model will also be more resilient to changes in the lockfile and project.json file formats.

For example, we could use `NuGet.ProjectModel` or `Microsoft.DotNet.ProjectModel`.

This needs to apply to the project.json validation and post-restore lockfile validation. Depending on whether these project models are mutable, there may be more difficulty changing auto-upgrade.

**Comment by MichaelSimons** [comment]
Triage: we don't want to do this because we want to limit dependencies.
