### ISSUE TITLE
Errors in restore for init-tools scripts

### ISSUE THREAD

**Issue by joperezr** [dotnet/buildtools#523]
When using the new version of the dotnet cli (which in fact is the one used by our repos) the init-tools.log show the following errors:
```
error: Microsoft.DotNet.BuildTools 1.0.25-prerelease-00193 is not compatible with DNXCore,Version=v5.0.
error: Some packages are not compatible with DNXCore,Version=v5.0.
error: Microsoft.DotNet.BuildTools 1.0.25-prerelease-00193 is not compatible with DNXCore,Version=v5.0 (win7-x64).
error: Some packages are not compatible with DNXCore,Version=v5.0 (win7-x64).
error: Microsoft.DotNet.BuildTools 1.0.25-prerelease-00193 is not compatible with DNXCore,Version=v5.0 (win7-x86).
error: Some packages are not compatible with DNXCore,Version=v5.0 (win7-x86).
info : Committing restore...
log  : Restore failed in 5912ms.
Errors in C:\Users\joperezr\Desktop\repo\coreclr\Tools\1.0.25-prerelease-00193\project.json
    Microsoft.DotNet.BuildTools 1.0.25-prerelease-00193 is not compatible with DNXCore,Version=v5.0.
    Some packages are not compatible with DNXCore,Version=v5.0.
    Microsoft.DotNet.BuildTools 1.0.25-prerelease-00193 is not compatible with DNXCore,Version=v5.0 (win7-x64).
    Some packages are not compatible with DNXCore,Version=v5.0 (win7-x64).
    Microsoft.DotNet.BuildTools 1.0.25-prerelease-00193 is not compatible with DNXCore,Version=v5.0 (win7-x86).
    Some packages are not compatible with DNXCore,Version=v5.0 (win7-x86).
```

For now, it doesn't really have an impact since restore is being done despite the errors, but we should address that by making BuildTools package dnxcore compliant.

cc: @weshaggard @dagood

**Comment by dagood** [comment]
Would this be as simple as adding `netstandard1.0\_._` or `dnxcore50\_._` or something as a placeholder? They work, but I don't know if we wanted something other than a placeholder.

/cc @ericstj

**Comment by ericstj** [comment]
Yeah, just add a placeholder to make nuget happy is a easy fix.

Alternatively if we can make this thing a "real" package (eg a dotnet CLI-friendly library or app) it would just work.

**Comment by dagood** [comment]
Closing this because the immediate issue has a merged fix.

For making buildtools a proper library/app package, does https://github.com/dotnet/buildtools/issues/413 represent that work or is there something more that we should make a new issue for?

**Comment by joperezr** [comment]
@dagood 
> For making buildtools a proper library/app package, does #413 represent that work or is there something more that we should make a new issue for?

That is the PR for making buildtools a proper package, but I'm still having issues in some platforms so I paused that work to focus on other things, I plan to get back at it either tomorrow or next week.

**Comment by dagood** [comment]
Cool, thanks. (No hurry as far as I'm concerned, just wanted to make sure an issue exists for the change.)
