### ISSUE TITLE
init-tools.cmd/.sh per repo should be simpler.

### ISSUE THREAD

**Issue by ellismg** [dotnet/buildtools#558]
Today, each repository has a bunch of logic in `init-tools.sh` and `init-tools.cmd` to download the correct version of dotnetcli, restore build tools and then call the stage two scripts.

This logic is starting to differ across corefx and coreclr, for no good reason.

I propose we do the following:
1. Tag our git repository with the build tools version number, each time we update it.
2. Add a file in this repository that does what init-tools.cmd/.sh does today (downloads the cli, creates and restores a project.json and then jumps into init-tools.sh/init-tools.cmd from the package).  Call this file bootstrap-tools.sh or something
3. Change init-tools.cmd/.sh in each repository to read the BuildTools version from the text file, then download the newly added script via a stable location (`https://raw.githubusercontent.com/dotnet/buildtools/<tag-name>/<path-to-bootstrap-tools.sh>`) and invoke that.  If we want to add a very simply check to invoke some other file instead (for local development) via something like an environment `PATH_TO_BOOTSTRAP_TOOLS`, that's fine.

Now all the logic about figuring out the distro/version, allowing overrides of different pacakges, etc. can be in a common location.

Now init-tools.cmd has very little logic that has to be duplicated across repositories.  Going forward we would consider it an anti-pattern to have to edit the init-tools file in the repository

If we do this, it might be a good idea to change the name of the `init-tools` that we call via bootstrapping to something like `deploy-tools` so each script has a unique name.

Does this seem reasonable?

**Comment by weshaggard** [comment]
cc @joperezr 

I like the general direction and completely agree with trying get the script to a point where it essentially should never need to be updated again to avoid the divergence problem. 

@ellismg is this something you want to try tackling?

**Comment by ellismg** [comment]
> @ellismg is this something you want to try tackling?

Sure.

**Comment by dagood** [comment]
This discussion probably happened a long time ago, but have git submodules been considered for this? From what I understand that would also remove the need for a bootstrap bat/sh. I'll be the first to admit that they aren't the most intuitive git feature, but I'm curious if they've been considered.

**Comment by weshaggard** [comment]
We have considered git sub-modules for various things (not sure if we did for this specific instance) but in general we have been very hesitate to use them because they add another layer of complexity. Whether or not that complexity matches the complexity of our init-tools I don't know but I think part of the problem is there is a fair amount of FUD around sub-modules with no one having any real experience with them.

**Comment by markwilkie** [comment]
Would this be the right time to think more about sharing the script itself across platforms?  Perhaps use c# on core?  Maintaining one version for windows and another for Linux seems lame...

**Comment by weshaggard** [comment]
@markwilkie not for this script as it is the lowest level and is what is boot-strapping dotnet cli. We could consider using C# for some of the higher level scripts but personally I think that might be overkill right now as my ultimate goal is that we have as little as possible in these cmd/sh scripts and most of the heavy lifting should be in the build engine (i.e msbuild in our case).

**Comment by dagood** [comment]
@weshaggard Ok, that makes sense. I did use submodules successfully on a team before, but it was only 4 people. Another downside is that submodules would make the TFS mirror quite a bit more complex depending on how far we wanted to support it there.

As for the general issue, I think it's a great idea to centralize and that plan looks fine to me. One thing I'm thinking we might want to add is a way for the corefx/etc. script to tell if the version stored in git has changed and clean/redownload. Maybe just a semaphore with the downloaded version.

(I think we should make a distinct name for the init-tools.cmd/sh in buildtools too, while we're at it.)

**Comment by ellismg** [comment]
> One thing I'm thinking we might want to add is a way for the corefx/etc. script to tell if the version stored in git has changed and clean/redownload. Maybe just a semaphore with the downloaded version.

I think this is a great idea and I'll incorporate it.

**Comment by joperezr** [comment]
@ellismg I like your suggestion about the centralized place. If we are planning to put this in Build tools though, will they be also part of the package? I suppose the answer is no, so that we can avoid confusion since there will now be two different init-tools.cmd and two init-tools.sh on the same repo.

**Comment by ellismg** [comment]
> I suppose the answer is no, so that we can avoid confusion since there will now be two different init-tools.cmd and two init-tools.sh on the same repo.

I'd like to have init-tools.sh/cmd be the simple script that downloads bootstrap-tools.sh/cmd (which is responsible for figuring out how to get you a CLI and restoring the buildtools package, basically what "init-tools" in each repo does today) from GitHub, based on your BuildToolsVersion.txt.  bootstrap-tools does the package restore and then calls "deploy-tools" which is the logic we have [here](https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.sh) today.  Only deploy-tools ends up the package.  bootstrap-tools is in a well known location in this repository (so it has a stable place for init-tools to find it) and init-tools is in the root of the repository and what we expect anyone using buildtools brings into their repository as well.

**Comment by weshaggard** [comment]
As part of this we should also consider using these for bootstrapping the cli. 
•	https://dot.net/dotnet-install.sh
•	https://dot.net/dotnet-install.ps1

**Comment by MichaelSimons** [comment]
Triage: bootstrap issue.

**Comment by omajid** [comment]
What's the source of https://dot.net/dotnet-install.sh? Say I wanted to make a change to the install script. How would I go about it?

**Comment by ellismg** [comment]
@blackdwarf Can you answer @omajid's question above?

**Comment by blackdwarf** [comment]
@omajid https://github.com/dotnet/cli/tree/rel/1.0.0/scripts/obtain is the source. The ones on the dot.net site could be older, so using the repo version should be preffered. Any changes should be made as PRs on the CLI repo. And yes, if you need a boostraping thing, these scripts should help.

**Comment by omajid** [comment]
@blackdwarf, thanks.The cli version of dotnet-install.sh is where I have been trying to get my changes into. Good to know https://dot.net/dotnet-install.sh is based on that.

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
