### ISSUE TITLE
Support multiple conditions in [ConditionalFact]

### ISSUE THREAD

**Issue by roncain** [dotnet/buildtools#610]
[ConditionalFact] currently accepts only a single member name to invoke, and if it returns 'false' provides only a canned [SKIP] message "{membername} returned false".  But in practice we have situations where multiple conditions must be met before a test can be run.  And if it is not run, we want to know which condition was not met.

I see 2 potential approaches:

1. (Preferred) Modify ConditionalFactAttribute to accept a params collection of member names.  At runtime, execute each in turn and make the [SKIP] message reflect which one returned false.

2. Modify ConditionalFactAttribute to optionally invoke a member capable of returning a more meaningful [SKIP] message.  That way, a single member could perform multiple condition checks and report which one was not met.

**Comment by roncain** [comment]
If there is agreement this enhancement is reasonable, feel free to assign it to me.

**Comment by stephentoub** [comment]
I think there's a 3rd option as well:
3. In addition to (1) and allowing the number of members to be 0 (which would translate to the condition passing), allow the body of the test to throw a particular exception and have that interpreted to mean that the test should be skipped, using the exception's message as the skip reason.  Sometimes it's easier to do the skip testing inside the method.

My preference would be (3), but as (1) would be a precursor to it, I'd be fine with that as a starting point.
