### ISSUE TITLE
Don't strip System.Private references from dependencies if package exists

### ISSUE THREAD

**Issue by ericstj** [dotnet/buildtools#617]
We strip out all System.Private references from dependencies: https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets#L478

This causes folks who build against a System.Private package to manually sepecify the reference: https://github.com/dotnet/wcf/blob/6b79b1193b5f213cee8f93fb5fe98982c311ab1b/src/System.ServiceModel.Duplex/pkg/System.ServiceModel.Duplex.pkgproj#L14

Which ineveitably gets out of sync with the project's PackageTargetFramework.

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
