### ISSUE TITLE
"Built By" version string in the non-Windows builds can't get the computer name or username

### ISSUE THREAD

**Issue by joperezr** [dotnet/buildtools#621]
We should figure out a way of getting this info in non-Windows machines.

cc: @gkhanna79

**Comment by bartonjs** [comment]
```
jbarton@jsb-ubuntu2:~/coreclr$ whoami
jbarton
jbarton@jsb-ubuntu2:~/coreclr$ hostname
jsb-ubuntu2
jbarton@jsb-ubuntu2:~/coreclr$ which whoami
/usr/bin/whoami
jbarton@jsb-ubuntu2:~/coreclr$ which hostname
/bin/hostname
```

**Comment by joperezr** [comment]
awesome, do you know if this two commands are available in all Linux distros?

**Comment by bartonjs** [comment]
They've been on every Unix system I've ever used.  And they're common enough that they're part of BusyBox.  https://busybox.net/downloads/BusyBox.html#commands
