### ISSUE TITLE
Long sub-paths in Microsoft.DotNet.BuildTools

### ISSUE THREAD

**Issue by anurse** [dotnet/buildtools#632]
`Microsoft.DotNet.BuildTools` has a very long sub-path in it, which makes it prone to long-path issues on Windows.

I've ended up with a path like this in my dotnet/cli clone: `C:\Users\anurse\Code\dotnet\cli\pkg\packages\Microsoft.DotNet.BuildTools\1.0.25-prerelease-00228-02\lib\portableTargets\packages\Microsoft.Portable.Targets\0.1.1-dev\contentFiles\any\any\Extensions\Microsoft\Portable\v5.0\Microsoft.Portable.VisualBasic.targets` which works out to 260 characters, AKA `MAX_PATH` :(.

I realize I could shorten some of my own paths to manage this, but the sub-path within the package is 160 characters (excluding the package ID and version), which gives users very little space to work with :).

Is there any way to shorten the paths to these items?

/cc @eerhardt @weshaggard

**Comment by joperezr** [comment]
Yes, we will basically move the restore to the top packages dir. I'll take care of this.
