### ISSUE TITLE
Code coverage results should exclude xunit.* assemblies

### ISSUE THREAD

**Issue by iamjasonp** [dotnet/buildtools#637]
When reporting code coverage, we currently include all the xunit.* assemblies with our code coverage numbers, which is skewing the percentages being reported, and not generally useful in a report which should cover just the product. 

We should exclude the xunit.* assemblies from reporting. 

At a glance from the [corefx Code Coverage report](http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/code_coverage_windows/Code_Coverage_Report/)
* xunit.assert
* xunit.core
* xunit.execution.desktop	
* xunit.execution.dotnet
* xunit.performance.core
* xunit.performance.execution.desktop
* xunit.performance.execution.dotnet
* xunit.runner.utility.desktop
* xunit.runner.utility.dotnet

**Comment by stephentoub** [comment]
Interesting.  Something must have changed very recently, as these didn't use to be included.  You can see in the report from Monday that they weren't included (http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/code_coverage_windows/221/artifact/bin/tests/coverage/index.htm), and then starting on Tuesday they are (http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/code_coverage_windows/221/artifact/bin/tests/coverage/index.htm).  It'd be interesting to understand what changed, e.g. did we start deploying xunit.* PDBs that would allow the code coverage tools to work on these binaries?

Regardless, the fix should be simple, just adding ``` -[Xunit.*]*``` to the filter parameter at
https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks/PackageFiles/CodeCoverage.targets#L39

Feel free to submit a fix.
