### ISSUE TITLE
Remove baseline targets from BuildTools.

### ISSUE THREAD

**Issue by ericstj** [dotnet/buildtools#639]
See discussion https://github.com/dotnet/buildtools/pull/638

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
