### ISSUE TITLE
GenAPI generates custom attributes with references to private types

### ISSUE THREAD

**Issue by ericstj** [dotnet/buildtools#658]
Bug is here: https://github.com/dotnet/buildtools/blob/b6663b70b5956f352af75d7d9accf89baa13929c/src/Microsoft.Cci.Extensions/Filters/PublicOnlyCciFilter.cs#L66

We need to check the visibility of all the types used in the custom attribute arguments.

An easy repro is to run GenAPI on an assembly with public async methods/events.
GenAPI will generate source like:
`[System.Runtime.CompilerServices.AsyncStateMachineAttribute(typeof(MyType.<MyAsyncMethod>d__13))]` where `MyType.<MyAsyncMethod>d__13` is private (not to mention invalid C# syntax).

To workaround this you can specify -excludeApiList with an exclusion file containing
```
T:System.Runtime.CompilerServices.AsyncStateMachineAttribute
T:System.Runtime.CompilerServices.IteratorStateMachineAttribute
```
There may be other attributes that need exclusion, but this pattern should work as a temporary workaround.

/cc @dotMorten

**Comment by ratishphilip** [comment]
@ericstj 
I am facing the same issue.
I have added the NuGet package to my project. My project contains a public async method.

Could you provide details about how I can specify an -excludeApiList. Where should the exclusion file be placed?

**Comment by ericstj** [comment]
You can put the exclusion file anywhere, for instance in your project root, eg: excludeApis.txt

Then in the project file, you just need to specify some additional parameters to pass to genapi.

For example:
```xml
<PropertyGroup>
  <GenAPIAdditionalParameters>$(GenAPIAdditionalParameters) -excludeApiList "$(MSBuildProjectDirectory)\excludeApis.txt"</GenAPIAdditionalParameters>
</PropertyGroup>
```

**Comment by ratishphilip** [comment]
@ericstj 
Thank you very much. 👍

**Comment by ratishphilip** [comment]
@ericstj 
Can we expect this bug to be fixed in the near future so as to avoid this workaround?

**Comment by ericstj** [comment]
I haven't looked at what a fix would look like here.  I'll mark this one up-for-grabs so anyone can pick it up.  /cc @mellinoe @weshaggard

**Comment by ericstj** [comment]
Fixed in https://github.com/dotnet/buildtools/pull/922

**Comment by ratishphilip** [comment]
@ericstj  Will the updated NuGet package be available soon?

**Comment by ericstj** [comment]
@ratishphilip you can always pick up builds from https://dotnet.myget.org/gallery/dotnet-buildtools (https://dotnet.myget.org/F/dotnet-buildtools/).  If we get a few folks testing this out we can push it to nuget.org.

**Comment by ratishphilip** [comment]
@ericstj 
I took the latest build from the location you specified and now I see that in the generated **.cs** file, earlier each of the method used to return the default value of the return type.
Now instead of that each method has **throw null;** statement.
Is this intended? Could you please explain the reason behind this change?

**Comment by ericstj** [comment]
Looks like this was changed by @KrzysztofCwalina with https://github.com/dotnet/buildtools/commit/10cef454e30604e6276459e91371ecffbf72345c because the throw null resulted in a smaller assembly size.  Krzysztof, did you consider making this configurable with a parameter?  That's what we already do with ['-throw'](https://github.com/dotnet/buildtools/blob/a23227c69643783164e24dcdda5782be9a6507f3/src/GenAPI/Program.cs#L203)  /cc @weshaggard

**Comment by ratishphilip** [comment]
ok. 
My doubt is will these throw statements actually raise an exception? Or they will be ignored when the package is referenced?

**Comment by ericstj** [comment]
This tool is for creating reference assemblies which are never used at runtime, only compile time.  The compiler won't execute the code so these throws will never be seen.  Most of our reference assemblies also use the [ReferenceAssemblyAttribute](https://msdn.microsoft.com/en-us/library/system.runtime.compilerservices.referenceassemblyattribute(v=vs.110).aspx) which prevent the assembly from even being loaded for execution.

**Comment by ratishphilip** [comment]
Thanks for the clarification.
