### ISSUE TITLE
Support 0 for *TokenDaysValid in CreateAzureContainer

### ISSUE THREAD

**Issue by chcosta** [dotnet/buildtools#667]
We aren't currently using the ReadOnlyToken or WriteOnlyToken tokens in CreateAzureContainer anywhere (or even retrieving them), but a token expiration of 0 causes a warning in the build.  0 should be a supported value implying, don't give me a token.

This issue was mentioned by @jhendrixMSFT in PR #666

**Comment by karajas** [comment]
This should be resolved by now.
