### ISSUE TITLE
BUILDTOOLS_OVERRIDE_RUNTIME no longer works

### ISSUE THREAD

**Issue by ellismg** [dotnet/buildtools#670]
The logic in our init scripts for handling `BUILDTOOLS_OVERRIDE_RUNTIME` no longer works (it assumes path layouts that matched what we had when we used a DNX based CLI, but no longer works with the new layout.

**Comment by ellismg** [comment]
In addition to the new layout there are a few additional issues:

1. The runtime that CLI now uses only contains mscorlib.ni.dll, but not the IL only image.  This means the logic to remove mscorlib.ni.dll will result in a runtime that does not boot unless `BUILDTOOLS_OVERRIDE_RUNTIME` points to a folder that also includes an MSIL mscorlib.dll
2. By default, all the rest of the IL images are going to be compiled as Ready To Run.  I'm not certain what coupling exists between the runtime and R2R images.  Is it safe to replace the runtime with a different version without touching the R2R images?

I think long term we should see if CLI can produce a "bootstrapping" CLI for us, that we use in the cases where `BUILDTOOLS_OVERRIDE_RUNTIME` is set.  This would have an IL image for mscorlib, and may not be R2R compiled.

**Comment by JonHanna** [comment]
Is there an alternative way to test a coreclr change against a corefx test in the meantime?

**Comment by weshaggard** [comment]
Triage: No longer applicable with the flat layout.
