### ISSUE TITLE
Race in ArchiveTestBuild target

### ISSUE THREAD

**Issue by chcosta** [dotnet/buildtools#687]
There is a race in the ArchiveTestBuild target of publishtest.target - https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks/PackageFiles/publishtest.targets#L232

The DestinationArchive path doesn't take into account that a test library may be built for different target groups.  See https://github.com/dotnet/corefx/blob/master/src/System.Globalization.Extensions/tests/System.Globalization.Extensions.Tests.builds for an example of where a test library is built for different targets in the CoreFx build.

The result is that you will attempt to create the same zip file with different content..
```
 116:2>ArchiveTestBuild:
         Compressing D:\A\_work\15\s\bin/Windows_NT.AnyCPU.Release/System.Globalization.Extensions.Tests/net46/ into D:\A\_work\15\s\bin/tests/Windows_NT.AnyCPU.Release/archive/tests/System.Globalization.Extensions.Tests.zip...
       (ArchiveTestBuild target) -> 
         D:\A\_work\15\s\Tools\publishtest.targets(232,5): error : An exception has occured while trying to compress 'D:\A\_work\15\s\bin/Windows_NT.AnyCPU.Release/System.Globalization.Extensions.Tests/' into 'D:\A\_work\15\s\bin/tests/Windows_NT.AnyCPU.Release/archive/tests/System.Globalization.Extensions.Tests.zip'. [D:\A\_work\15\s\src\System.Globalization.Extensions\tests\System.Globalization.Extensions.Tests.csproj]
```

This needs to be fixed as it is causing non-deterministic failures in our build pipeline.  Assigning to @jhendrixMSFT 

/cc @weshaggard

**Comment by weshaggard** [comment]
cc @tarekgh @MattGal 
We will need to take this into account when building for the different targets and potentially in the universal runner logic, not sure.

**Comment by jhendrixMSFT** [comment]
Fixed in https://github.com/dotnet/buildtools/commit/ae1465a55c36640d4c0ad6588750c931ebd69f88.
