### ISSUE TITLE
VS F5 experience broken again, due to relative path in StartProgram.

### ISSUE THREAD

**Issue by AtsushiKan** [dotnet/buildtools#699]
In test.targets,

     <StartProgram Condition="'$(StartProgram)'==''">$(TestProgram)</StartProgram>

This puts a relative path ("CoreRun.exe") into the F5 executable form. It needs to be the full path, something like

     <StartProgram Condition="'$(StartProgram)'==''">$(StartWorkingDirectory)\$(TestProgram)</StartProgram>

or F5 will not work. VS will not fill in the working directory for you.

**Comment by MattGal** [comment]
Fix for this is in https://github.com/MattGal/buildtools/tree/VS_Debugging_fixes .  I am checking out ways to also fix #700.

**Comment by MattGal** [comment]
Fixed
