### ISSUE TITLE
SendToHelix task is failing to upload json job

### ISSUE THREAD

**Issue by schaabs** [dotnet/buildtools#727]
Recently hit an issue with uploading the job list to helix:

BuildToolsVersion 1.0.25-prerelease-00414-01

    Upload to Azure is complete, a total of 505 items were uploaded.
             Begin uploading blobs to Azure account dotnetbuilddrops in container corefx-master-stress-24111-131-ubuntu.
             Uploading d:\dotnet-reliability\bin/tests/Linux.AnyCPU.Debug/archive/SupplementalPayload.zip to corefx-master-stress-24111-131-ubuntu.
             Upload to Azure is complete, a total of 1 items were uploaded.
           WriteCompletionEvent:
             Writing d:\dotnet-reliability\bin/tests/Linux.AnyCPU.Debug/FuncBuildComplete.json.
         1>d:\dotnet-reliability\Tools\CloudTest.targets(346,5): error MSB4018: The "SendToHelix" task failed unexpectedly.\r [d:\dotnet-reliability\test\genstress.proj]
           d:\dotnet-reliability\Tools\CloudTest.targets(346,5): error MSB4018: Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Current JsonReader item is not an object: StartArray. Path '', line 1, position 1.\r
            [d:\dotnet-reliability\test\genstress.proj]
    d:\dotnet-reliability\Tools\CloudTest.targets(346,5): error MSB4018:    at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader)\r [d:\dotnet-reliability\test\genstress.proj]
           d:\dotnet-reliability\Tools\CloudTest.targets(346,5): error MSB4018:    at Microsoft.DotNet.Build.CloudTestTasks.SendToHelix.<ExecuteAsync>d__17.MoveNext() in d:\buildtools\src\Microsoft.DotNet.Build.CloudTestTasks\SendToHelix.cs
           :line 77\r [d:\dotnet-reliability\test\genstress.proj]
    d:\dotnet-reliability\Tools\CloudTest.targets(346,5): error MSB4018: --- End of stack trace from previous location where exception was thrown ---\r [d:\dotnet-reliability\test\genstress.proj]
    d:\dotnet-reliability\Tools\CloudTest.targets(346,5): error MSB4018:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r [d:\dotnet-reliability\test\genstress.proj]
    d:\dotnet-reliability\Tools\CloudTest.targets(346,5): error MSB4018:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r [d:\dotnet-reliability\test\genstress.proj]
    d:\dotnet-reliability\Tools\CloudTest.targets(346,5): error MSB4018:    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r [d:\dotnet-reliability\test\genstress.proj]
           d:\dotnet-reliability\Tools\CloudTest.targets(346,5): error MSB4018:    at Microsoft.DotNet.Build.CloudTestTasks.SendToHelix.Execute() in d:\buildtools\src\Microsoft.DotNet.Build.CloudTestTasks\SendToHelix.cs:line 45\r [d:\dotnet
           -reliability\test\genstress.proj]
    d:\dotnet-reliability\Tools\CloudTest.targets(346,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()\r [d:\dotnet-reliability\test\genstress.proj]
    d:\dotnet-reliability\Tools\CloudTest.targets(346,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext() [d:\dotnet-reliability\test\genstress.proj]
         1>Done Building Project "d:\dotnet-reliability\test\genstress.proj" (default targets) -- FAILED.

**Comment by MattGal** [comment]
@ChadNedzlek   This is the issue we were just talking about (where POST is redirecting to GET)

**Comment by MattGal** [comment]
@schaabs , looks like @ChadNedzlek  has addressed this now.

**Comment by ChadNedzlek** [comment]
We should point that task to the production servers as well, since staging is... well... staging, and isn't always going to be working.  I'll try to find the place where that happens (I think it's in some targets file somewhere) and update it. But it's just a property that can be overridden by a caller for now.
