### ISSUE TITLE
ValidateApiCompatForSrc causes CopyFilesToOutputDirectory before all files are built

### ISSUE THREAD

**Issue by ericstj** [dotnet/buildtools#728]
The ValidateApiCompatForSrc target depends on CopyFilesToOutputDirectory target and ValidateApiCompatForSrc is called *during* the CoreCompile target. CopyFilesToOutputDirectory tries to copy the resource assemblies to the output directory but those haven't been created yet since that happens as part of CreateSatelliteAssemblies which is sequenced later in the CoreBuild phase (after Compile and some other targets).

I'm seeing this cause failures when the TFS build builds MS.CSharp with OSGroup=Windows_NT.  Apparently this is the only project that actually produces satellite assemblies and is broken by the early execution of CopyFilesToOutputDirectory.

To reproduce do the following:
git clone https://github.com/dotnet/corefx.git
git checkout 67735157bce82ea2306cd36d85446e61e3c66fd3
cd src\Microsoft.CSharp\
msbuild /p:OSGroup=Windows_NT /t:Rebuild

**Comment by ericstj** [comment]
When fixing this please undo the workaround made to the TFS Microsoft.CSharp wrapper project that disabled resource assembly generation.

**Comment by weshaggard** [comment]
Thanks for fixing the internal build, I will try to look into this further. While you were looking into this did you happen to see a better target ordering?

**Comment by ericstj** [comment]
I believe the right fix is to make ValidateApiCompatForSrc not depend on CopyFilesToOutputDirectory at all (so that you don't pull that into the CoreCompile target).  Instead have ValidateApiCompatForSrc use the IntermediateOutputPath where CSC just wrote the assembly.

**Comment by ericstj** [comment]
I didn't attempt to make that fix since it would require an update of buildtools.

**Comment by ericstj** [comment]
I tried out that fix locally and it worked.  I'll submit a PR.
