### ISSUE TITLE
Support dependency validation and upgrade using full package versions

### ISSUE THREAD

**Issue by dagood** [dotnet/buildtools#732]
Now that we have a versions repository that lists every package id and version (https://github.com/dotnet/versions/blob/master/build-info/dotnet/corefx/master/Latest_Packages.txt) we might want to change from validating and updating dependencies based on prerelease to validating full versions. This solves a few problems:

1. We would no longer need to maintain regexes to match package ids that should follow certain validation rules. (Specifically, this could be a problem if some packages come from different builds.)
2. We wouldn't automatically upgrade a prerelease without upgrading the minor/patch version anymore. For example, if `1.0.0-rc2-01` becomes `1.0.1-rc2-02`, our current upgrading system would upgrade to `1.0.0-rc2-02`, breaking things. We currently make sure this doesn't happen in a post-restore step, but upgrading based on full package version would remove this problem.

This does mean we would have to keep the current version of every dependency checked into a central file in corefx, wcf, and coreclr rather than having a single property for prerelease. It would be great to pair this change up with one that lets us centralize the *actual* dependencies being used, where projects somehow get their versions from a single source.

With the central file, an upgrade can check the latest version on the versions repo and see which versions need to be updated. The central file is updated as well as any project.jsons. Then the dependency validation step just checks project.jsons for consistency with that central file.

/cc @weshaggard @ericstj @jhendrixMSFT @chcosta @eerhardt

**Comment by weshaggard** [comment]
>This does mean we would have to keep the current version of every dependency checked into a central file in corefx, wcf, and coreclr rather than having a single property for prerelease. It would be great to pair this change up with one that lets us centralize the actual dependencies being used, where projects somehow get their versions from a single source.

I don't think we actually need to check that in do we? I was hoping we might just be able to point to the exact package list via it's sha via the github url. Is there any reason that wouldn't work?

**Comment by dagood** [comment]
It would add an extra network dependency during a `sync /p` to validate (maybe just the first `sync /p` if we cache the result), but other than that I like that idea, didn't think of it.

**Comment by weshaggard** [comment]
Yes I think we could pull it down and cache it.

**Comment by dagood** [comment]
For the validation part of this, I'm not sure what to do about our "misc" packages: https://github.com/dotnet/corefx/blob/604ed96/dir.props#L115-L134. Maybe checking to see if all project.jsons have the same version of non-auto-upgraded packages is enough?

**Comment by weshaggard** [comment]
I think it would be reasonable to just point to a package and version list that is checked into the repo for these packages.
