### ISSUE TITLE
Move native symbol package creation logic into buildtools

### ISSUE THREAD

**Issue by dagood** [dotnet/buildtools#745]
Right now native symbol packages are created differently in https://github.com/dotnet/coreclr/tree/master/src/.nuget/Microsoft.NETCore.Runtime.CoreCLR vs https://github.com/dotnet/corefx/tree/master/src/Native/pkg although the core logic could be shared. We should move what we can into buildtools, especially any symbol "discovery" functionality that could be applied across packages in any .NET Core repository.

A few things that should go along with this: including pdbs for exe files and more focused review/refinement of the logic.

/cc @weshaggard @ericstj

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
