### ISSUE TITLE
VS F5 not working out of the box when targeting NETFramework

### ISSUE THREAD

**Issue by mrgleba** [dotnet/buildtools#752]
I'm porting a project (web service on Kestrel) from RC1 tooling to RC2.
The project is targeting net451 as I'm still stuck with some libs that are not yet ported.

On hitting F5:
 - compilation goes fine and exe is created in bin\Debug\net451
 - libuv is *not* copied to bin\Debug\net451
 - VS tries to run exe from bin\Debug\net451\win10-x64 and fails as there is no such directory

I was able to work around by seting "executablePath" explicitly in launchSettings.json

**Comment by davidfowl** [comment]
This has nothing to do with this repository.

**Comment by mrgleba** [comment]
Sorry then :(
Any idea where it should be reported ?

**Comment by davidfowl** [comment]
aspnet/Home
