### ISSUE TITLE
Include [ComVisible(false)] in generated _AssemblyInfo.cs file

### ISSUE THREAD

**Issue by stephentoub** [dotnet/buildtools#77]
Per the discussion at https://github.com/dotnet/corefx/pull/782, we're scrubbing [ComVisible] attribution from the CoreFX sources.  If the resolution of that discussion is that we should have an [assembly: ComVisible(false)] attribute in every assembly, we should put it in the generated _AssemblyInfo.cs file that's generated as part of the build.

**Comment by AlexGhiondea** [comment]
LGTM

**Comment by weshaggard** [comment]
The support for this has been included in the build tools we now just need to decide whether or not we include it by default by setting AssemblyComVisible=false in our src\dir.targets in the CoreFX repo.

**Comment by weshaggard** [comment]
We have support for this in the build targets but right now we aren't putting any AssemblyComVisible attributes on our assemblies. I'm closing this issue as it was more about adding support for this if we feel we need to set it to false then we just need to set the AssemblyComVisible property to false in our dir.props for the repo.
