### ISSUE TITLE
Add feature to auto-upgrade to group dependencies by rules

### ISSUE THREAD

**Issue by dagood** [dotnet/buildtools#779]
One way to solve the merge conflicts we saw in https://github.com/dotnet/corefx/pull/9028 is to add newlines between the different sets of dependencies that are updated simultaneously. This could be done in the auto-upgrade task.

**Comment by dagood** [comment]
This could be brittle if we add/remove dependencies without running the ordering, but the worst that happens is a merge conflict. After fixing the merge conflict, the dependencies are back in order.

**Comment by bartonjs** [comment]
Yeah, we'll still get merge conflicts when dependencies are added.

Maybe my thinking here is naive, but: Won't most of our references flip to stable after RTM?  That would mostly eliminate the changes from the task, which would therefore mostly eliminate the conflicts.

**Comment by dagood** [comment]
Well, that's only if they're added without caring at all about the grouping, I'm pretty sure. As long as the dependency-adder either adds it to the right group, runs the tooling, or adds a newline before their new dependency at the end of the deps section, the next upgrade PR should handle it ok.

**Comment by dagood** [comment]
I *think* that https://github.com/dotnet/corefx/blob/master/src/Common/test-runtime/project.json will always be upgraded, so would always cause merge conflicts for the overall PR without a newline. I agree that there won't be as many, though.

**Comment by dagood** [comment]
Closing since we're going with the "all upgrades in one PR" fix instead.
