### ISSUE TITLE
Disable live packaging task dll after updating buildtools version in buildtools

### ISSUE THREAD

**Issue by ericstj** [dotnet/buildtools#780]
I had to run against the live task to get a NuGet fix.  Disable this once we've updated the buildtools package version used by buildtools repo to one that has the fix.

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
