### ISSUE TITLE
PInvoke checker data files are too sparse

### ISSUE THREAD

**Issue by ericstj** [dotnet/buildtools#788]
The logic for applying the pinvoke checker data files is really flaky.  We should look at all the targetgroups we have holistically and map the right data file to all of them.  We should also provide a way for TargetGroup='' to say what it actually represents.

One thought here is a layer of indirection where we map the project settings to some named API grouping (eg: OneCore, UWP, Win8, ClassicDesktop, etc) and then use that to find the data file.  If the API grouping is already set directly in the project, don't try to calculate it.

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
