### ISSUE TITLE
Visual Studio crashes when publishing to Azure App Service

### ISSUE THREAD

**Issue by cdomino** [dotnet/buildtools#799]
Hello -

I have a dnx46 web project that's currently working on (mostly) RC1 bits started a few months ago on the preview templates.  On the same machine (Windows Server 2012 R2 + VS 2015 Update 2) I cannot publish a vanilla (no changes made from the VS template) web project to Azure. VS crashes at various stages of the publish (see attached).  Some observations:

- Doing a clean on the project seems to help it get further in the publish before crashing.
- I've experiencing this with projects targeting .NET 4.6 and 4.6.1 as well as Core.
- It runs fine through Visual Studio

Let me know what else i can tell you.

Thanks!

[2. Mid-publish.docx](https://github.com/dotnet/buildtools/files/312762/2.Mid-publish.docx)
[1. Publish settings.docx](https://github.com/dotnet/buildtools/files/312763/1.Publish.settings.docx)

**Comment by weshaggard** [comment]
This isn't relevant to BuildTools repo so closing.

**Comment by cdomino** [comment]
Can you recommend where I should post this please?

 

Thanks!

**Comment by weshaggard** [comment]
I believe you can try https://github.com/aspnet/tooling.
