### ISSUE TITLE
GenAPI fails not being able to find System.Linq.dll

### ISSUE THREAD

**Issue by KrzysztofCwalina** [dotnet/buildtools#811]
I forket the repo and built it from command line. Then I tried to run GenAPI and got the following error:
![image](https://cloud.githubusercontent.com/assets/9724236/16088035/19024b36-32da-11e6-812d-21f6556bf35f.png)

**Comment by weshaggard** [comment]
Which version of genapi did you run? The desktop or core version?

**Comment by weshaggard** [comment]
This is not an issue if you are running the desktop version which is properly published.
