### ISSUE TITLE
Add validation to detect stable runtime packages depending on prerelease packages

### ISSUE THREAD

**Issue by weshaggard** [dotnet/buildtools#820]
We need to ensure any runtime dependencies going into runtime.json are also stable if the package containing it is stable.

**Comment by ericstj** [comment]
NuGet detects direct dependencies but not runtime.json dependencies.  We need to do that.

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
