### ISSUE TITLE
Move UpdatePublishedVersions.ps1 to buildtools

### ISSUE THREAD

**Issue by dagood** [dotnet/buildtools#823]
`UpdatePublishedVersions.ps1` is in a few places:
* https://github.com/dotnet/corefx/blob/master/UpdatePublishedVersions.ps1
* https://github.com/dotnet/coreclr/blob/master/UpdatePublishedVersions.ps1
* The TFS build auto-publisher
* Soon, WCF

There isn't any big reason to differentiate the file between repos, so it should be centralized.

Also consider centralizing `UpdateDependencies.ps1` (corefx, coreclr, wcf) at the same time.

/cc @weshaggard @jhendrixMSFT @ericstj @eerhardt

**Comment by weshaggard** [comment]
agreed thanks for filing this issue.
