### ISSUE TITLE
Update lineup/platforms references in buildtools

### ISSUE THREAD

**Issue by ericstj** [dotnet/buildtools#831]
Need to bump version to 1.0.2 in https://github.com/dotnet/buildtools/blob/3c700d1ecc358c6c1b3ffbaaeb49e7864a8e9ba7/src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets#L86

**Comment by ericstj** [comment]
Lineup is now at 1.0.3, Platform is at 1.0.2

**Comment by dleeapho** [comment]
Still applicable?

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
