### ISSUE TITLE
Make UpdateDependencies.ps1 update all in one PR, updating existing PR if possible

### ISSUE THREAD

**Issue by dagood** [dotnet/buildtools#835]
Instead of opening separate PRs for each dependency group in the versions repo, make a single PR with all upgrades necessary to make dependency state current. This:
* Fixes the merge conflict problem.
* Reduces PR noise.
* Reduces CI strain.
* Simplifies the versions repo subscription.

To help even more, we should update an existing dependency upgrade PR rather than opening a new one if possible. We could have the bot do a force push (to keep number of commits down) or push a new commit (to keep intermediate CI results easily visible). Either way sounds good to me.

(Depends on https://github.com/dotnet/buildtools/issues/823 bringing the script into buildtools.)

Related earlier discussion about this: https://github.com/dotnet/corefx/issues/9156

**Comment by weshaggard** [comment]
I'm all for it.
