### ISSUE TITLE
Incremental build drops source files

### ISSUE THREAD

**Issue by ericstj** [dotnet/buildtools#846]
See comment: https://github.com/dotnet/buildtools/commit/65080e8a3bd132cfe51ebe73009f75cef02c9b1d#commitcomment-18068059

I noticed this when building packages because our symbol packages include all source files and on an incremental build were dropping _AssemblyInfo.cs and SR.cs

**Comment by ericstj** [comment]
Yep, SR.cs followed the same bad pattern.
https://github.com/dotnet/buildtools/blob/d25c6128ceb345040773480e55322931a3ec2b6e/src/Microsoft.DotNet.Build.Tasks/PackageFiles/resources.targets#L23

**Comment by tarekgh** [comment]
does this cause compile error with the incremental build?

**Comment by weshaggard** [comment]
Yes it could end up causing compile issues and missing assembly information.

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
