### ISSUE TITLE
Merge change of CommandLine.cs from the run folder to the common folder

### ISSUE THREAD

**Issue by maririos** [dotnet/buildtools#857]
The Run Command Tool (merged with PR #672 ) is using a copy of the class CommandLine.cs.
Instead of having a copy we would like to merge the changes from the class under Run to the CommandLine.cs class under the common folder.

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
