### ISSUE TITLE
Run command doesn't show colors

### ISSUE THREAD

**Issue by dagood** [dotnet/buildtools#864]
Specifically, color no longer shows up in the msbuild output when I run `build`. This makes it hard to spot build errors and warnings.

(Running `build` using `cmd.exe` on win10.)

/cc @maririos

**Comment by joperezr** [comment]
FYI @AlexGhiondea developed a .NetCore library that helps you print in the Console with color. @maririos perhaps you can leverage that in Run.exe ?

**Comment by dagood** [comment]
I did a bit of searching back when I filed this, and the email reminded me to comment about it. :smile:

I don't know if colors are possible while redirecting the output, because the color is a property of the console and msbuild uses that rather than something capturable like ANSI control sequences. Hoping I'm missing a way to do this.

My workaround is to write out an error-only log (`build -- /flp1:errorsonly;logfile=msbuild.err`) and look at that after the build's done. In theory, Run could do this itself and print out the file in red after the build's done, but it might conflict with flp's set up manually and in any case is probably not worth it.

**Comment by maririos** [comment]
Are you talking about the colors at the end of the build? when you have like the summary of what happened? or the colors while it is building.

For the first case, there may be a way to do it. We could look at every line msbuild is dropping and with a regex see if it is an error or a warning and according to that change the color. We'll need to try it though because I'm not sure.

For the second one, it is easy to add the error log files to run, but msbuild is already printing the summary so it would be weird to have it twice, but one in white and one in red.

**Comment by dagood** [comment]
Ah, in buildtools there is no summary, so I didn't think about that vs. the workaround. The during-build coloring is what I noticed missing when Run was integrated, but trying out `-- /v:N` now, I do miss having color in the summary too. Not sure if it's worth regexing over msbuild output though.

**Comment by mellinoe** [comment]
Is there really no way to "intercept" the output from the process without messing up the colors, and still getting whatever info we need? Doesn't CLI do something like this? I know a lot of stuff was broken by that for a while, but it seems okay lately.

**Comment by dagood** [comment]
Ooh! https://github.com/Microsoft/msbuild/pull/505 added a flag to enable ANSI colors. You can try it out with `build -- /clp:ForceConsoleColor`. My warnings are yellow again. :smile: This would mean you'd have to strip them out if someone else is trying to parse the msbuild output, though, I think.

**Comment by maririos** [comment]
:| I'm running `build -- /clp:ForceConsoleColor ` in BuildTools and I don't see the colors! am I missing something? It would be really cool if it is just that easy

**Comment by maririos** [comment]
@mellinoe no. Calling Process.start only retrieves text, so the color format that mbuild has is getting lost.
@sokket do you have a workaround for this in CLI?

**Comment by dagood** [comment]
Hmm, well search results say that the Windows console doesn't support ANSI color codes without some tweaks, but as far as I know I haven't done anything to enable them on my Win10 install. In any case, since ANSI codes are part of the output text, Run should be able to look for them and replace them with `Console` calls for compatibility. That may be more complex than it's worth--and maybe there's a simpler way that I don't know.

**Comment by sokket** [comment]
@maririos, @piotrpMSFT or @eerhardt would be good contacts to ask :)

**Comment by eerhardt** [comment]
See https://github.com/dotnet/cli/blob/rel/1.0.0/src/Microsoft.DotNet.Cli.Utils/AnsiConsole.cs and https://github.com/dotnet/cli/blob/rel/1.0.0/src/Microsoft.DotNet.Cli.Utils/AnsiColorExtensions.cs for how the CLI handles colors.

**Comment by eerhardt** [comment]
Also - https://github.com/dotnet/cli/blob/rel/1.0.0/src/Microsoft.DotNet.Cli.Utils/StreamForwarder.cs for how the CLI captures a child process's output, and forwards it to the current process's stdout/err

**Comment by dagood** [comment]
@eerhardt That does require the child process to emit ANSI color codes, right?

**Comment by eerhardt** [comment]
> @eerhardt That does require the child process to emit ANSI color codes, right?

I'm not sure.

**Comment by dagood** [comment]
Assuming it does, that `AnsiConsole` class would be handy here: if Run executes msbuild with `/clp:ForceConsoleColor` (and if it works), then the `AnsiConsole` class can parse the codes and translate to the "normal" `Console` api, leaving the text output clean.

(Could also think about reusing more stuff if we pull in that utils package.)

**Comment by weshaggard** [comment]
I agree we should fix it so we can see the colors again. We also need to have it output the summary with the number of warnings and errors at the end of the build, otherwise it is really hard to get an idea of what happen during the build.
