### ISSUE TITLE
apigen.exe generating code that does not compile.

### ISSUE THREAD

**Issue by esdrubal** [dotnet/buildtools#869]
While generating api of mscorlib v4.6.2, apigen.exe  generates code that does not compile:

Using v4.6.2 reference assemblies

And doing on windows:
```
genapi.exe v4.6.2/mscorlib.dll > out.cs
csc.exe /unsafe /w:0 out.cs
```

Here is  one of the problematic lines:
```[System.Runtime.CompilerServices.IteratorStateMachineAttribute(typeof(System.Collections.Concurrent.ConcurrentDictionary<TKey, TValue>.<GetEnumerator>d__35))]```

**Comment by ericstj** [comment]
Dup of https://github.com/dotnet/buildtools/issues/658

**Comment by ericstj** [comment]
Fixed in https://github.com/dotnet/buildtools/pull/922
