### ISSUE TITLE
Update Xamarin Assembly lists

### ISSUE THREAD

**Issue by ericstj** [dotnet/buildtools#877]
Here are the latest file lists.  We should translate these to xml and update our validation lists.

[monotouch_watch.txt](https://github.com/dotnet/buildtools/files/364538/monotouch_watch.txt)
[xammac_net_4_x.txt](https://github.com/dotnet/buildtools/files/364540/xammac_net_4_x.txt)
[monodroid.txt](https://github.com/dotnet/buildtools/files/364542/monodroid.txt)
[monotouch.txt](https://github.com/dotnet/buildtools/files/364539/monotouch.txt)
[monotouch_tv.txt](https://github.com/dotnet/buildtools/files/364541/monotouch_tv.txt)

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
