### ISSUE TITLE
BuildVersionFile generated matches the time zone of builder; Build controller may not be in the same time zone

### ISSUE THREAD

**Issue by MattGal** [dotnet/buildtools#882]
@jhendrixMSFT  @chcosta  @karajas 

The file BuildVersion-**DATE**.props is generated by the following in BuildVersion.targets:

    <BuildVersionFile Condition="'$(BuildVersionFile)'==''">$(BuildVersionFilePath)BuildVersion-$(TodayTimeStamp).props</BuildVersionFile>

    <TodayTimeStamp>$([System.DateTime]::Now.ToString(yyyyMMdd))</TodayTimeStamp>

However, for our VSO automated build processes, the build controller runs in UTC time zone (PST + 7) while the agents run in PST.  So, we see build failures due to VSO builds looking for files emitted in an earlier step due to the build # (which encapsulates the date) being 1 day ahead.  (any build where this file is generated before 5 PM PST would hit this).

I don't expect everyone would want this file's date to be in UTC either (otherwise it'd be a super easy fix).  
I propose either: 

- Remove date from this file name, put the date information inside the file or otherwise use metadata to make this decision.
- Providing a special property like "BuildVersionUTCDate" which if true uses DateTime.UtcNow instead of DateTime.Now.

**Comment by jhendrixMSFT** [comment]
@joperezr I think this is similar to the issue you're investigating.

**Comment by MattGal** [comment]
From chatting w/ Joel, this should be overwritten when property "OfficialBuildId" is provided.  I can't find evidence that ever worked though.

**Comment by joperezr** [comment]
Closing since this was fixed with #885
