### ISSUE TITLE
Failed to start ASP.Net Core application from VS when custom output name is used

### ISSUE THREAD

**Issue by maxim-boligatov** [dotnet/buildtools#886]
I am not sure if it is correct place for this issue. But I have not found more appropriate place. 

## Steps to reproduce
1. Create ASP.Net Core  web application (.Net Framework) with name Web.Site in VS
2. Use outputName property in buildOptions to specify custom name of assembly (for example "outputName": "MyCompany.Web.Site").
3. Try to start application from VS or try to run debug.

## Expected  behavior
Started application....

## Actual behavior
In case of Start without debugging: HTTP Error 502.5 - Process Failure 
In case of Start with debugging: window with message "Unable to start process [Name]. Process creation failed with the error: The system cannot find the file specified."

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64

So it looks that the image for execution is not found.

**Comment by joperezr** [comment]
Hello Maxim, thanks for your contribution! This repo is where we have the source for all of the tools that we use in order to build our other repos(.Net Core framework, CLR, etc.). I believe this issue probably belongs on the [ASP.NET Core repo instead](https://github.com/dotnet/buildtools/issues/886) If it's ok by you, I would like to move it there to have the right people looking at it. Thanks again.

**Comment by maxim-boligatov** [comment]
Hello )) Yes of course, please move it to corresponding place. If it is possible please put here reference to new thread (moved).

**Comment by joperezr** [comment]
Done, you can go [here](https://github.com/aspnet/Home/issues/1680) to track the new issue. I'll close this one given the other is now tracking the bug.
