### ISSUE TITLE
run.exe crashes on empty file

### ISSUE THREAD

**Issue by TyOverby** [dotnet/buildtools#888]
with an empty config.json file, run.exe crashes with the error:

```
Running: C:\Users\tyoverby\workspace\roslyn-internal\Open\Tools\dotnetcli\dotnet.exe C:\Users\tyoverby\workspace\roslyn-internal\Open\Tools\run.exe
Error: Object reference not set to an instance of an object.    at Microsoft.DotNet.Execute.Executor.<>c__DisplayClass17_0.<DefineParameters>b__0(CommandLineParser parser)
   at Microsoft.Fx.CommandLine.CommandLineParser.Parse(Action`1 parseBody, Action`1 helpHandler, Action`2 errorHandler, Setup setupContent, String[] args)
   at Microsoft.Fx.CommandLine.CommandLineParser.ParseForConsoleApplication(Action`1 parseBody, String[] args, Setup setupContent)
   at Microsoft.DotNet.Execute.Executor.DefineParameters(String[] args, Setup setupInformation)
```

**Comment by joperezr** [comment]
I don't believe we want to support this case. Either way I'm assigning this to @maririos so that she can better evaluate.

**Comment by maririos** [comment]
I'll add a condition to print an error message.

**Comment by maririos** [comment]
@TyOverby I'm not able to repro the issue.
I have an empty config.json file and when calling sync.cmd/build.cmd/run.cmd the error message is:
```
Error: Could not load Json configuration file.
```
Is there something I'm missing?

**Comment by TyOverby** [comment]
> Is there something I'm missing?

Nope, that was it.  Maybe it was inadvertently fixed by another change?

**Comment by maririos** [comment]
I haven't change this part of the code, but I;m glad it works :)
I'm closing the issue then.

Thanks Ty!
