### ISSUE TITLE
Add buildtools to versions repository, allowing auto-update with Maestro

### ISSUE THREAD

**Issue by dagood** [dotnet/buildtools#892]
We should have buildtools update an entry in https://github.com/dotnet/versions/tree/master/build-info/dotnet so that other repos can get automatic PRs for new builds through Maestro.

When someone updates buildtools, the changes tend to target a specific repo, but it will be useful to check for breaks in other repos early. (Rather than only noticing when an update is needed and getting blocked.)

/cc @eerhardt @weshaggard @jhendrixMSFT

**Comment by dleeapho** [comment]
We should link to the core-eng issue tracking this.

**Comment by dagood** [comment]
@eerhardt completed this, reassigning and closing as resolved.
