### ISSUE TITLE
Cannot reference portable nupkg from corefx test projects

### ISSUE THREAD

**Issue by nguerrera** [dotnet/buildtools#90]
See dotnet/corefx#950. There is currently a dependency on the nupkg explicitly mentioning aspnetcore50.

I'm working around it with a binary reference while excluding the package from packages.config. (This only works because we have to build the src/ project first which guarantees that the package will have been restored.)

**Repro steps in dotnet/corefx**
1. Clean entire enlistment (git clean -fdx)
2. Remove any <Reference> or <ProjectReference> to System.Collections.Immutable.dll from System.Reflection.Metadata.Tests.dll.
3. Add System.Collections.Immutable to System.Reflection.Metadata.Tests packages.config  
4. Build System.Reflection.Metadata.sln in VS
5. Set tests as startup project 
6. Run (Cltrl+F5)

**Expected result** 
Build succeeds without warning and tests run successfully.

**Actual result**
Build warns about not "finding a matching group" and tests fail due to missing System.Collections.Immutable.dll.

**Comment by nguerrera** [comment]
/cc @FiveTimesTheFun @weshaggard @akoeplinger 

I will send out a PR with workaround to close dotnet/corefx#950, but this tracks getting the core issue resolved in buildtools.

**Comment by MichaelSimons** [comment]
Triage: this shouldn't be applicable anymore.
