### ISSUE TITLE
Reference Assembly generation

### ISSUE THREAD

**Issue by raffaeler** [dotnet/buildtools#904]
I am using the following nuget package to generate the sources for a reference assembly:
https://www.nuget.org/packages/Microsoft.DotNet.BuildTools.GenAPI

The generated code contains the following attribute for each method returning a task:
        [System.Runtime.CompilerServices.AsyncStateMachineAttribute(typeof(Xyz.Abc.MyClass.<GetAuthenticationCookie>d__34))]

The problem is the "AsyncStateMachineAttribute" is not available in all the framework flavors.
Is this attribute really needed?
Can I specify not to write it in the generated source code?

Thank you

**Comment by ericstj** [comment]
I believe this is a duplicate of https://github.com/dotnet/buildtools/issues/658

**Comment by ericstj** [comment]
Fixed in https://github.com/dotnet/buildtools/pull/922
