### ISSUE TITLE
Remove fork of ResolveNuGetPackageAssets 

### ISSUE THREAD

**Issue by ericstj** [dotnet/buildtools#917]
Once we have a way to consume ResolveNuGetPackageAssets x-plat we should remove our fork of it.  This should be coming with the dotnet-CLI-msbuild work.

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
