### ISSUE TITLE
Change the name for Xunit.PlatformID to avoid type conflicts

### ISSUE THREAD

**Issue by joperezr** [dotnet/buildtools#936]
On netstandard1.7 we are adding back System.PlatformID which will now cause ambiguity with Xunit.PlatformID unless the fully qualified name is specified. We should rename Xunit.PlatformID to avoid this.

**Comment by weshaggard** [comment]
cc @stephentoub @Priya91

**Comment by weshaggard** [comment]
Fixed with https://github.com/dotnet/buildtools/pull/1084.
