### ISSUE TITLE
On auto-upgrade, post errors/warnings to PR to make them visible

### ISSUE THREAD

**Issue by dagood** [dotnet/buildtools#942]
Currently they only show up in the Maestro build, and nobody checks those unless something goes obviously wrong. It would be useful to post errors and warnings into the PRs, giving them high visibility.

This should be doable by making a trace listener in the msbuild task, but we should aim for something that's reusable with only VersionTools.

**Comment by dagood** [comment]
Small thing to add to this: making sure two loaded buildinfos don't share any packages. That's a consistency error in the versions repo, and this is a good way to surface it.

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
