### ISSUE TITLE
Need a way to disable tests for different TestTFM

### ISSUE THREAD

**Issue by weshaggard** [dotnet/buildtools#960]
Now that we are running our tests for various TestTFM's we need a way to disable a test for a given TestTFM.

See https://github.com/dotnet/buildtools/blob/4bc8723ed65c6e6921649d196ed6f14bdfafdd7a/src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets#L61 for the list of TestTFMs.

**Comment by weshaggard** [comment]
@Chrisboh @markwilkie do one of you guys have someone to add this functionality?

**Comment by Priya91** [comment]
@Chrisboh @weshaggard Since i need this in my PR, if it's not being worked on, i will pick this up.

**Comment by weshaggard** [comment]
Thanks @Priya91
