### ISSUE TITLE
Package-Dependency verification should not open repo files with write access.

### ISSUE THREAD

**Issue by AtsushiKan** [dotnet/buildtools#964]
The new dependency verification step injected into "sync -p" by this PR (https://github.com/dotnet/buildtools/pull/953) causes hundreds of "UnauthorizedAccessExceptions" on

  .\dependencies.proj
  and every project.json in the tree.

Yes, I "attrib +r" all repo files I'm not actively working on. It's the one aspect of TFS I prefer to Git. It's also convenient for catching things that sneak changes into my files.

[Goes to add "set SkipVerifyPackageVersions=true" to my cmd windows for CoreFx]

Since this process is only checking (autofix is supposed to be off by default), it should not be demanding  write permissions on these files.

@dagood

**Comment by dagood** [comment]
Thanks for filing, I'll check it out. I agree it shouldn't be trying to get write access.
