### ISSUE TITLE
Run tool, suppress run output option?

### ISSUE THREAD

**Issue by chcosta** [dotnet/buildtools#973]
I intend to add an option to the run tool to suppress its output from printing to the console.  MsBuild, for example, has a "/nologo" option which is used to prevent printing its header information to the console when it runs.  I'd like a similar option to run which suppresses "run" output and only displays output of the command I'm actually running.

Suppressing the output from here - https://github.com/dotnet/buildtools/blob/master/src/Run/Setup.cs#L87

Ideally, this would also be configurable from within a specific command in config.json so that you could always say, "if I execute 'run produces', it just gives me the clean output of that command."  

This feature would enable us to more easily pipe run output to other commands.

Please let me know if there is any concern with this or this conflicts with other work / design goals in progress for run.

/cc @maririos @weshaggard

**Comment by maririos** [comment]
So you would only want the output that MsBuild is directly producing?
https://github.com/dotnet/buildtools/blob/master/src/Run/RunProcess.cs#L57

**Comment by chcosta** [comment]
Yes, I don't want these...

https://github.com/dotnet/buildtools/blob/master/src/Run/Setup.cs#L93
https://github.com/dotnet/buildtools/blob/master/src/Run/Setup.cs#L100
https://github.com/dotnet/buildtools/blob/master/src/Run/Setup.cs#L105

Perhaps there are more.  error output or exceptions from the tool itself might be ok as well.
