### ISSUE TITLE
Is it mandatory for settings and commands to have different names?

### ISSUE THREAD

**Issue by maririos** [dotnet/buildtools#974]
Right now the Settings, the Commands or the Alias names can't have the same name in the config.json file.
This is now causing problems when defying a setting that is a target in MsBuild and a Command with the same name.
For more information see PR dotnet/corefx#11003.

We should take a look to see if it is possible to work around this.

**Comment by dleeapho** [comment]
Run command cleanup?

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
