### ISSUE TITLE
Condition for Property 'IsTestProject' is CoreFX specific

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/buildtools#977]
https://github.com/dotnet/buildtools/blob/04599faf85856b754a1969f23095e28181e564e3/src/Microsoft.DotNet.Build.Tasks/PackageFiles/Build.Common.targets#L8 

This check sets the property 'IsTestProject' to 'true' on the condition that the project in question has a name that ends with '.Tests'. This condition is specific to the coreFX repo, which should not be the case. We use this property for building tests against packages (the relevant targets won't get invoked if this property isn't set to 'true'), so anyone wanting to build tests against packages would need to manually set that property themselves, which is very far from obvious.

**Comment by weshaggard** [comment]
The default convention is general and corefx happens to match that convention, but there isn't anything that prevents folks to set IsTestProject in their repo's targets.
