### ISSUE TITLE
Change dependency verification "source of truth" to repo API Consumes command json

### ISSUE THREAD

**Issue by dagood** [dotnet/buildtools#983]
Instead of [`dependencies.props`](https://github.com/dotnet/corefx/blob/0743d949b8d7a63f8e7f9ff3b5023b1a8fa8618a/dependencies.props#L2-L7) being the source of truth, this info can be stored in the format of Repo API [`consumes`](https://github.com/dotnet/buildtools/blob/master/Documentation/RepoCompose.md#consumes).

This gives us a simple implementation of the `consumes` command in buildtools-using repos: just output this json file. `change` is also simple: replace the contents of this file, then run `UpdateDependencies` to synchronize the repo to the new truth.

Not downloading the build-infos at verify-time does mean this data is essentially duplicated in the product repo, but I think that's minor compared to the benefit to the repo API commands and offline product builds.

---

A few notes on the implementation that I don't want to forget:
- When doing auto-upgrade using this system, if a new package is added to the build-info we don't want to miss it. It can't always just be added to the list of `floating` dependencies, though, because it might be skipped (for example in dev/api). So only ensure all packages are in the floating list that aren't already in the `stable` list.
- We need to allow multiple versions of the same package as `stable` dependencies. (Specifically for a dev/api quirk, at the moment.)

**Comment by dleeapho** [comment]
Not sure if BfS changes this. Closing for now.
