### ISSUE TITLE
Use new build-info structure (using Repo API) when publishing to dotnet/versions

### ISSUE THREAD

**Issue by dagood** [dotnet/buildtools#986]
Instead of publishing a package list and a release file as a versions repo build-info, use a single json file that contains output from Repo API commands plus some build metadata.

Outputs that should be included:
- Build metadata: build id, product repo commit sha.
- ~~[`produces`](https://github.com/dotnet/buildtools/blob/master/Documentation/RepoCompose.md#produces): a list of all package ids and versions produced, organized by platform.~~ (This is included in the `publish` input.)
- [`consumes`](https://github.com/dotnet/buildtools/blob/master/Documentation/RepoCompose.md#consumes). This makes it easy to traverse repo dependencies without cloning every repo and running the command locally (although that would be possible given the repo commit sha in the metadata).
- [`publish`](https://github.com/dotnet/buildtools/blob/master/Documentation/RepoCompose.md#publish): a list of artifacts produced and where they were published. As the spec is written, this is the _input_ to `publish`, but it seems reasonable to put on the versions repo. (Should we manually change this data when the packages are published to nuget.org?)

For repos that don't have the full Repo API implemented (I believe nobody does as of now) VersionTools can format the current data into something that fits the repo API format.

@eerhardt I think this ends up including all the info you suggested in your proposal, do you see anything missing or wrong here?

/cc @jhendrixMSFT @weshaggard @jaredpar

**Comment by eerhardt** [comment]
> I think this ends up including all the info you suggested in your proposal, do you see anything missing or wrong here?

I agree this should satisfy what I was proposing for better build-info. The only thing I see missing is that there can be other types of assets besides NuGet packages.  `core-setup` and `cli` produce zips and installers as well as NuGet packages.  So we should be sure to allow for `produces` and `consumes` that aren't NuGet packages.

**Comment by dagood** [comment]
The spec includes other assets, I just didn't think to point it out--check out [Artifact Specification](https://github.com/dotnet/buildtools/blob/master/Documentation/RepoCompose.md#artifact-specification) and the samples.

Rereading the spec a bit, I see that it actually says `publish` is an augmented `produces`--so I don't think including the `produces` output in the build-info is necessary. (Editing this issue.)

**Comment by dleeapho** [comment]
BfS probably changes this. Closing for now.
