### ISSUE TITLE
Xunit.PlatformID should be plural

### ISSUE THREAD

**Issue by justinvp** [dotnet/buildtools#999]
This is very nit-picky, but it's a pet peeve of mine: It'd be nice if the .NET Core code followed the framework design guidelines, even in test infrastructure code, so it feels familiar to .NET developers.

[`Xunit.PlatformID`](https://github.com/dotnet/buildtools/blob/master/src/xunit.netcore.extensions/PlatformID.cs) is a flags enum, and according the [design guidelines](https://msdn.microsoft.com/en-us/library/ms229040(v=vs.110).aspx), it should be plural:

> ✓ DO use a singular type name for an enumeration unless its values are bit fields.
> ✓ DO use a plural type name for an enumeration with bit fields as values, also called flags enum.

Thus, I'd like to rename `PlatformID` to `PlatformIDs` (plural) to follow the .NET conventions we're used to.

Renaming has an additional benefit: the plural name would no longer conflict with [`System.PlatformID`](https://github.com/dotnet/corefx/blob/c4538cc3e6d3c28318e50ce81d5c2137c91b0d44/src/System.Runtime.Extensions/ref/System.Runtime.Extensions.cs#L685-L694), which is being added back in the dev/api branch in CoreFX. Renaming the test enum means we'll no longer need to  [fully qualify it with the namespace](https://github.com/dotnet/corefx/blob/722c529bb3b4096564c33303568e8e99a350100b/src/System.Globalization/tests/CultureInfo/CultureInfoCurrentCulture.cs#L103) anymore, e.g. instead of `[PlatformSpecific(Xunit.PlatformID.AnyUnix)]` it could simply be `[PlatformSpecific(PlatformIDs.AnyUnix)]`.

I know this will cause some churn, and for a seemingly minor benefit, but I'd be happy to do the work to make it happen, opening a PR in this repo to do the rename, along with PRs in the repos that need to be updated as a result.

cc: @weshaggard @stephentoub @Priya91

**Comment by justinvp** [comment]
Or maybe even just: `Platforms`?

```c#
[PlatformSpecific(Platforms.AnyUnix)]
[ActiveIssue(###, Platforms.Windows)]
```

**Comment by weshaggard** [comment]
I have another reason to rename this which is that in conflicts with System.PlatformID which we have recently exposed and we had to use alias' to disambiguate. @joperezr I believe you hit that issue recently. 

So I think we should rename it but Platforms might be a little to general, PlatformIDs seems a little better to me.

**Comment by mellinoe** [comment]
`TestPlatform` ? Or something else with "Test" in the name?

**Comment by weshaggard** [comment]
I'd be OK with TestPlatforms

**Comment by Priya91** [comment]
I'm not going to get this done anytime soon..

**Comment by justinvp** [comment]
+1 to `TestPlatforms`.

@Priya91, I can submit a PR.

Should I...

1. Add `TestPlatforms` as a new enum and leave `PlatformID` for now (updating the attributes to support both) to make the transition easier? Then, after all uses have been updated (e.g. in CoreFX repo), follow-up by deleting `PlatformID` altogether?
2. Or just go ahead and rename `PlatformID` to `TestPlatforms` now, and force the change in CoreFX during the next buildtools update?

**Comment by justinvp** [comment]
Went with 1. PR: #1000

**Comment by weshaggard** [comment]
I like option #1 as well.
